# CardioCCC NER Pipeline — lcampillos/roberta-es-clinical-trials-ner

This notebook preserves the original DisTEMIST training design and evaluates the ten-model ensemble on CardioCCC test.
The runtime configuration was chosen using short timing measurements on DisTEMIST training data only; CardioCCC results were not used to choose it.

## Contents

1. [Environment and dependencies](#1-environment-and-dependencies)
2. [Configuration](#2-configuration)
   - [Paths and dataset](#21-paths-and-dataset)
   - [Labels and data loading](#22-labels-and-data-loading)
   - [Segmentation and label alignment](#23-segmentation-and-label-alignment)
   - [Hyperparameters and tokenizer](#24-hyperparameters-and-tokenizer)
3. [Training](#3-training)
   - [Evaluation metrics](#31-evaluation-metrics)
   - [Discriminative fine-tuning](#32-discriminative-fine-tuning)
   - [Multi-seed k-fold loop](#33-multi-seed-k-fold-loop)
   - [Ensemble summary](#34-ensemble-summary)
4. [Inference](#4-inference)
   - [Sentence-based inference function](#41-sentence-based-inference-function)
   - [Ensemble execution](#42-ensemble-execution)
5. [Evaluation](#5-evaluation)
   - [Strict offset-based evaluation](#51-strict-offset-based-evaluation)
   - [Overlap evaluation (IoU)](#52-overlap-evaluation-iou)

## 1. Environment and dependencies

Installation of the required packages and import of libraries.

In [1]:
%pip install -q "evaluate==0.4.6" "spacy==3.8.7" "datasets==3.6.0" "transformers==4.57.6" "accelerate==1.12.0"
%pip install -q --use-pep517 "seqeval==1.2.2"
%pip install -q "https://github.com/explosion/spacy-models/releases/download/es_core_news_md-3.8.0/es_core_news_md-3.8.0-py3-none-any.whl"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.4/33.4 MB 51.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 21.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 99.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.9/380.9 kB 16.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 30.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 kB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.7/146.7 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 78.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 98.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.1/65.1 kB 3.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.48.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
pathos 0.3.5 requires dill>=0.4.1, but you have dill 0.3.8 which is incompatible.
pathos 0.3.5 requires multiprocess>=0.70.19, but you have multiprocess 0.70.16 which is incompatible.
s3fs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2025.3.0 which is incompatible.
tpot 1.1.0 requires dill>=0.3.9, but you have dill 0.3.8 which is incompatible.
gradio 6.26.0 requires huggingface-hub<2.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
diffusers 0.40.0 requires huggingface-hub<2.0,>=1.23.0, but you have huggingface-hub 0.36.2 which is incompatible.
gcsfs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2025.3.0 which is incompatible.
Note: you may need to restart the kernel to use updated packages.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for seqeval (pyproject.toml) ... done
Note: you may need to restart the kernel to use updated packages.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 MB 42.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import gc
import json
import re
import time
from collections import defaultdict
from pathlib import Path

import evaluate
import numpy as np
import pandas as pd
import spacy
import torch
from torch.optim import AdamW
from transformers import (
    AutoConfig,
    AutoModelForTokenClassification,
    AutoTokenizer,
    DataCollatorForTokenClassification,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
    pipeline,
    set_seed,
)

print(f"GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
from transformers import TrainerCallback
import importlib.metadata
import math

if torch.cuda.device_count() != 2:
    raise RuntimeError("Select GPU T4 x2: this execution expects two GPUs.")
print(f"GPU count: {torch.cuda.device_count()} | CPU threads: {torch.get_num_threads()}")

GPU available: True
GPU: Tesla T4
GPU count: 2 | CPU threads: 2

## 2. Configuration

### 2.1. Paths and dataset

Definition of dataset paths and selection of the base model. Training uses the 750 DisTEMIST training documents; external evaluation uses the 250 CardioCCC test documents.

In [3]:
import csv
import hashlib
from zipfile import ZipFile

INPUT_ROOT = Path("/kaggle/input")
DATASET_ROOT = Path("/kaggle/working/cardioccc_dataset")
EXPECTED_FINGERPRINT = "3cef134a65040d6d1b12b3594cd30dab127a24ceda13187159de9429ad947965"
dataset_dirs = set()
for path in INPUT_ROOT.rglob("dataset_manifest.json"):
    try:
        candidate = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError):
        continue
    if candidate.get("dataset_id") == "distemist-cardioccc-external-v1":
        dataset_dirs.add(path.parent.resolve())

if len(dataset_dirs) == 1:
    DATASET_ROOT = dataset_dirs.pop()
elif dataset_dirs:
    raise RuntimeError("Multiple copies of the prepared dataset were found in the inputs.")
else:
    archives = sorted(INPUT_ROOT.rglob("distemist_cardioccc_datos.zip"))
    if len(archives) != 1:
        raise RuntimeError("Attach the distemist-cardioccc-external-evaluation dataset, extracted or as a ZIP archive.")
    with ZipFile(archives[0]) as archive:
        for name in archive.namelist():
            if Path(name).is_absolute() or ".." in Path(name).parts:
                raise ValueError(f"Unsafe archive path: {name}")
        archive.extractall(DATASET_ROOT)

manifest = json.loads((DATASET_ROOT / "dataset_manifest.json").read_text(encoding="utf-8"))
fingerprint = hashlib.sha256(json.dumps(manifest["files"], sort_keys=True, separators=(",", ":")).encode()).hexdigest()
assert fingerprint == manifest["fingerprint"] == EXPECTED_FINGERPRINT
for name, digest in manifest["files"].items():
    assert hashlib.sha256((DATASET_ROOT / name).read_bytes()).hexdigest() == digest, name
print(f"Dataset verified: {DATASET_ROOT}")

train_jsonl = DATASET_ROOT / "distemist/distemist_train.jsonl"
assert hashlib.sha256(train_jsonl.read_bytes()).hexdigest() == "f0200564e73f8665949d09ba32d055c7435dde794f47d950d43141894cf19471"
test_dir = DATASET_ROOT / "cardioccc/test/texts"
texts = {p.stem: p.read_bytes().decode("utf-8") for p in sorted(test_dir.glob("*.txt"))}
assert len(texts) == 250

with (DATASET_ROOT / "cardioccc/test/gold.tsv").open(encoding="utf-8", newline="") as stream:
    gold = list(csv.DictReader(stream, delimiter="\t"))
assert len(gold) == 7884 and {row["filename"] for row in gold} == set(texts)
for row in gold:
    start, end = int(row["start_span"]), int(row["end_span"])
    assert row["label"] == "ENFERMEDAD" and 0 <= start < end <= len(texts[row["filename"]])
    assert texts[row["filename"]][start:end] == row["text"]

gs_path = Path("/kaggle/working/cardioccc_test_mentions.tsv")
with gs_path.open("w", encoding="utf-8", newline="") as stream:
    writer = csv.writer(stream, delimiter="\t")
    writer.writerow(["filename", "label", "off0", "off1", "span"])
    writer.writerows((row["filename"], row["label"], row["start_span"], row["end_span"], row["text"]) for row in gold)

DATA_PATHS = {
    "train_jsonl": str(train_jsonl),
    "text_files_test_dir": str(test_dir),
    "gs_mentions_tsv": str(gs_path),
}
BASE_MODEL = "lcampillos/roberta-es-clinical-trials-ner"

print("Configured paths:")
for k, v in DATA_PATHS.items():
    print(f"  - {k}: {v}")
print(f"Base model: {BASE_MODEL}")
BASE_MODEL_REVISION = 'cfdd0455be8bd539a27883026b24aa745c871493'

Dataset verified: /kaggle/input/distemist-cardioccc-external-evaluation
Configured paths:
  - train_jsonl: /kaggle/input/distemist-cardioccc-external-evaluation/distemist/distemist_train.jsonl
  - text_files_test_dir: /kaggle/input/distemist-cardioccc-external-evaluation/cardioccc/test/texts
  - gs_mentions_tsv: /kaggle/working/cardioccc_test_mentions.tsv
Base model: lcampillos/roberta-es-clinical-trials-ner

### 2.2. Labels and data loading

BIO label mapping and loading of the training JSONL file.

In [4]:
id2label = {0: "B-ENFERMEDAD", 1: "I-ENFERMEDAD", 2: "O"}
label2id = {"B-ENFERMEDAD": 0, "I-ENFERMEDAD": 1, "O": 2}
label_list = [id2label[i] for i in range(len(id2label))]

nlp_spacy = spacy.load("es_core_news_md")

from datasets import load_dataset as _load_dataset
train_full = _load_dataset("json", data_files=DATA_PATHS["train_jsonl"], split="train")

print(f"Labels: {label2id}")
print(f"Training documents: {len(train_full)}")

Generating train split: 0 examples [00:00, ? examples/s]

Labels: {'B-ENFERMEDAD': 0, 'I-ENFERMEDAD': 1, 'O': 2}
Training documents: 750

### 2.3. Segmentation and label alignment

Sentence segmentation functions using spaCy and BIO label alignment during tokenization.

In [5]:
def split_by_sentences(text, tokens, labels, nlp_spacy):
    """Split document tokens and labels into sentences using spaCy."""
    doc = nlp_spacy(text)
    sentences = list(doc.sents)

    if len(sentences) <= 1:
        return [(tokens, labels)]

    token_char_starts = []
    search_pos = 0
    for tok in tokens:
        idx = text.find(tok, search_pos)
        if idx == -1:
            return [(tokens, labels)]
        token_char_starts.append(idx)
        search_pos = idx + len(tok)

    results = []
    for sent in sentences:
        sent_start = sent.start_char
        sent_end = sent.end_char
        sent_token_indices = [
            i for i, cs in enumerate(token_char_starts)
            if sent_start <= cs < sent_end
        ]
        if not sent_token_indices:
            continue
        sent_tokens = [tokens[i] for i in sent_token_indices]
        sent_labels = [labels[i] for i in sent_token_indices]
        results.append((sent_tokens, sent_labels))

    return results if results else [(tokens, labels)]


def tokenize_and_align_labels(examples, tok, nlp_spacy, max_length=512):
    """Tokenize sentences with truncation=True and propagate B->I to subtokens."""
    all_input_ids = []
    all_attention_masks = []
    all_labels = []

    for doc_idx in range(len(examples["tokens"])):
        text = examples["text"][doc_idx]
        tokens = examples["tokens"][doc_idx]
        ner_tags = examples["ner_tags"][doc_idx]

        sent_chunks = split_by_sentences(text, tokens, ner_tags, nlp_spacy)

        for sent_tokens, sent_labels in sent_chunks:
            tokenized = tok(
                [sent_tokens],
                is_split_into_words=True,
                truncation=True,
                max_length=max_length,
                padding=False,
            )

            word_ids = tokenized.word_ids(batch_index=0)
            previous_word_idx = None
            label_ids = []

            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)
                elif word_idx != previous_word_idx:
                    label_ids.append(sent_labels[word_idx])
                else:
                    prev_label = sent_labels[word_idx]
                    label_ids.append(1 if prev_label == 0 else prev_label)
                previous_word_idx = word_idx

            all_input_ids.append(tokenized["input_ids"][0])
            all_attention_masks.append(tokenized["attention_mask"][0])
            all_labels.append(label_ids)

    return {
        "input_ids": all_input_ids,
        "attention_mask": all_attention_masks,
        "labels": all_labels,
    }

### 2.4. Hyperparameters and tokenizer

Experiment configuration: training hyperparameters and tokenizer loading.

In [6]:
BASE_MODEL_TAG = BASE_MODEL.split("/")[-1]
USE_BF16 = True
USE_FP16 = False
CHECKPOINT_REENTRANT = False
CPU_THREADS = 2
torch.set_num_threads(CPU_THREADS)

MAX_EPOCHS          = 20
BATCH_SIZE          = 16
LEARNING_RATE       = 8.516e-5
LR_LAYER_DECAY      = 0.95
LR_ENCODER_GROUPS   = 3
DROPOUT             = 0.1
WEIGHT_DECAY        = 0.1844
WARMUP_RATIO        = 0.1
EARLY_STOPPING_PATIENCE   = 5
EARLY_STOPPING_THRESHOLD  = 1e-4

K_FOLDS             = 5
CV_SPLIT_SEED       = 42
SEEDS               = [123, 4242]
ENSEMBLE_VOTING_RATIO = 0.5

RESULTS_DIR        = f"results_{BASE_MODEL_TAG}_kfold_multiseed"
MODEL_OUTPUT_PREFIX = f"{BASE_MODEL_TAG}-distemist-ner"
Path(RESULTS_DIR).mkdir(parents=True, exist_ok=True)

config = AutoConfig.from_pretrained(
    BASE_MODEL, revision=BASE_MODEL_REVISION,
    num_labels=len(label2id),
    label2id=label2id,
    id2label=id2label,
    hidden_dropout_prob=DROPOUT,
    attention_probs_dropout_prob=DROPOUT,
    classifier_dropout=DROPOUT,
    attn_implementation="sdpa",
)

tokenizer = AutoTokenizer.from_pretrained(
    BASE_MODEL, revision=BASE_MODEL_REVISION,
    add_prefix_space=True,
    do_lower_case=False,
    keep_accents=True,
    model_max_length=config.max_position_embeddings,
)

hyperparams = {
    "base_model": BASE_MODEL, "base_model_tag": BASE_MODEL_TAG,
    "max_epochs": MAX_EPOCHS, "batch_size": BATCH_SIZE,
    "learning_rate": LEARNING_RATE, "lr_layer_decay": LR_LAYER_DECAY,
    "lr_encoder_groups": LR_ENCODER_GROUPS, "dropout": DROPOUT,
    "weight_decay": WEIGHT_DECAY, "warmup_ratio": WARMUP_RATIO,
    "early_stopping_patience": EARLY_STOPPING_PATIENCE,
    "early_stopping_threshold": EARLY_STOPPING_THRESHOLD,
    "k_folds": K_FOLDS, "cv_split_seed": CV_SPLIT_SEED,
    "seeds": SEEDS, "ensemble_voting_ratio": ENSEMBLE_VOTING_RATIO,
}
with open(f"{RESULTS_DIR}/hyperparameters.json", "w", encoding="utf-8") as f:
    json.dump(hyperparams, f, ensure_ascii=False, indent=2)

print(f"Model: {BASE_MODEL} | Max pos embeddings: {config.max_position_embeddings}")
print(f"Results directory: {RESULTS_DIR}")
runtime_settings = {
    "model_revision": BASE_MODEL_REVISION,
    "bf16": USE_BF16, "fp16": USE_FP16,
    "gradient_checkpointing_use_reentrant": CHECKPOINT_REENTRANT,
    "cpu_threads": CPU_THREADS, "gpu_count": torch.cuda.device_count(),
    "gpu_names": [torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())],
    "software": {p: importlib.metadata.version(p) for p in
                 ["torch", "transformers", "accelerate", "datasets", "spacy", "seqeval"]},
    "cuda": torch.version.cuda,
    "training_corpus": "DisTEMIST train (750 documents)",
    "external_test": "CardioCCC test (250 documents)",
    "runtime_selection": "Throughput and finite loss on DisTEMIST train only",
}
runtime_settings["speed_benchmark"] = {'steps_per_second': 2.0366128105347236, 'observed_query_dtypes': {'cuda:1': {'dtype': 'torch.float32', 'autocast': False}, 'cuda:0': {'dtype': 'torch.float32', 'autocast': False}}, 'measured_on': 'DisTEMIST training fold 1; 56 timed optimizer steps'}
with open(f"{RESULTS_DIR}/runtime_settings.json", "w", encoding="utf-8") as stream:
    json.dump(runtime_settings, stream, indent=2)
print("RUNTIME " + json.dumps(runtime_settings), flush=True)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

Model: lcampillos/roberta-es-clinical-trials-ner | Max pos embeddings: 514
Results directory: results_roberta-es-clinical-trials-ner_kfold_multiseed
RUNTIME {"model_revision": "cfdd0455be8bd539a27883026b24aa745c871493", "bf16": true, "fp16": false, "gradient_checkpointing_use_reentrant": false, "cpu_threads": 2, "gpu_count": 2, "gpu_names": ["Tesla T4", "Tesla T4"], "software": {"torch": "2.11.0+cu128", "transformers": "4.57.6", "accelerate": "1.12.0", "datasets": "3.6.0", "spacy": "3.8.7", "seqeval": "1.2.2"}, "cuda": "12.8", "training_corpus": "DisTEMIST train (750 documents)", "external_test": "CardioCCC test (250 documents)", "runtime_selection": "Throughput and finite loss on DisTEMIST train only", "speed_benchmark": {"steps_per_second": 2.0366128105347236, "observed_query_dtypes": {"cuda:1": {"dtype": "torch.float32", "autocast": false}, "cuda:0": {"dtype": "torch.float32", "autocast": false}}, "measured_on": "DisTEMIST training fold 1; 56 timed optimizer steps"}}

## 3. Training

### 3.1. Evaluation metrics

Definition of the seqeval metrics for NER evaluation during training.

In [7]:
metric_fn = evaluate.load("seqeval", trust_remote_code=True)


def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = [
        [label_list[pred] for (pred, la) in zip(prediction, label) if la != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [label_list[la] for (_, la) in zip(prediction, label) if la != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = metric_fn.compute(
        predictions=true_predictions,
        references=true_labels,
        zero_division=0.0,
    )
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

Downloading builder script: 0.00B [00:00, ?B/s]

### 3.2. Discriminative fine-tuning

Assignment of different learning rates according to layer depth.

In [8]:
def create_discriminative_optimizer(model):
    named_params = [(n, p) for n, p in model.named_parameters() if p.requires_grad]
    layer_re = re.compile(r"\.(?:encoder\.layer|layer|layers|block|h)\.(\d+)\.")
    layer_ids = [int(m.group(1)) for n, _ in named_params for m in [layer_re.search(n.lower())] if m]
    max_layer_id = max(layer_ids) if layer_ids else 0

    groups = {}
    for name, param in named_params:
        lname = name.lower()
        if "classifier" in lname or "crf" in lname:
            bucket, lr = "head", LEARNING_RATE
        elif "embed" in lname:
            bucket, lr = "embeddings", LEARNING_RATE * (LR_LAYER_DECAY ** (LR_ENCODER_GROUPS + 1))
        else:
            match = layer_re.search(lname)
            if match and max_layer_id > 0:
                zone = min(int((int(match.group(1)) / max_layer_id) * LR_ENCODER_GROUPS), LR_ENCODER_GROUPS - 1)
                bucket, lr = f"encoder_{zone}", LEARNING_RATE * (LR_LAYER_DECAY ** (LR_ENCODER_GROUPS - zone))
            else:
                bucket, lr = "head", LEARNING_RATE

        if bucket not in groups:
            groups[bucket] = {"params": [], "lr": float(lr), "param_count": 0, "tensor_count": 0}
        groups[bucket]["params"].append(param)
        groups[bucket]["param_count"] += param.numel()
        groups[bucket]["tensor_count"] += 1

    optimizer = AdamW(
        [{"params": g["params"], "lr": g["lr"], "weight_decay": WEIGHT_DECAY} for g in groups.values()],
        lr=LEARNING_RATE,
        fused=torch.cuda.is_available(),
    )
    order = ["embeddings"] + [f"encoder_{i}" for i in range(LR_ENCODER_GROUPS)] + ["head"]
    summary = [
        {"bucket": b, "lr": groups[b]["lr"], "param_count": groups[b]["param_count"], "tensor_count": groups[b]["tensor_count"]}
        for b in order if b in groups
    ]
    return optimizer, summary

### 3.3. Multi-seed k-fold loop

Training across document folds and seeds with early stopping on internal validation. The resulting models form the ensemble. CardioCCC is reserved for external evaluation.

In [9]:
class TrainingProgress(TrainerCallback):
    def __init__(self, fold, seed):
        self.fold = fold
        self.seed = seed
        self.started = None

    def on_train_begin(self, args, state, control, **kwargs):
        self.started = time.perf_counter()
        print(f"TRAIN_START fold={self.fold} seed={self.seed} GPUs={args.n_gpu} effective_batch={args.train_batch_size}", flush=True)

    def on_log(self, args, state, control, logs=None, **kwargs):
        elapsed = time.perf_counter() - self.started
        for key in ["loss", "eval_loss"]:
            if key in (logs or {}) and not math.isfinite(logs[key]):
                raise FloatingPointError(f"Non-finite {key}: {logs[key]}")
        report = {"fold": self.fold, "seed": self.seed,
                  "epoch": round(state.epoch or 0, 3), "step": state.global_step,
                  "elapsed_minutes": round(elapsed / 60, 2),
                  "average_steps_per_second": round(state.global_step / elapsed, 3),
                  **(logs or {})}
        print("TRAIN_PROGRESS " + json.dumps(report), flush=True)

    def on_epoch_end(self, args, state, control, **kwargs):
        self.epoch_train_end = time.perf_counter()
        print(f"EPOCH_TRAIN_END fold={self.fold} seed={self.seed} epoch={state.epoch:.2f}", flush=True)

    def on_evaluate(self, args, state, control, metrics=None, **kwargs):
        self.evaluation_end = time.perf_counter()
        seconds = self.evaluation_end - self.epoch_train_end
        print(f"VALIDATION_TIME fold={self.fold} seed={self.seed} seconds={seconds:.2f}", flush=True)

    def on_save(self, args, state, control, **kwargs):
        seconds = time.perf_counter() - self.evaluation_end
        print(f"CHECKPOINT_TIME fold={self.fold} seed={self.seed} seconds={seconds:.2f}", flush=True)


def make_kfold_indices(n_samples, k_folds, split_seed):
    rng = np.random.default_rng(split_seed)
    indices = np.arange(n_samples)
    rng.shuffle(indices)
    fold_sizes = np.full(k_folds, n_samples // k_folds, dtype=int)
    fold_sizes[: n_samples % k_folds] += 1
    folds, current = [], 0
    for size in fold_sizes:
        val_idx = indices[current: current + size]
        train_idx = np.concatenate((indices[:current], indices[current + size:]))
        folds.append((train_idx, val_idx))
        current += size
    return folds


fold_seed_results = []
ensemble_models = []
folds = make_kfold_indices(len(train_full), K_FOLDS, CV_SPLIT_SEED)

print(f"Multi-seed k-fold training | docs={len(train_full)} | folds={K_FOLDS} | seeds={SEEDS}")

for fold_idx, (train_idx, val_idx) in enumerate(folds, start=1):
    train_raw = train_full.select(train_idx.tolist())
    val_raw   = train_full.select(val_idx.tolist())

    map_kwargs = dict(batched=True, remove_columns=train_full.column_names)
    fn = lambda x: tokenize_and_align_labels(x, tokenizer, nlp_spacy, max_length=512)
    train_ds = train_raw.map(fn, **map_kwargs)
    val_ds   = val_raw.map(fn, **map_kwargs)

    print(f"\nFold {fold_idx}/{K_FOLDS} | train={len(train_raw)} docs / {len(train_ds)} seqs | val={len(val_raw)} docs / {len(val_ds)} seqs")

    for seed in SEEDS:
        print(f"  Seed {seed}...")
        set_seed(seed)
        start_time = time.time()

        model = AutoModelForTokenClassification.from_pretrained(BASE_MODEL, revision=BASE_MODEL_REVISION, config=config,ignore_mismatched_sizes=True)
        model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": CHECKPOINT_REENTRANT})
        optimizer, lr_summary = create_discriminative_optimizer(model)

        output_dir = f"{RESULTS_DIR}/{MODEL_OUTPUT_PREFIX}-fold{fold_idx}-seed{seed}"
        training_args = TrainingArguments(
            output_dir=output_dir,
            eval_strategy="epoch",
            logging_strategy="steps",
            logging_steps=100,
            logging_nan_inf_filter=False,
            save_strategy="epoch",
            num_train_epochs=MAX_EPOCHS,
            load_best_model_at_end=True,
            metric_for_best_model="eval_f1",
            greater_is_better=True,
            save_total_limit=1,
            learning_rate=LEARNING_RATE,
            warmup_ratio=WARMUP_RATIO,
            weight_decay=WEIGHT_DECAY,
            per_device_train_batch_size=BATCH_SIZE,
            dataloader_num_workers=2,
            dataloader_prefetch_factor=4,
            dataloader_persistent_workers=True,
            seed=seed,
            bf16=USE_BF16,
            fp16=USE_FP16,
            save_only_model=True,
            report_to="none",
        )

        trainer = Trainer(
            model, training_args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            processing_class=tokenizer,
            compute_metrics=compute_metrics,
            data_collator=DataCollatorForTokenClassification(tokenizer),
            callbacks=[TrainingProgress(fold_idx, seed), EarlyStoppingCallback(
                early_stopping_patience=EARLY_STOPPING_PATIENCE,
                early_stopping_threshold=EARLY_STOPPING_THRESHOLD,
            )],
            optimizers=(optimizer, None),
        )
        trainer.train()

        model_dir = trainer.state.best_model_checkpoint or output_dir
        val_metrics = trainer.evaluate(val_ds)
        best_logs = [l for l in trainer.state.log_history if "eval_f1" in l]
        best_f1   = max((l["eval_f1"] for l in best_logs), default=float("nan"))
        elapsed   = (time.time() - start_time) / 60

        row = {
            "fold": fold_idx, "seed": seed,
            "train_docs": len(train_raw), "val_docs": len(val_raw),
            "train_sequences": len(train_ds), "val_sequences": len(val_ds),
            "best_eval_f1": best_f1,
            "eval_precision": val_metrics.get("eval_precision", float("nan")),
            "eval_recall":    val_metrics.get("eval_recall",    float("nan")),
            "eval_f1":        val_metrics.get("eval_f1",        float("nan")),
            "eval_accuracy":  val_metrics.get("eval_accuracy",  float("nan")),
            "eval_loss":      val_metrics.get("eval_loss",      float("nan")),
            "elapsed_min": elapsed, "model_dir": model_dir,
        }
        fold_seed_results.append(row)
        ensemble_models.append({"fold": fold_idx, "seed": seed, "model_dir": model_dir, "eval_f1": row["eval_f1"]})

        print(f"    fold={fold_idx} seed={seed} | best_f1={best_f1:.4f} | eval_f1={row['eval_f1']:.4f} | {elapsed:.1f} min")

        del trainer, model, optimizer
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

if not fold_seed_results:
    raise RuntimeError("No fold-seed model was trained.")

df_ensemble_results = (
    pd.DataFrame(fold_seed_results)
    .sort_values(["eval_f1", "fold", "seed"], ascending=[False, True, True])
    .reset_index(drop=True)
)
df_ensemble_results.to_csv(f"{RESULTS_DIR}/ensemble_fold_seed_summary.csv", index=False)
with open(f"{RESULTS_DIR}/ensemble_fold_seed_summary.json", "w", encoding="utf-8") as f:
    json.dump(fold_seed_results, f, ensure_ascii=False, indent=2)

print(f"\nEnsemble models: {len(ensemble_models)}")
print(df_ensemble_results[["fold","seed","eval_f1","best_eval_f1","elapsed_min"]].to_string(index=False))

Multi-seed k-fold training | docs=750 | folds=5 | seeds=[123, 4242]

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Fold 1/5 | train=600 docs / 9485 seqs | val=150 docs / 2228 seqs
  Seed 123...

model.safetensors:   0%|          | 0.00/496M [00:00<?, ?B/s]

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

TRAIN_START fold=1 seed=123 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 0.3367003367003367, "step": 100, "elapsed_minutes": 0.75, "average_steps_per_second": 2.231, "loss": 0.4542, "grad_norm": 1.159822702407837, "learning_rate": 1.1560558708333332e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 0.6734006734006734, "step": 200, "elapsed_minutes": 1.47, "average_steps_per_second": 2.269, "loss": 0.1183, "grad_norm": 3.3330628871917725, "learning_rate": 2.323789073695286e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=1.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 1.0, "step": 297, "elapsed_minutes": 2.42, "average_steps_per_second": 2.046, "eval_loss": 0.09169122576713562, "eval_precision": 0.655591054313099, "eval_recall": 0.6904441453566622, "eval_f1": 0.672566371681416, "eval_accuracy": 0.9689403701968134, "eval_runtime": 13.1068, "eval_samples_per_second": 169.988, "eval_steps_per_second": 10.681}
VALIDATION_TIME fold=1 seed=123 seconds=13.11
CHECKPOINT_TIME fold=1 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 1.0101010101010102, "step": 300, "elapsed_minutes": 2.45, "average_steps_per_second": 2.042, "loss": 0.1038, "grad_norm": 0.6753032207489014, "learning_rate": 3.491522276557239e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 1.3468013468013469, "step": 400, "elapsed_minutes": 3.23, "average_steps_per_second": 2.066, "loss": 0.0759, "grad_norm": 1.2546669244766235, "learning_rate": 4.6592554794191914e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 1.6835016835016834, "step": 500, "elapsed_minutes": 3.99, "average_steps_per_second": 2.088, "loss": 0.0807, "grad_norm": 1.2877620458602905, "learning_rate": 5.826988682281144e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=2.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 2.0, "step": 594, "elapsed_minutes": 4.92, "average_steps_per_second": 2.012, "eval_loss": 0.08790699392557144, "eval_precision": 0.6730061349693252, "eval_recall": 0.7382234185733513, "eval_f1": 0.7041078305519897, "eval_accuracy": 0.9703901124648547, "eval_runtime": 12.213, "eval_samples_per_second": 182.429, "eval_steps_per_second": 11.463}
VALIDATION_TIME fold=1 seed=123 seconds=12.21
CHECKPOINT_TIME fold=1 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 2.0202020202020203, "step": 600, "elapsed_minutes": 4.99, "average_steps_per_second": 2.004, "loss": 0.0769, "grad_norm": 1.537680745124817, "learning_rate": 6.929847818317433e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 2.356902356902357, "step": 700, "elapsed_minutes": 5.74, "average_steps_per_second": 2.032, "loss": 0.0487, "grad_norm": 0.4892892837524414, "learning_rate": 6.800099684666106e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 2.6936026936026938, "step": 800, "elapsed_minutes": 6.51, "average_steps_per_second": 2.049, "loss": 0.0532, "grad_norm": 0.7905460000038147, "learning_rate": 6.670351551014777e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=3.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 3.0, "step": 891, "elapsed_minutes": 7.39, "average_steps_per_second": 2.009, "eval_loss": 0.0884256511926651, "eval_precision": 0.7103403982016698, "eval_recall": 0.7442799461641992, "eval_f1": 0.7269142293789025, "eval_accuracy": 0.9712394564198688, "eval_runtime": 12.374, "eval_samples_per_second": 180.055, "eval_steps_per_second": 11.314}
VALIDATION_TIME fold=1 seed=123 seconds=12.38
CHECKPOINT_TIME fold=1 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 3.0303030303030303, "step": 900, "elapsed_minutes": 7.47, "average_steps_per_second": 2.009, "loss": 0.0475, "grad_norm": 0.6661027073860168, "learning_rate": 6.54060341736345e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 3.3670033670033668, "step": 1000, "elapsed_minutes": 8.22, "average_steps_per_second": 2.028, "loss": 0.0287, "grad_norm": 1.1566287279129028, "learning_rate": 6.41085528371212e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 3.7037037037037037, "step": 1100, "elapsed_minutes": 8.99, "average_steps_per_second": 2.04, "loss": 0.0273, "grad_norm": 0.6742251515388489, "learning_rate": 6.281107150060793e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=4.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 4.0, "step": 1188, "elapsed_minutes": 9.87, "average_steps_per_second": 2.005, "eval_loss": 0.11977476626634598, "eval_precision": 0.669735327963176, "eval_recall": 0.7833109017496636, "eval_f1": 0.7220843672456577, "eval_accuracy": 0.9681788894095595, "eval_runtime": 12.1986, "eval_samples_per_second": 182.644, "eval_steps_per_second": 11.477}
VALIDATION_TIME fold=1 seed=123 seconds=12.20
CHECKPOINT_TIME fold=1 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 4.040404040404041, "step": 1200, "elapsed_minutes": 9.96, "average_steps_per_second": 2.007, "loss": 0.0302, "grad_norm": 1.6429637670516968, "learning_rate": 6.151359016409464e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 4.377104377104377, "step": 1300, "elapsed_minutes": 10.74, "average_steps_per_second": 2.017, "loss": 0.015, "grad_norm": 0.1777554452419281, "learning_rate": 6.021610882758137e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 4.713804713804714, "step": 1400, "elapsed_minutes": 11.49, "average_steps_per_second": 2.031, "loss": 0.0171, "grad_norm": 0.06449645757675171, "learning_rate": 5.891862749106808e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=5.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 5.0, "step": 1485, "elapsed_minutes": 12.35, "average_steps_per_second": 2.004, "eval_loss": 0.11969329416751862, "eval_precision": 0.7214241099312929, "eval_recall": 0.7772543741588156, "eval_f1": 0.7482993197278911, "eval_accuracy": 0.9727038425492034, "eval_runtime": 12.2738, "eval_samples_per_second": 181.525, "eval_steps_per_second": 11.406}
VALIDATION_TIME fold=1 seed=123 seconds=12.28
CHECKPOINT_TIME fold=1 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 5.05050505050505, "step": 1500, "elapsed_minutes": 12.48, "average_steps_per_second": 2.003, "loss": 0.0186, "grad_norm": 0.3649302124977112, "learning_rate": 5.7621146154554804e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 5.3872053872053876, "step": 1600, "elapsed_minutes": 13.23, "average_steps_per_second": 2.015, "loss": 0.0105, "grad_norm": 0.591622531414032, "learning_rate": 5.632366481804152e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 5.723905723905724, "step": 1700, "elapsed_minutes": 13.98, "average_steps_per_second": 2.027, "loss": 0.0134, "grad_norm": 0.1894543617963791, "learning_rate": 5.502618348152824e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=6.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 6.0, "step": 1782, "elapsed_minutes": 14.82, "average_steps_per_second": 2.004, "eval_loss": 0.1465945690870285, "eval_precision": 0.7158160050409578, "eval_recall": 0.7644683714670256, "eval_f1": 0.7393426618939147, "eval_accuracy": 0.9713566073102156, "eval_runtime": 12.2347, "eval_samples_per_second": 182.105, "eval_steps_per_second": 11.443}
VALIDATION_TIME fold=1 seed=123 seconds=12.24
CHECKPOINT_TIME fold=1 seed=123 seconds=0.65
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 6.0606060606060606, "step": 1800, "elapsed_minutes": 14.95, "average_steps_per_second": 2.006, "loss": 0.0112, "grad_norm": 0.16809673607349396, "learning_rate": 5.372870214501496e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 6.397306397306397, "step": 1900, "elapsed_minutes": 15.72, "average_steps_per_second": 2.014, "loss": 0.0091, "grad_norm": 0.10918810963630676, "learning_rate": 5.243122080850168e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 6.7340067340067336, "step": 2000, "elapsed_minutes": 16.48, "average_steps_per_second": 2.023, "loss": 0.008, "grad_norm": 0.23928223550319672, "learning_rate": 5.11337394719884e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=7.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 7.0, "step": 2079, "elapsed_minutes": 17.29, "average_steps_per_second": 2.004, "eval_loss": 0.139125257730484, "eval_precision": 0.7223264540337712, "eval_recall": 0.7772543741588156, "eval_f1": 0.7487844408427877, "eval_accuracy": 0.9714884020618557, "eval_runtime": 12.2247, "eval_samples_per_second": 182.254, "eval_steps_per_second": 11.452}
VALIDATION_TIME fold=1 seed=123 seconds=12.23
CHECKPOINT_TIME fold=1 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 7.070707070707071, "step": 2100, "elapsed_minutes": 17.45, "average_steps_per_second": 2.006, "loss": 0.0078, "grad_norm": 0.16269050538539886, "learning_rate": 4.983625813547512e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 7.407407407407407, "step": 2200, "elapsed_minutes": 18.28, "average_steps_per_second": 2.006, "loss": 0.0047, "grad_norm": 0.22847862541675568, "learning_rate": 4.853877679896183e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 7.744107744107744, "step": 2300, "elapsed_minutes": 19.01, "average_steps_per_second": 2.016, "loss": 0.0052, "grad_norm": 0.16715432703495026, "learning_rate": 4.724129546244855e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=8.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 8.0, "step": 2376, "elapsed_minutes": 19.75, "average_steps_per_second": 2.005, "eval_loss": 0.15862764418125153, "eval_precision": 0.7370417193426043, "eval_recall": 0.784656796769852, "eval_f1": 0.760104302477184, "eval_accuracy": 0.9721766635426429, "eval_runtime": 12.243, "eval_samples_per_second": 181.981, "eval_steps_per_second": 11.435}
VALIDATION_TIME fold=1 seed=123 seconds=12.24
CHECKPOINT_TIME fold=1 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 8.080808080808081, "step": 2400, "elapsed_minutes": 19.95, "average_steps_per_second": 2.005, "loss": 0.0051, "grad_norm": 0.7956090569496155, "learning_rate": 4.594381412593528e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 8.417508417508417, "step": 2500, "elapsed_minutes": 20.71, "average_steps_per_second": 2.012, "loss": 0.0052, "grad_norm": 0.08606910705566406, "learning_rate": 4.4646332789421995e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 8.754208754208754, "step": 2600, "elapsed_minutes": 21.48, "average_steps_per_second": 2.018, "loss": 0.0066, "grad_norm": 0.8382042646408081, "learning_rate": 4.3348851452908714e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=9.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 9.0, "step": 2673, "elapsed_minutes": 22.23, "average_steps_per_second": 2.004, "eval_loss": 0.17622961103916168, "eval_precision": 0.723885155772755, "eval_recall": 0.797442799461642, "eval_f1": 0.7588856868395774, "eval_accuracy": 0.9723670337394564, "eval_runtime": 12.2604, "eval_samples_per_second": 181.723, "eval_steps_per_second": 11.419}
VALIDATION_TIME fold=1 seed=123 seconds=12.26
CHECKPOINT_TIME fold=1 seed=123 seconds=0.65
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 9.090909090909092, "step": 2700, "elapsed_minutes": 22.43, "average_steps_per_second": 2.006, "loss": 0.0038, "grad_norm": 1.5726114511489868, "learning_rate": 4.205137011639543e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 9.427609427609427, "step": 2800, "elapsed_minutes": 23.22, "average_steps_per_second": 2.01, "loss": 0.0029, "grad_norm": 0.09770471602678299, "learning_rate": 4.075388877988216e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 9.764309764309765, "step": 2900, "elapsed_minutes": 23.99, "average_steps_per_second": 2.015, "loss": 0.0025, "grad_norm": 0.12704609334468842, "learning_rate": 3.9456407443368876e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=10.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 10.0, "step": 2970, "elapsed_minutes": 24.7, "average_steps_per_second": 2.004, "eval_loss": 0.1413978785276413, "eval_precision": 0.734225621414914, "eval_recall": 0.775235531628533, "eval_f1": 0.7541734860883798, "eval_accuracy": 0.9731138706654171, "eval_runtime": 12.2357, "eval_samples_per_second": 182.09, "eval_steps_per_second": 11.442}
VALIDATION_TIME fold=1 seed=123 seconds=12.24
CHECKPOINT_TIME fold=1 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 10.1010101010101, "step": 3000, "elapsed_minutes": 24.94, "average_steps_per_second": 2.005, "loss": 0.0041, "grad_norm": 0.41347071528434753, "learning_rate": 3.815892610685559e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 10.437710437710438, "step": 3100, "elapsed_minutes": 25.72, "average_steps_per_second": 2.009, "loss": 0.0034, "grad_norm": 0.34523287415504456, "learning_rate": 3.6861444770342306e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 10.774410774410775, "step": 3200, "elapsed_minutes": 26.46, "average_steps_per_second": 2.016, "loss": 0.0023, "grad_norm": 0.2296421080827713, "learning_rate": 3.556396343382903e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=11.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 11.0, "step": 3267, "elapsed_minutes": 27.16, "average_steps_per_second": 2.005, "eval_loss": 0.17567238211631775, "eval_precision": 0.730246913580247, "eval_recall": 0.7960969044414535, "eval_f1": 0.7617514488087573, "eval_accuracy": 0.9726599109653233, "eval_runtime": 12.1795, "eval_samples_per_second": 182.93, "eval_steps_per_second": 11.495}
VALIDATION_TIME fold=1 seed=123 seconds=12.18
CHECKPOINT_TIME fold=1 seed=123 seconds=0.72
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 11.11111111111111, "step": 3300, "elapsed_minutes": 27.42, "average_steps_per_second": 2.006, "loss": 0.0019, "grad_norm": 0.0022500697523355484, "learning_rate": 3.426648209731575e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 11.447811447811448, "step": 3400, "elapsed_minutes": 28.19, "average_steps_per_second": 2.01, "loss": 0.002, "grad_norm": 0.3209451138973236, "learning_rate": 3.296900076080247e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 11.784511784511784, "step": 3500, "elapsed_minutes": 28.96, "average_steps_per_second": 2.014, "loss": 0.0016, "grad_norm": 0.025516677647829056, "learning_rate": 3.1671519424289186e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=12.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 12.0, "step": 3564, "elapsed_minutes": 29.63, "average_steps_per_second": 2.005, "eval_loss": 0.17390115559101105, "eval_precision": 0.7607843137254902, "eval_recall": 0.7833109017496636, "eval_f1": 0.7718832891246683, "eval_accuracy": 0.9732456654170571, "eval_runtime": 12.2598, "eval_samples_per_second": 181.732, "eval_steps_per_second": 11.419}
VALIDATION_TIME fold=1 seed=123 seconds=12.26
CHECKPOINT_TIME fold=1 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 12.121212121212121, "step": 3600, "elapsed_minutes": 29.92, "average_steps_per_second": 2.006, "loss": 0.0024, "grad_norm": 0.036399081349372864, "learning_rate": 3.0374038087775905e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 12.457912457912458, "step": 3700, "elapsed_minutes": 30.68, "average_steps_per_second": 2.01, "loss": 0.0019, "grad_norm": 0.11641119420528412, "learning_rate": 2.9076556751262623e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 12.794612794612794, "step": 3800, "elapsed_minutes": 31.41, "average_steps_per_second": 2.016, "loss": 0.0013, "grad_norm": 0.003646168392151594, "learning_rate": 2.7779075414749345e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=13.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 13.0, "step": 3861, "elapsed_minutes": 32.11, "average_steps_per_second": 2.004, "eval_loss": 0.15453076362609863, "eval_precision": 0.7409293443666455, "eval_recall": 0.7833109017496636, "eval_f1": 0.7615309126594701, "eval_accuracy": 0.9732749531396439, "eval_runtime": 12.2155, "eval_samples_per_second": 182.392, "eval_steps_per_second": 11.461}
VALIDATION_TIME fold=1 seed=123 seconds=12.22
CHECKPOINT_TIME fold=1 seed=123 seconds=0.65
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 13.131313131313131, "step": 3900, "elapsed_minutes": 32.4, "average_steps_per_second": 2.006, "loss": 0.0017, "grad_norm": 0.032275885343551636, "learning_rate": 2.648159407823606e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 13.468013468013467, "step": 4000, "elapsed_minutes": 33.16, "average_steps_per_second": 2.01, "loss": 0.0006, "grad_norm": 0.02850709855556488, "learning_rate": 2.5184112741722782e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 13.804713804713804, "step": 4100, "elapsed_minutes": 33.93, "average_steps_per_second": 2.014, "loss": 0.0019, "grad_norm": 0.004287922754883766, "learning_rate": 2.38866314052095e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=14.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 14.0, "step": 4158, "elapsed_minutes": 34.57, "average_steps_per_second": 2.005, "eval_loss": 0.18726854026317596, "eval_precision": 0.7488554610856769, "eval_recall": 0.7705248990578735, "eval_f1": 0.7595356550580431, "eval_accuracy": 0.9732163776944704, "eval_runtime": 12.2317, "eval_samples_per_second": 182.15, "eval_steps_per_second": 11.446}
VALIDATION_TIME fold=1 seed=123 seconds=12.23
CHECKPOINT_TIME fold=1 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 14.141414141414142, "step": 4200, "elapsed_minutes": 34.91, "average_steps_per_second": 2.005, "loss": 0.0011, "grad_norm": 0.07646474987268448, "learning_rate": 2.2589150068696222e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 14.478114478114477, "step": 4300, "elapsed_minutes": 35.64, "average_steps_per_second": 2.011, "loss": 0.0011, "grad_norm": 0.7315482497215271, "learning_rate": 2.1291668732182937e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 14.814814814814815, "step": 4400, "elapsed_minutes": 36.43, "average_steps_per_second": 2.013, "loss": 0.0008, "grad_norm": 1.0844870805740356, "learning_rate": 1.999418739566966e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=15.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 15.0, "step": 4455, "elapsed_minutes": 37.05, "average_steps_per_second": 2.004, "eval_loss": 0.20469807088375092, "eval_precision": 0.7524752475247525, "eval_recall": 0.7671601615074024, "eval_f1": 0.7597467510829723, "eval_accuracy": 0.973743556701031, "eval_runtime": 12.2411, "eval_samples_per_second": 182.01, "eval_steps_per_second": 11.437}
VALIDATION_TIME fold=1 seed=123 seconds=12.24
CHECKPOINT_TIME fold=1 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 15.151515151515152, "step": 4500, "elapsed_minutes": 37.39, "average_steps_per_second": 2.006, "loss": 0.0008, "grad_norm": 0.072768434882164, "learning_rate": 1.8696706059156378e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 15.488215488215488, "step": 4600, "elapsed_minutes": 38.16, "average_steps_per_second": 2.009, "loss": 0.0011, "grad_norm": 0.005842109676450491, "learning_rate": 1.73992247226431e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 15.824915824915825, "step": 4700, "elapsed_minutes": 38.93, "average_steps_per_second": 2.012, "loss": 0.0011, "grad_norm": 3.6391470432281494, "learning_rate": 1.6101743386129815e-05}
EPOCH_TRAIN_END fold=1 seed=123 epoch=16.00
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 16.0, "step": 4752, "elapsed_minutes": 39.52, "average_steps_per_second": 2.004, "eval_loss": 0.18059055507183075, "eval_precision": 0.7626329787234043, "eval_recall": 0.7718707940780619, "eval_f1": 0.7672240802675585, "eval_accuracy": 0.974212160262418, "eval_runtime": 12.2344, "eval_samples_per_second": 182.109, "eval_steps_per_second": 11.443}
VALIDATION_TIME fold=1 seed=123 seconds=12.24
CHECKPOINT_TIME fold=1 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 16.161616161616163, "step": 4800, "elapsed_minutes": 39.92, "average_steps_per_second": 2.004, "loss": 0.0012, "grad_norm": 0.0014556573005393147, "learning_rate": 1.4804262049616535e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 16.4983164983165, "step": 4900, "elapsed_minutes": 40.67, "average_steps_per_second": 2.008, "loss": 0.0007, "grad_norm": 0.003292030654847622, "learning_rate": 1.3506780713103253e-05}

TRAIN_PROGRESS {"fold": 1, "seed": 123, "epoch": 17.0, "step": 5049, "elapsed_minutes": 42.22, "average_steps_per_second": 1.993, "eval_loss": 0.17390115559101105, "eval_precision": 0.7607843137254902, "eval_recall": 0.7833109017496636, "eval_f1": 0.7718832891246683, "eval_accuracy": 0.9732456654170571, "eval_runtime": 12.1624, "eval_samples_per_second": 183.187, "eval_steps_per_second": 11.511}
VALIDATION_TIME fold=1 seed=123 seconds=25.18
    fold=1 seed=123 | best_f1=0.7719 | eval_f1=0.7719 | 42.3 min

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  Seed 4242...
TRAIN_START fold=1 seed=4242 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 0.3367003367003367, "step": 100, "elapsed_minutes": 0.78, "average_steps_per_second": 2.145, "loss": 0.4699, "grad_norm": 0.7175684571266174, "learning_rate": 1.1560558708333332e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 0.6734006734006734, "step": 200, "elapsed_minutes": 1.55, "average_steps_per_second": 2.151, "loss": 0.1196, "grad_norm": 1.0506339073181152, "learning_rate": 2.323789073695286e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=1.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 1.0, "step": 297, "elapsed_minutes": 2.48, "average_steps_per_second": 1.995, "eval_loss": 0.0976838693022728, "eval_precision": 0.6267970097757332, "eval_recall": 0.7335127860026918, "eval_f1": 0.675968992248062, "eval_accuracy": 0.9674906279287723, "eval_runtime": 12.3076, "eval_samples_per_second": 181.027, "eval_steps_per_second": 11.375}
VALIDATION_TIME fold=1 seed=4242 seconds=12.31
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.66
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 1.0101010101010102, "step": 300, "elapsed_minutes": 2.51, "average_steps_per_second": 1.99, "loss": 0.1008, "grad_norm": 1.5688316822052002, "learning_rate": 3.491522276557239e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 1.3468013468013469, "step": 400, "elapsed_minutes": 3.27, "average_steps_per_second": 2.041, "loss": 0.0803, "grad_norm": 1.5316210985183716, "learning_rate": 4.6592554794191914e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 1.6835016835016834, "step": 500, "elapsed_minutes": 4.03, "average_steps_per_second": 2.065, "loss": 0.0799, "grad_norm": 0.2809658944606781, "learning_rate": 5.826988682281144e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=2.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 2.0, "step": 594, "elapsed_minutes": 4.95, "average_steps_per_second": 2.001, "eval_loss": 0.09343255311250687, "eval_precision": 0.6834625322997416, "eval_recall": 0.7119784656796769, "eval_f1": 0.6974291364535268, "eval_accuracy": 0.9700533036551078, "eval_runtime": 12.2003, "eval_samples_per_second": 182.618, "eval_steps_per_second": 11.475}
VALIDATION_TIME fold=1 seed=4242 seconds=12.20
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 2.0202020202020203, "step": 600, "elapsed_minutes": 5.01, "average_steps_per_second": 1.995, "loss": 0.078, "grad_norm": 0.770248293876648, "learning_rate": 6.929847818317433e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 2.356902356902357, "step": 700, "elapsed_minutes": 5.77, "average_steps_per_second": 2.023, "loss": 0.0504, "grad_norm": 1.1000285148620605, "learning_rate": 6.800099684666106e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 2.6936026936026938, "step": 800, "elapsed_minutes": 6.54, "average_steps_per_second": 2.039, "loss": 0.0492, "grad_norm": 0.5876379013061523, "learning_rate": 6.670351551014777e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=3.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 3.0, "step": 891, "elapsed_minutes": 7.43, "average_steps_per_second": 1.998, "eval_loss": 0.09747069329023361, "eval_precision": 0.6918199112238428, "eval_recall": 0.734185733512786, "eval_f1": 0.7123734900424421, "eval_accuracy": 0.9693943298969072, "eval_runtime": 12.2935, "eval_samples_per_second": 181.234, "eval_steps_per_second": 11.388}
VALIDATION_TIME fold=1 seed=4242 seconds=12.29
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.70
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 3.0303030303030303, "step": 900, "elapsed_minutes": 7.51, "average_steps_per_second": 1.998, "loss": 0.0545, "grad_norm": 1.375577688217163, "learning_rate": 6.54060341736345e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 3.3670033670033668, "step": 1000, "elapsed_minutes": 8.27, "average_steps_per_second": 2.015, "loss": 0.023, "grad_norm": 0.33600136637687683, "learning_rate": 6.41085528371212e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 3.7037037037037037, "step": 1100, "elapsed_minutes": 9.04, "average_steps_per_second": 2.027, "loss": 0.0333, "grad_norm": 0.964529812335968, "learning_rate": 6.281107150060793e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=4.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 4.0, "step": 1188, "elapsed_minutes": 9.91, "average_steps_per_second": 1.998, "eval_loss": 0.11399959772825241, "eval_precision": 0.7033232628398791, "eval_recall": 0.7833109017496636, "eval_f1": 0.7411652340019101, "eval_accuracy": 0.9710051546391752, "eval_runtime": 12.2205, "eval_samples_per_second": 182.317, "eval_steps_per_second": 11.456}
VALIDATION_TIME fold=1 seed=4242 seconds=12.22
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 4.040404040404041, "step": 1200, "elapsed_minutes": 10.0, "average_steps_per_second": 1.999, "loss": 0.0263, "grad_norm": 1.148956537246704, "learning_rate": 6.151359016409464e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 4.377104377104377, "step": 1300, "elapsed_minutes": 10.81, "average_steps_per_second": 2.005, "loss": 0.0166, "grad_norm": 0.17955146729946136, "learning_rate": 6.021610882758137e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 4.713804713804714, "step": 1400, "elapsed_minutes": 11.56, "average_steps_per_second": 2.018, "loss": 0.0181, "grad_norm": 0.4208054840564728, "learning_rate": 5.891862749106808e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=5.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 5.0, "step": 1485, "elapsed_minutes": 12.39, "average_steps_per_second": 1.997, "eval_loss": 0.11986373364925385, "eval_precision": 0.7268074216250799, "eval_recall": 0.7644683714670256, "eval_f1": 0.7451623483109215, "eval_accuracy": 0.9714884020618557, "eval_runtime": 12.2933, "eval_samples_per_second": 181.236, "eval_steps_per_second": 11.388}
VALIDATION_TIME fold=1 seed=4242 seconds=12.29
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 5.05050505050505, "step": 1500, "elapsed_minutes": 12.5, "average_steps_per_second": 1.999, "loss": 0.0176, "grad_norm": 0.8047587275505066, "learning_rate": 5.7621146154554804e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 5.3872053872053876, "step": 1600, "elapsed_minutes": 13.29, "average_steps_per_second": 2.007, "loss": 0.0115, "grad_norm": 0.6877867579460144, "learning_rate": 5.632366481804152e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 5.723905723905724, "step": 1700, "elapsed_minutes": 14.06, "average_steps_per_second": 2.015, "loss": 0.0127, "grad_norm": 3.5436222553253174, "learning_rate": 5.502618348152824e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=6.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 6.0, "step": 1782, "elapsed_minutes": 14.88, "average_steps_per_second": 1.996, "eval_loss": 0.13782407343387604, "eval_precision": 0.7139334155363748, "eval_recall": 0.7792732166890982, "eval_f1": 0.745173745173745, "eval_accuracy": 0.9724402530459232, "eval_runtime": 12.2607, "eval_samples_per_second": 181.719, "eval_steps_per_second": 11.419}
VALIDATION_TIME fold=1 seed=4242 seconds=12.26
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 6.0606060606060606, "step": 1800, "elapsed_minutes": 15.04, "average_steps_per_second": 1.995, "loss": 0.0124, "grad_norm": 0.23510099947452545, "learning_rate": 5.372870214501496e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 6.397306397306397, "step": 1900, "elapsed_minutes": 15.82, "average_steps_per_second": 2.002, "loss": 0.0074, "grad_norm": 0.1339694708585739, "learning_rate": 5.243122080850168e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 6.7340067340067336, "step": 2000, "elapsed_minutes": 16.55, "average_steps_per_second": 2.014, "loss": 0.0106, "grad_norm": 0.5916033387184143, "learning_rate": 5.11337394719884e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=7.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 7.0, "step": 2079, "elapsed_minutes": 17.36, "average_steps_per_second": 1.996, "eval_loss": 0.14476649463176727, "eval_precision": 0.75, "eval_recall": 0.7772543741588156, "eval_f1": 0.7633840052875083, "eval_accuracy": 0.9718691424554826, "eval_runtime": 12.2571, "eval_samples_per_second": 181.773, "eval_steps_per_second": 11.422}
VALIDATION_TIME fold=1 seed=4242 seconds=12.26
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 7.070707070707071, "step": 2100, "elapsed_minutes": 17.54, "average_steps_per_second": 1.995, "loss": 0.0071, "grad_norm": 0.1190185621380806, "learning_rate": 4.983625813547512e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 7.407407407407407, "step": 2200, "elapsed_minutes": 18.31, "average_steps_per_second": 2.002, "loss": 0.0059, "grad_norm": 2.2828211784362793, "learning_rate": 4.853877679896183e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 7.744107744107744, "step": 2300, "elapsed_minutes": 19.1, "average_steps_per_second": 2.007, "loss": 0.0062, "grad_norm": 1.5303609371185303, "learning_rate": 4.724129546244855e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=8.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 8.0, "step": 2376, "elapsed_minutes": 19.85, "average_steps_per_second": 1.995, "eval_loss": 0.1524592787027359, "eval_precision": 0.7306717363751585, "eval_recall": 0.7759084791386271, "eval_f1": 0.7526109660574414, "eval_accuracy": 0.9738167760074976, "eval_runtime": 12.2831, "eval_samples_per_second": 181.387, "eval_steps_per_second": 11.398}
VALIDATION_TIME fold=1 seed=4242 seconds=12.29
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 8.080808080808081, "step": 2400, "elapsed_minutes": 20.06, "average_steps_per_second": 1.994, "loss": 0.0064, "grad_norm": 0.07707102596759796, "learning_rate": 4.594381412593528e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 8.417508417508417, "step": 2500, "elapsed_minutes": 20.83, "average_steps_per_second": 2.0, "loss": 0.0049, "grad_norm": 0.032798536121845245, "learning_rate": 4.4646332789421995e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 8.754208754208754, "step": 2600, "elapsed_minutes": 21.6, "average_steps_per_second": 2.007, "loss": 0.0038, "grad_norm": 3.062185525894165, "learning_rate": 4.3348851452908714e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=9.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 9.0, "step": 2673, "elapsed_minutes": 22.34, "average_steps_per_second": 1.994, "eval_loss": 0.14678850769996643, "eval_precision": 0.740550928891736, "eval_recall": 0.7779273216689099, "eval_f1": 0.7587791270101739, "eval_accuracy": 0.9734213917525774, "eval_runtime": 12.375, "eval_samples_per_second": 180.04, "eval_steps_per_second": 11.313}
VALIDATION_TIME fold=1 seed=4242 seconds=12.38
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 9.090909090909092, "step": 2700, "elapsed_minutes": 22.55, "average_steps_per_second": 1.996, "loss": 0.0048, "grad_norm": 0.15786512196063995, "learning_rate": 4.205137011639543e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 9.427609427609427, "step": 2800, "elapsed_minutes": 23.32, "average_steps_per_second": 2.001, "loss": 0.0035, "grad_norm": 0.03838181868195534, "learning_rate": 4.075388877988216e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 9.764309764309765, "step": 2900, "elapsed_minutes": 24.09, "average_steps_per_second": 2.006, "loss": 0.0049, "grad_norm": 0.0401473268866539, "learning_rate": 3.9456407443368876e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=10.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 10.0, "step": 2970, "elapsed_minutes": 24.81, "average_steps_per_second": 1.995, "eval_loss": 0.15671077370643616, "eval_precision": 0.7521255722694572, "eval_recall": 0.7738896366083445, "eval_f1": 0.7628524046434494, "eval_accuracy": 0.9739192830365511, "eval_runtime": 12.3006, "eval_samples_per_second": 181.129, "eval_steps_per_second": 11.382}
VALIDATION_TIME fold=1 seed=4242 seconds=12.30
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.70
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 10.1010101010101, "step": 3000, "elapsed_minutes": 25.05, "average_steps_per_second": 1.996, "loss": 0.0039, "grad_norm": 1.6255587339401245, "learning_rate": 3.815892610685559e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 10.437710437710438, "step": 3100, "elapsed_minutes": 25.79, "average_steps_per_second": 2.003, "loss": 0.0021, "grad_norm": 0.002364621264860034, "learning_rate": 3.6861444770342306e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 10.774410774410775, "step": 3200, "elapsed_minutes": 26.58, "average_steps_per_second": 2.007, "loss": 0.0032, "grad_norm": 0.14080092310905457, "learning_rate": 3.556396343382903e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=11.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 11.0, "step": 3267, "elapsed_minutes": 27.28, "average_steps_per_second": 1.996, "eval_loss": 0.15694259107112885, "eval_precision": 0.7265822784810126, "eval_recall": 0.7725437415881561, "eval_f1": 0.7488584474885844, "eval_accuracy": 0.9710637300843487, "eval_runtime": 12.1842, "eval_samples_per_second": 182.86, "eval_steps_per_second": 11.49}
VALIDATION_TIME fold=1 seed=4242 seconds=12.19
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 11.11111111111111, "step": 3300, "elapsed_minutes": 27.53, "average_steps_per_second": 1.998, "loss": 0.0031, "grad_norm": 0.5924339294433594, "learning_rate": 3.426648209731575e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 11.447811447811448, "step": 3400, "elapsed_minutes": 28.31, "average_steps_per_second": 2.002, "loss": 0.002, "grad_norm": 1.1045037508010864, "learning_rate": 3.296900076080247e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 11.784511784511784, "step": 3500, "elapsed_minutes": 29.07, "average_steps_per_second": 2.007, "loss": 0.0022, "grad_norm": 0.4274045526981354, "learning_rate": 3.1671519424289186e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=12.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 12.0, "step": 3564, "elapsed_minutes": 29.77, "average_steps_per_second": 1.995, "eval_loss": 0.16826269030570984, "eval_precision": 0.75390625, "eval_recall": 0.7792732166890982, "eval_f1": 0.7663798808735937, "eval_accuracy": 0.9739339268978444, "eval_runtime": 12.1563, "eval_samples_per_second": 183.28, "eval_steps_per_second": 11.517}
VALIDATION_TIME fold=1 seed=4242 seconds=12.16
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 12.121212121212121, "step": 3600, "elapsed_minutes": 30.03, "average_steps_per_second": 1.998, "loss": 0.0029, "grad_norm": 0.09044133871793747, "learning_rate": 3.0374038087775905e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 12.457912457912458, "step": 3700, "elapsed_minutes": 30.81, "average_steps_per_second": 2.002, "loss": 0.0018, "grad_norm": 0.16170747578144073, "learning_rate": 2.9076556751262623e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 12.794612794612794, "step": 3800, "elapsed_minutes": 31.58, "average_steps_per_second": 2.006, "loss": 0.0017, "grad_norm": 0.9478470087051392, "learning_rate": 2.7779075414749345e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=13.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 13.0, "step": 3861, "elapsed_minutes": 32.24, "average_steps_per_second": 1.996, "eval_loss": 0.17941908538341522, "eval_precision": 0.7504898758981058, "eval_recall": 0.7732166890982504, "eval_f1": 0.7616837918462049, "eval_accuracy": 0.9730552952202437, "eval_runtime": 12.1345, "eval_samples_per_second": 183.609, "eval_steps_per_second": 11.537}
VALIDATION_TIME fold=1 seed=4242 seconds=12.14
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.64
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 13.131313131313131, "step": 3900, "elapsed_minutes": 32.55, "average_steps_per_second": 1.997, "loss": 0.0014, "grad_norm": 0.001531722373329103, "learning_rate": 2.648159407823606e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 13.468013468013467, "step": 4000, "elapsed_minutes": 33.35, "average_steps_per_second": 1.999, "loss": 0.0006, "grad_norm": 0.001853895140811801, "learning_rate": 2.5184112741722782e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 13.804713804713804, "step": 4100, "elapsed_minutes": 34.1, "average_steps_per_second": 2.004, "loss": 0.0013, "grad_norm": 0.0026073073968291283, "learning_rate": 2.38866314052095e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=14.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 14.0, "step": 4158, "elapsed_minutes": 34.72, "average_steps_per_second": 1.996, "eval_loss": 0.18100102245807648, "eval_precision": 0.7628797886393659, "eval_recall": 0.7772543741588156, "eval_f1": 0.77, "eval_accuracy": 0.973875351452671, "eval_runtime": 12.1597, "eval_samples_per_second": 183.228, "eval_steps_per_second": 11.513}
VALIDATION_TIME fold=1 seed=4242 seconds=12.16
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 14.141414141414142, "step": 4200, "elapsed_minutes": 35.05, "average_steps_per_second": 1.997, "loss": 0.0012, "grad_norm": 0.008472290821373463, "learning_rate": 2.2589150068696222e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 14.478114478114477, "step": 4300, "elapsed_minutes": 35.83, "average_steps_per_second": 2.0, "loss": 0.001, "grad_norm": 0.011734837666153908, "learning_rate": 2.1291668732182937e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 14.814814814814815, "step": 4400, "elapsed_minutes": 36.57, "average_steps_per_second": 2.005, "loss": 0.0006, "grad_norm": 0.0009583640494383872, "learning_rate": 1.999418739566966e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=15.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 15.0, "step": 4455, "elapsed_minutes": 37.18, "average_steps_per_second": 1.997, "eval_loss": 0.1702580600976944, "eval_precision": 0.7422419252691577, "eval_recall": 0.7886944818304172, "eval_f1": 0.764763458401305, "eval_accuracy": 0.9739192830365511, "eval_runtime": 12.1411, "eval_samples_per_second": 183.508, "eval_steps_per_second": 11.531}
VALIDATION_TIME fold=1 seed=4242 seconds=12.14
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.64
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 15.151515151515152, "step": 4500, "elapsed_minutes": 37.52, "average_steps_per_second": 1.999, "loss": 0.0008, "grad_norm": 0.01963024027645588, "learning_rate": 1.8696706059156378e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 15.488215488215488, "step": 4600, "elapsed_minutes": 38.26, "average_steps_per_second": 2.004, "loss": 0.0011, "grad_norm": 0.036575157195329666, "learning_rate": 1.73992247226431e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 15.824915824915825, "step": 4700, "elapsed_minutes": 39.01, "average_steps_per_second": 2.008, "loss": 0.0009, "grad_norm": 0.007767763454467058, "learning_rate": 1.6101743386129815e-05}
EPOCH_TRAIN_END fold=1 seed=4242 epoch=16.00
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 16.0, "step": 4752, "elapsed_minutes": 39.64, "average_steps_per_second": 1.998, "eval_loss": 0.18129663169384003, "eval_precision": 0.7515923566878981, "eval_recall": 0.7940780619111709, "eval_f1": 0.7722513089005235, "eval_accuracy": 0.9747832708528584, "eval_runtime": 12.3259, "eval_samples_per_second": 180.758, "eval_steps_per_second": 11.358}
VALIDATION_TIME fold=1 seed=4242 seconds=12.33
CHECKPOINT_TIME fold=1 seed=4242 seconds=0.70
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 16.161616161616163, "step": 4800, "elapsed_minutes": 40.0, "average_steps_per_second": 2.0, "loss": 0.0002, "grad_norm": 0.013944649137556553, "learning_rate": 1.4804262049616535e-05}
TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 16.4983164983165, "step": 4900, "elapsed_minutes": 40.78, "average_steps_per_second": 2.003, "loss": 0.0006, "grad_norm": 0.0007432784186676145, "learning_rate": 1.3506780713103253e-05}

TRAIN_PROGRESS {"fold": 1, "seed": 4242, "epoch": 20.0, "step": 5940, "elapsed_minutes": 49.71, "average_steps_per_second": 1.992, "eval_loss": 0.17845958471298218, "eval_precision": 0.7587096774193548, "eval_recall": 0.7913862718707941, "eval_f1": 0.774703557312253, "eval_accuracy": 0.9747393392689785, "eval_runtime": 12.1997, "eval_samples_per_second": 182.627, "eval_steps_per_second": 11.476}
VALIDATION_TIME fold=1 seed=4242 seconds=25.32
    fold=1 seed=4242 | best_f1=0.7747 | eval_f1=0.7747 | 49.7 min

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 2/5 | train=600 docs / 9280 seqs | val=150 docs / 2433 seqs
  Seed 123...
TRAIN_START fold=2 seed=123 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 0.3448275862068966, "step": 100, "elapsed_minutes": 0.77, "average_steps_per_second": 2.165, "loss": 0.4612, "grad_norm": 1.9594199657440186, "learning_rate": 1.1839606677155173e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 0.6896551724137931, "step": 200, "elapsed_minutes": 1.54, "average_steps_per_second": 2.159, "loss": 0.1115, "grad_norm": 1.5088775157928467, "learning_rate": 2.3798805340948275e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=1.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 1.0, "step": 290, "elapsed_minutes": 2.45, "average_steps_per_second": 1.975, "eval_loss": 0.10512122511863708, "eval_precision": 0.6277864178330741, "eval_recall": 0.7165680473372781, "eval_f1": 0.6692456479690522, "eval_accuracy": 0.9643503878483203, "eval_runtime": 13.5103, "eval_samples_per_second": 180.084, "eval_steps_per_second": 11.325}
VALIDATION_TIME fold=2 seed=123 seconds=13.52
CHECKPOINT_TIME fold=2 seed=123 seconds=0.71
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 1.0344827586206897, "step": 300, "elapsed_minutes": 2.54, "average_steps_per_second": 1.972, "loss": 0.1017, "grad_norm": 1.681107759475708, "learning_rate": 3.5758004004741375e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 1.3793103448275863, "step": 400, "elapsed_minutes": 3.29, "average_steps_per_second": 2.028, "loss": 0.0724, "grad_norm": 2.485020637512207, "learning_rate": 4.771720266853448e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 1.7241379310344827, "step": 500, "elapsed_minutes": 4.05, "average_steps_per_second": 2.058, "loss": 0.0807, "grad_norm": 1.2481136322021484, "learning_rate": 5.967640133232758e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=2.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 2.0, "step": 580, "elapsed_minutes": 4.88, "average_steps_per_second": 1.98, "eval_loss": 0.09628108888864517, "eval_precision": 0.6506814740030288, "eval_recall": 0.7627218934911243, "eval_f1": 0.7022609643149006, "eval_accuracy": 0.9682694126868294, "eval_runtime": 13.344, "eval_samples_per_second": 182.329, "eval_steps_per_second": 11.466}
VALIDATION_TIME fold=2 seed=123 seconds=13.35
CHECKPOINT_TIME fold=2 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 2.0689655172413794, "step": 600, "elapsed_minutes": 5.06, "average_steps_per_second": 1.977, "loss": 0.0718, "grad_norm": 2.725372791290283, "learning_rate": 6.911088027820881e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 2.413793103448276, "step": 700, "elapsed_minutes": 5.82, "average_steps_per_second": 2.005, "loss": 0.0511, "grad_norm": 1.513863205909729, "learning_rate": 6.778208042667623e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 2.7586206896551726, "step": 800, "elapsed_minutes": 6.57, "average_steps_per_second": 2.029, "loss": 0.0528, "grad_norm": 0.9588475227355957, "learning_rate": 6.645328057514368e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=3.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 3.0, "step": 870, "elapsed_minutes": 7.33, "average_steps_per_second": 1.978, "eval_loss": 0.10638730227947235, "eval_precision": 0.6818419675562533, "eval_recall": 0.7710059171597633, "eval_f1": 0.7236878644820882, "eval_accuracy": 0.9656342063299008, "eval_runtime": 13.2441, "eval_samples_per_second": 183.705, "eval_steps_per_second": 11.552}
VALIDATION_TIME fold=2 seed=123 seconds=13.25
CHECKPOINT_TIME fold=2 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 3.103448275862069, "step": 900, "elapsed_minutes": 7.56, "average_steps_per_second": 1.983, "loss": 0.0381, "grad_norm": 1.1603567600250244, "learning_rate": 6.51244807236111e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 3.4482758620689653, "step": 1000, "elapsed_minutes": 8.33, "average_steps_per_second": 2.001, "loss": 0.0272, "grad_norm": 0.1809770166873932, "learning_rate": 6.379568087207855e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 3.793103448275862, "step": 1100, "elapsed_minutes": 9.06, "average_steps_per_second": 2.023, "loss": 0.0317, "grad_norm": 2.2803523540496826, "learning_rate": 6.246688102054597e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=4.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 4.0, "step": 1160, "elapsed_minutes": 9.75, "average_steps_per_second": 1.982, "eval_loss": 0.12381010502576828, "eval_precision": 0.7342211928199189, "eval_recall": 0.7502958579881657, "eval_f1": 0.7421714954638571, "eval_accuracy": 0.9707559663774696, "eval_runtime": 13.2974, "eval_samples_per_second": 182.968, "eval_steps_per_second": 11.506}
VALIDATION_TIME fold=2 seed=123 seconds=13.30
CHECKPOINT_TIME fold=2 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 4.137931034482759, "step": 1200, "elapsed_minutes": 10.09, "average_steps_per_second": 1.982, "loss": 0.0214, "grad_norm": 0.5315607190132141, "learning_rate": 6.11380811690134e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 4.482758620689655, "step": 1300, "elapsed_minutes": 10.82, "average_steps_per_second": 2.003, "loss": 0.0166, "grad_norm": 2.008936882019043, "learning_rate": 5.980928131748084e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 4.827586206896552, "step": 1400, "elapsed_minutes": 11.6, "average_steps_per_second": 2.012, "loss": 0.0189, "grad_norm": 0.7075676918029785, "learning_rate": 5.848048146594827e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=5.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 5.0, "step": 1450, "elapsed_minutes": 12.18, "average_steps_per_second": 1.983, "eval_loss": 0.12773358821868896, "eval_precision": 0.7307692307692307, "eval_recall": 0.7420118343195267, "eval_f1": 0.7363476218438051, "eval_accuracy": 0.9699316197735074, "eval_runtime": 13.2183, "eval_samples_per_second": 184.063, "eval_steps_per_second": 11.575}
VALIDATION_TIME fold=2 seed=123 seconds=13.22
CHECKPOINT_TIME fold=2 seed=123 seconds=0.66
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 5.172413793103448, "step": 1500, "elapsed_minutes": 12.61, "average_steps_per_second": 1.983, "loss": 0.0152, "grad_norm": 1.2224478721618652, "learning_rate": 5.715168161441571e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 5.517241379310345, "step": 1600, "elapsed_minutes": 13.34, "average_steps_per_second": 1.999, "loss": 0.0098, "grad_norm": 0.2827400267124176, "learning_rate": 5.5822881762883136e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 5.862068965517241, "step": 1700, "elapsed_minutes": 14.1, "average_steps_per_second": 2.009, "loss": 0.0092, "grad_norm": 0.9083213210105896, "learning_rate": 5.449408191135057e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=6.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 6.0, "step": 1740, "elapsed_minutes": 14.62, "average_steps_per_second": 1.983, "eval_loss": 0.14354941248893738, "eval_precision": 0.7484057971014493, "eval_recall": 0.763905325443787, "eval_f1": 0.7560761346998537, "eval_accuracy": 0.9697153977134517, "eval_runtime": 13.1464, "eval_samples_per_second": 185.069, "eval_steps_per_second": 11.638}
VALIDATION_TIME fold=2 seed=123 seconds=13.15
CHECKPOINT_TIME fold=2 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 6.206896551724138, "step": 1800, "elapsed_minutes": 15.08, "average_steps_per_second": 1.989, "loss": 0.0097, "grad_norm": 0.41414207220077515, "learning_rate": 5.3165282059818004e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 6.551724137931035, "step": 1900, "elapsed_minutes": 15.84, "average_steps_per_second": 2.0, "loss": 0.0054, "grad_norm": 0.1496831774711609, "learning_rate": 5.183648220828544e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 6.896551724137931, "step": 2000, "elapsed_minutes": 16.59, "average_steps_per_second": 2.01, "loss": 0.0061, "grad_norm": 0.05665922909975052, "learning_rate": 5.050768235675287e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=7.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 7.0, "step": 2030, "elapsed_minutes": 17.03, "average_steps_per_second": 1.987, "eval_loss": 0.14864391088485718, "eval_precision": 0.7248322147651006, "eval_recall": 0.7668639053254438, "eval_f1": 0.7452558941920644, "eval_accuracy": 0.9680667045055272, "eval_runtime": 13.427, "eval_samples_per_second": 181.202, "eval_steps_per_second": 11.395}
VALIDATION_TIME fold=2 seed=123 seconds=13.43
CHECKPOINT_TIME fold=2 seed=123 seconds=0.65
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 7.241379310344827, "step": 2100, "elapsed_minutes": 17.59, "average_steps_per_second": 1.99, "loss": 0.0065, "grad_norm": 0.47228115797042847, "learning_rate": 4.9178882505220305e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 7.586206896551724, "step": 2200, "elapsed_minutes": 18.33, "average_steps_per_second": 2.0, "loss": 0.0059, "grad_norm": 0.20681266486644745, "learning_rate": 4.785008265368774e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 7.931034482758621, "step": 2300, "elapsed_minutes": 19.09, "average_steps_per_second": 2.008, "loss": 0.0064, "grad_norm": 0.7799997329711914, "learning_rate": 4.6521282802155165e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=8.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 8.0, "step": 2320, "elapsed_minutes": 19.46, "average_steps_per_second": 1.987, "eval_loss": 0.1586136817932129, "eval_precision": 0.7508670520231214, "eval_recall": 0.7686390532544378, "eval_f1": 0.7596491228070176, "eval_accuracy": 0.9702154112273305, "eval_runtime": 13.4409, "eval_samples_per_second": 181.015, "eval_steps_per_second": 11.383}
VALIDATION_TIME fold=2 seed=123 seconds=13.44
CHECKPOINT_TIME fold=2 seed=123 seconds=0.74
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 8.275862068965518, "step": 2400, "elapsed_minutes": 20.05, "average_steps_per_second": 1.995, "loss": 0.0055, "grad_norm": 1.594849705696106, "learning_rate": 4.5192482950622606e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 8.620689655172415, "step": 2500, "elapsed_minutes": 20.8, "average_steps_per_second": 2.003, "loss": 0.0056, "grad_norm": 0.024026809260249138, "learning_rate": 4.386368309909003e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 8.96551724137931, "step": 2600, "elapsed_minutes": 21.59, "average_steps_per_second": 2.008, "loss": 0.0067, "grad_norm": 0.050177015364170074, "learning_rate": 4.253488324755747e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=9.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 9.0, "step": 2610, "elapsed_minutes": 21.87, "average_steps_per_second": 1.989, "eval_loss": 0.14611934125423431, "eval_precision": 0.7472160356347439, "eval_recall": 0.7940828402366864, "eval_f1": 0.7699368904188181, "eval_accuracy": 0.9706343414686883, "eval_runtime": 13.268, "eval_samples_per_second": 183.374, "eval_steps_per_second": 11.532}
VALIDATION_TIME fold=2 seed=123 seconds=13.27
CHECKPOINT_TIME fold=2 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 9.310344827586206, "step": 2700, "elapsed_minutes": 22.58, "average_steps_per_second": 1.993, "loss": 0.0045, "grad_norm": 0.07486015558242798, "learning_rate": 4.12060833960249e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 9.655172413793103, "step": 2800, "elapsed_minutes": 23.33, "average_steps_per_second": 2.001, "loss": 0.0038, "grad_norm": 0.8585968017578125, "learning_rate": 3.9877283544492333e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 10.0, "step": 2900, "elapsed_minutes": 24.09, "average_steps_per_second": 2.006, "loss": 0.0029, "grad_norm": 0.15299870073795319, "learning_rate": 3.854848369295977e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=10.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 10.0, "step": 2900, "elapsed_minutes": 24.31, "average_steps_per_second": 1.988, "eval_loss": 0.1729993373155594, "eval_precision": 0.7437325905292479, "eval_recall": 0.7899408284023669, "eval_f1": 0.7661406025824964, "eval_accuracy": 0.9700802724397957, "eval_runtime": 13.15, "eval_samples_per_second": 185.019, "eval_steps_per_second": 11.635}
VALIDATION_TIME fold=2 seed=123 seconds=13.15
CHECKPOINT_TIME fold=2 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 10.344827586206897, "step": 3000, "elapsed_minutes": 25.08, "average_steps_per_second": 1.993, "loss": 0.0023, "grad_norm": 0.27536553144454956, "learning_rate": 3.72196838414272e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 10.689655172413794, "step": 3100, "elapsed_minutes": 25.84, "average_steps_per_second": 2.0, "loss": 0.0023, "grad_norm": 0.002387476619333029, "learning_rate": 3.5890883989894634e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=11.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 11.0, "step": 3190, "elapsed_minutes": 26.76, "average_steps_per_second": 1.987, "eval_loss": 0.18948350846767426, "eval_precision": 0.742792538157151, "eval_recall": 0.7775147928994083, "eval_f1": 0.7597571552471812, "eval_accuracy": 0.9694045785021217, "eval_runtime": 14.0715, "eval_samples_per_second": 172.903, "eval_steps_per_second": 10.873}
VALIDATION_TIME fold=2 seed=123 seconds=14.07
CHECKPOINT_TIME fold=2 seed=123 seconds=0.73
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 11.03448275862069, "step": 3200, "elapsed_minutes": 26.85, "average_steps_per_second": 1.986, "loss": 0.002, "grad_norm": 0.037739768624305725, "learning_rate": 3.456208413836207e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 11.379310344827585, "step": 3300, "elapsed_minutes": 27.58, "average_steps_per_second": 1.994, "loss": 0.0035, "grad_norm": 0.26688966155052185, "learning_rate": 3.32332842868295e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 11.724137931034482, "step": 3400, "elapsed_minutes": 28.35, "average_steps_per_second": 1.998, "loss": 0.0019, "grad_norm": 0.2959931194782257, "learning_rate": 3.1904484435296935e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=12.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 12.0, "step": 3480, "elapsed_minutes": 29.18, "average_steps_per_second": 1.988, "eval_loss": 0.1962813287973404, "eval_precision": 0.7816301703163017, "eval_recall": 0.7603550295857988, "eval_f1": 0.7708458308338332, "eval_accuracy": 0.9704451471661396, "eval_runtime": 13.3713, "eval_samples_per_second": 181.957, "eval_steps_per_second": 11.442}
VALIDATION_TIME fold=2 seed=123 seconds=13.37
CHECKPOINT_TIME fold=2 seed=123 seconds=0.72
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 12.068965517241379, "step": 3500, "elapsed_minutes": 29.33, "average_steps_per_second": 1.989, "loss": 0.0018, "grad_norm": 0.018995406106114388, "learning_rate": 3.057568458376437e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 12.413793103448276, "step": 3600, "elapsed_minutes": 30.07, "average_steps_per_second": 1.995, "loss": 0.0012, "grad_norm": 0.04941600561141968, "learning_rate": 2.92468847322318e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 12.758620689655173, "step": 3700, "elapsed_minutes": 30.86, "average_steps_per_second": 1.998, "loss": 0.0018, "grad_norm": 0.5407408475875854, "learning_rate": 2.7918084880699233e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=13.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 13.0, "step": 3770, "elapsed_minutes": 31.61, "average_steps_per_second": 1.988, "eval_loss": 0.20107974112033844, "eval_precision": 0.7701149425287356, "eval_recall": 0.7532544378698225, "eval_f1": 0.7615913849835476, "eval_accuracy": 0.9703775777723722, "eval_runtime": 13.3289, "eval_samples_per_second": 182.536, "eval_steps_per_second": 11.479}
VALIDATION_TIME fold=2 seed=123 seconds=13.33
CHECKPOINT_TIME fold=2 seed=123 seconds=0.66
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 13.10344827586207, "step": 3800, "elapsed_minutes": 31.86, "average_steps_per_second": 1.988, "loss": 0.0016, "grad_norm": 0.0012143999338150024, "learning_rate": 2.6589285029166667e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 13.448275862068966, "step": 3900, "elapsed_minutes": 32.67, "average_steps_per_second": 1.99, "loss": 0.0012, "grad_norm": 0.02608264982700348, "learning_rate": 2.5260485177634097e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 13.793103448275861, "step": 4000, "elapsed_minutes": 33.4, "average_steps_per_second": 1.996, "loss": 0.0008, "grad_norm": 0.0812603086233139, "learning_rate": 2.393168532610153e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=14.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 14.0, "step": 4060, "elapsed_minutes": 34.06, "average_steps_per_second": 1.987, "eval_loss": 0.1979743391275406, "eval_precision": 0.7594117647058823, "eval_recall": 0.763905325443787, "eval_f1": 0.7616519174041297, "eval_accuracy": 0.971526257466418, "eval_runtime": 13.2998, "eval_samples_per_second": 182.935, "eval_steps_per_second": 11.504}
VALIDATION_TIME fold=2 seed=123 seconds=13.30
CHECKPOINT_TIME fold=2 seed=123 seconds=0.71
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 14.137931034482758, "step": 4100, "elapsed_minutes": 34.38, "average_steps_per_second": 1.988, "loss": 0.0011, "grad_norm": 0.003716591978445649, "learning_rate": 2.2602885474568964e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 14.482758620689655, "step": 4200, "elapsed_minutes": 35.15, "average_steps_per_second": 1.992, "loss": 0.0007, "grad_norm": 0.1335265040397644, "learning_rate": 2.1274085623036395e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 14.827586206896552, "step": 4300, "elapsed_minutes": 35.91, "average_steps_per_second": 1.996, "loss": 0.0006, "grad_norm": 0.3329882323741913, "learning_rate": 1.994528577150383e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=15.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 15.0, "step": 4350, "elapsed_minutes": 36.53, "average_steps_per_second": 1.985, "eval_loss": 0.20924334228038788, "eval_precision": 0.7374860956618465, "eval_recall": 0.7846153846153846, "eval_f1": 0.7603211009174312, "eval_accuracy": 0.970512716559907, "eval_runtime": 13.7523, "eval_samples_per_second": 176.916, "eval_steps_per_second": 11.125}
VALIDATION_TIME fold=2 seed=123 seconds=13.75
CHECKPOINT_TIME fold=2 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 15.172413793103448, "step": 4400, "elapsed_minutes": 36.92, "average_steps_per_second": 1.986, "loss": 0.0011, "grad_norm": 0.0018921656301245093, "learning_rate": 1.8616485919971262e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 15.517241379310345, "step": 4500, "elapsed_minutes": 37.7, "average_steps_per_second": 1.989, "loss": 0.0007, "grad_norm": 0.1633816808462143, "learning_rate": 1.7287686068438696e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 15.862068965517242, "step": 4600, "elapsed_minutes": 38.45, "average_steps_per_second": 1.994, "loss": 0.0005, "grad_norm": 0.002314648125320673, "learning_rate": 1.595888621690613e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=16.00
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 16.0, "step": 4640, "elapsed_minutes": 38.98, "average_steps_per_second": 1.984, "eval_loss": 0.20880261063575745, "eval_precision": 0.7554660529344074, "eval_recall": 0.7769230769230769, "eval_f1": 0.766044340723454, "eval_accuracy": 0.9713100354063623, "eval_runtime": 13.351, "eval_samples_per_second": 182.234, "eval_steps_per_second": 11.46}
VALIDATION_TIME fold=2 seed=123 seconds=13.35
CHECKPOINT_TIME fold=2 seed=123 seconds=0.72
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 16.20689655172414, "step": 4700, "elapsed_minutes": 39.49, "average_steps_per_second": 1.984, "loss": 0.0003, "grad_norm": 0.0008608676725998521, "learning_rate": 1.4630086365373561e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 16.551724137931036, "step": 4800, "elapsed_minutes": 40.22, "average_steps_per_second": 1.989, "loss": 0.0002, "grad_norm": 0.0016294046072289348, "learning_rate": 1.3301286513840995e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 16.896551724137932, "step": 4900, "elapsed_minutes": 40.99, "average_steps_per_second": 1.992, "loss": 0.001, "grad_norm": 0.0010998621582984924, "learning_rate": 1.1972486662308429e-05}
EPOCH_TRAIN_END fold=2 seed=123 epoch=17.00

TRAIN_PROGRESS {"fold": 2, "seed": 123, "epoch": 17.0, "step": 4930, "elapsed_minutes": 41.66, "average_steps_per_second": 1.972, "eval_loss": 0.1962813287973404, "eval_precision": 0.7816301703163017, "eval_recall": 0.7603550295857988, "eval_f1": 0.7708458308338332, "eval_accuracy": 0.9704451471661396, "eval_runtime": 13.1833, "eval_samples_per_second": 184.551, "eval_steps_per_second": 11.606}
VALIDATION_TIME fold=2 seed=123 seconds=27.39
    fold=2 seed=123 | best_f1=0.7708 | eval_f1=0.7708 | 41.7 min

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  Seed 4242...
TRAIN_START fold=2 seed=4242 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 0.3448275862068966, "step": 100, "elapsed_minutes": 0.77, "average_steps_per_second": 2.169, "loss": 0.4661, "grad_norm": 1.8884471654891968, "learning_rate": 1.1839606677155173e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 0.6896551724137931, "step": 200, "elapsed_minutes": 1.57, "average_steps_per_second": 2.13, "loss": 0.111, "grad_norm": 1.3006161451339722, "learning_rate": 2.3798805340948275e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=1.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 1.0, "step": 290, "elapsed_minutes": 2.45, "average_steps_per_second": 1.975, "eval_loss": 0.10710784047842026, "eval_precision": 0.6302057200200702, "eval_recall": 0.7431952662721893, "eval_f1": 0.6820526744501765, "eval_accuracy": 0.9622557366415309, "eval_runtime": 13.3729, "eval_samples_per_second": 181.935, "eval_steps_per_second": 11.441}
VALIDATION_TIME fold=2 seed=4242 seconds=13.38
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 1.0344827586206897, "step": 300, "elapsed_minutes": 2.53, "average_steps_per_second": 1.976, "loss": 0.101, "grad_norm": 1.2903306484222412, "learning_rate": 3.5758004004741375e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 1.3793103448275863, "step": 400, "elapsed_minutes": 3.3, "average_steps_per_second": 2.018, "loss": 0.0803, "grad_norm": 1.2255550622940063, "learning_rate": 4.771720266853448e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 1.7241379310344827, "step": 500, "elapsed_minutes": 4.09, "average_steps_per_second": 2.037, "loss": 0.0769, "grad_norm": 1.8529918193817139, "learning_rate": 5.967640133232758e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=2.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 2.0, "step": 580, "elapsed_minutes": 4.89, "average_steps_per_second": 1.977, "eval_loss": 0.10470261424779892, "eval_precision": 0.6649404453650958, "eval_recall": 0.7597633136094675, "eval_f1": 0.7091963545981773, "eval_accuracy": 0.9688369955944756, "eval_runtime": 13.2122, "eval_samples_per_second": 184.148, "eval_steps_per_second": 11.58}
VALIDATION_TIME fold=2 seed=4242 seconds=13.21
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.71
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 2.0689655172413794, "step": 600, "elapsed_minutes": 5.05, "average_steps_per_second": 1.981, "loss": 0.0691, "grad_norm": 1.6211379766464233, "learning_rate": 6.911088027820881e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 2.413793103448276, "step": 700, "elapsed_minutes": 5.83, "average_steps_per_second": 2.0, "loss": 0.0485, "grad_norm": 1.858426809310913, "learning_rate": 6.778208042667623e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 2.7586206896551726, "step": 800, "elapsed_minutes": 6.59, "average_steps_per_second": 2.022, "loss": 0.0509, "grad_norm": 0.9829489588737488, "learning_rate": 6.645328057514368e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=3.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 3.0, "step": 870, "elapsed_minutes": 7.33, "average_steps_per_second": 1.978, "eval_loss": 0.11718171834945679, "eval_precision": 0.6840425531914893, "eval_recall": 0.7609467455621302, "eval_f1": 0.7204481792717087, "eval_accuracy": 0.9663369280250818, "eval_runtime": 13.3071, "eval_samples_per_second": 182.835, "eval_steps_per_second": 11.498}
VALIDATION_TIME fold=2 seed=4242 seconds=13.31
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 3.103448275862069, "step": 900, "elapsed_minutes": 7.57, "average_steps_per_second": 1.981, "loss": 0.0425, "grad_norm": 1.6628062725067139, "learning_rate": 6.51244807236111e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 3.4482758620689653, "step": 1000, "elapsed_minutes": 8.35, "average_steps_per_second": 1.997, "loss": 0.0281, "grad_norm": 1.1295132637023926, "learning_rate": 6.379568087207855e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 3.793103448275862, "step": 1100, "elapsed_minutes": 9.12, "average_steps_per_second": 2.01, "loss": 0.0296, "grad_norm": 0.9145174622535706, "learning_rate": 6.246688102054597e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=4.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 4.0, "step": 1160, "elapsed_minutes": 9.79, "average_steps_per_second": 1.975, "eval_loss": 0.11223339289426804, "eval_precision": 0.6763185108583247, "eval_recall": 0.7739644970414201, "eval_f1": 0.7218543046357616, "eval_accuracy": 0.9646071515446364, "eval_runtime": 13.7493, "eval_samples_per_second": 176.955, "eval_steps_per_second": 11.128}
VALIDATION_TIME fold=2 seed=4242 seconds=13.75
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 4.137931034482759, "step": 1200, "elapsed_minutes": 10.08, "average_steps_per_second": 1.983, "loss": 0.0243, "grad_norm": 0.8575513362884521, "learning_rate": 6.11380811690134e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 4.482758620689655, "step": 1300, "elapsed_minutes": 10.87, "average_steps_per_second": 1.992, "loss": 0.0175, "grad_norm": 3.005997657775879, "learning_rate": 5.980928131748084e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 4.827586206896552, "step": 1400, "elapsed_minutes": 11.64, "average_steps_per_second": 2.005, "loss": 0.0206, "grad_norm": 0.6215978860855103, "learning_rate": 5.848048146594827e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=5.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 5.0, "step": 1450, "elapsed_minutes": 12.24, "average_steps_per_second": 1.975, "eval_loss": 0.12066857516765594, "eval_precision": 0.7388143176733781, "eval_recall": 0.7816568047337278, "eval_f1": 0.7596319723979298, "eval_accuracy": 0.9699856752885213, "eval_runtime": 13.2965, "eval_samples_per_second": 182.98, "eval_steps_per_second": 11.507}
VALIDATION_TIME fold=2 seed=4242 seconds=13.30
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 5.172413793103448, "step": 1500, "elapsed_minutes": 12.61, "average_steps_per_second": 1.982, "loss": 0.0132, "grad_norm": 1.1525466442108154, "learning_rate": 5.715168161441571e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 5.517241379310345, "step": 1600, "elapsed_minutes": 13.38, "average_steps_per_second": 1.993, "loss": 0.0093, "grad_norm": 1.308546543121338, "learning_rate": 5.5822881762883136e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 5.862068965517241, "step": 1700, "elapsed_minutes": 14.15, "average_steps_per_second": 2.002, "loss": 0.0124, "grad_norm": 1.0111720561981201, "learning_rate": 5.449408191135057e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=6.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 6.0, "step": 1740, "elapsed_minutes": 14.66, "average_steps_per_second": 1.978, "eval_loss": 0.15283961594104767, "eval_precision": 0.7437097717963721, "eval_recall": 0.7520710059171598, "eval_f1": 0.7478670197116799, "eval_accuracy": 0.9703235222573583, "eval_runtime": 13.346, "eval_samples_per_second": 182.302, "eval_steps_per_second": 11.464}
VALIDATION_TIME fold=2 seed=4242 seconds=13.35
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.71
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 6.206896551724138, "step": 1800, "elapsed_minutes": 15.13, "average_steps_per_second": 1.983, "loss": 0.0083, "grad_norm": 0.2405729591846466, "learning_rate": 5.3165282059818004e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 6.551724137931035, "step": 1900, "elapsed_minutes": 15.88, "average_steps_per_second": 1.994, "loss": 0.0085, "grad_norm": 2.8920466899871826, "learning_rate": 5.183648220828544e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 6.896551724137931, "step": 2000, "elapsed_minutes": 16.66, "average_steps_per_second": 2.0, "loss": 0.0095, "grad_norm": 0.07027048617601395, "learning_rate": 5.050768235675287e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=7.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 7.0, "step": 2030, "elapsed_minutes": 17.11, "average_steps_per_second": 1.978, "eval_loss": 0.15573449432849884, "eval_precision": 0.7565588773642465, "eval_recall": 0.7337278106508875, "eval_f1": 0.7449684589966957, "eval_accuracy": 0.9699721614097678, "eval_runtime": 13.2725, "eval_samples_per_second": 183.311, "eval_steps_per_second": 11.528}
VALIDATION_TIME fold=2 seed=4242 seconds=13.27
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.87
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 7.241379310344827, "step": 2100, "elapsed_minutes": 17.66, "average_steps_per_second": 1.982, "loss": 0.0063, "grad_norm": 0.17528752982616425, "learning_rate": 4.9178882505220305e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 7.586206896551724, "step": 2200, "elapsed_minutes": 18.43, "average_steps_per_second": 1.99, "loss": 0.0041, "grad_norm": 0.22841496765613556, "learning_rate": 4.785008265368774e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 7.931034482758621, "step": 2300, "elapsed_minutes": 19.18, "average_steps_per_second": 1.998, "loss": 0.0063, "grad_norm": 0.1349833905696869, "learning_rate": 4.6521282802155165e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=8.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 8.0, "step": 2320, "elapsed_minutes": 19.57, "average_steps_per_second": 1.976, "eval_loss": 0.1787472367286682, "eval_precision": 0.7382857142857143, "eval_recall": 0.7644970414201183, "eval_f1": 0.7511627906976744, "eval_accuracy": 0.9694856617746426, "eval_runtime": 14.1225, "eval_samples_per_second": 172.278, "eval_steps_per_second": 10.834}
VALIDATION_TIME fold=2 seed=4242 seconds=14.12
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.71
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 8.275862068965518, "step": 2400, "elapsed_minutes": 20.18, "average_steps_per_second": 1.982, "loss": 0.0046, "grad_norm": 2.2643110752105713, "learning_rate": 4.5192482950622606e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 8.620689655172415, "step": 2500, "elapsed_minutes": 20.95, "average_steps_per_second": 1.989, "loss": 0.0056, "grad_norm": 0.03444633632898331, "learning_rate": 4.386368309909003e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 8.96551724137931, "step": 2600, "elapsed_minutes": 21.7, "average_steps_per_second": 1.997, "loss": 0.0045, "grad_norm": 0.3852895200252533, "learning_rate": 4.253488324755747e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=9.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 9.0, "step": 2610, "elapsed_minutes": 21.99, "average_steps_per_second": 1.978, "eval_loss": 0.16302983462810516, "eval_precision": 0.7494047619047619, "eval_recall": 0.7449704142011835, "eval_f1": 0.7471810089020773, "eval_accuracy": 0.9695126895321495, "eval_runtime": 13.5872, "eval_samples_per_second": 179.065, "eval_steps_per_second": 11.261}
VALIDATION_TIME fold=2 seed=4242 seconds=13.59
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.80
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 9.310344827586206, "step": 2700, "elapsed_minutes": 22.71, "average_steps_per_second": 1.982, "loss": 0.0026, "grad_norm": 0.07987245172262192, "learning_rate": 4.12060833960249e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 9.655172413793103, "step": 2800, "elapsed_minutes": 23.47, "average_steps_per_second": 1.989, "loss": 0.0042, "grad_norm": 0.00601029209792614, "learning_rate": 3.9877283544492333e-05}
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 10.0, "step": 2900, "elapsed_minutes": 24.24, "average_steps_per_second": 1.994, "loss": 0.0027, "grad_norm": 0.07365640997886658, "learning_rate": 3.854848369295977e-05}
EPOCH_TRAIN_END fold=2 seed=4242 epoch=10.00
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 10.0, "step": 2900, "elapsed_minutes": 24.46, "average_steps_per_second": 1.976, "eval_loss": 0.19765296578407288, "eval_precision": 0.7136612021857923, "eval_recall": 0.7727810650887574, "eval_f1": 0.7420454545454545, "eval_accuracy": 0.96555312305738, "eval_runtime": 13.3366, "eval_samples_per_second": 182.43, "eval_steps_per_second": 11.472}
VALIDATION_TIME fold=2 seed=4242 seconds=13.34
CHECKPOINT_TIME fold=2 seed=4242 seconds=0.79
TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 10.0, "step": 2900, "elapsed_minutes": 24.48, "average_steps_per_second": 1.974, "train_runtime": 1468.7518, "train_samples_per_second": 126.366, "train_steps_per_second": 3.949, "total_flos": 4586893730336448.0, "train_loss": 0.04373975196789051}

TRAIN_PROGRESS {"fold": 2, "seed": 4242, "epoch": 10.0, "step": 2900, "elapsed_minutes": 24.7, "average_steps_per_second": 1.957, "eval_loss": 0.12066857516765594, "eval_precision": 0.7388143176733781, "eval_recall": 0.7816568047337278, "eval_f1": 0.7596319723979298, "eval_accuracy": 0.9699856752885213, "eval_runtime": 13.334, "eval_samples_per_second": 182.466, "eval_steps_per_second": 11.474}
VALIDATION_TIME fold=2 seed=4242 seconds=27.63
    fold=2 seed=4242 | best_f1=0.7596 | eval_f1=0.7596 | 24.7 min

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 3/5 | train=600 docs / 9289 seqs | val=150 docs / 2424 seqs
  Seed 123...
TRAIN_START fold=3 seed=123 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 0.3436426116838488, "step": 100, "elapsed_minutes": 0.79, "average_steps_per_second": 2.117, "loss": 0.4606, "grad_norm": 1.2667609453201294, "learning_rate": 1.17989207435567e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 0.6872852233676976, "step": 200, "elapsed_minutes": 1.57, "average_steps_per_second": 2.13, "loss": 0.1195, "grad_norm": 1.783270001411438, "learning_rate": 2.3717022504725083e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=1.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 1.0, "step": 291, "elapsed_minutes": 2.49, "average_steps_per_second": 1.949, "eval_loss": 0.10656362771987915, "eval_precision": 0.5683244809270883, "eval_recall": 0.7370068879148404, "eval_f1": 0.6417666303162486, "eval_accuracy": 0.9601432740046191, "eval_runtime": 13.1612, "eval_samples_per_second": 184.178, "eval_steps_per_second": 11.549}
VALIDATION_TIME fold=3 seed=123 seconds=13.17
CHECKPOINT_TIME fold=3 seed=123 seconds=0.73
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 1.0309278350515463, "step": 300, "elapsed_minutes": 2.57, "average_steps_per_second": 1.945, "loss": 0.0996, "grad_norm": 0.6712161898612976, "learning_rate": 3.563512426589347e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 1.3745704467353952, "step": 400, "elapsed_minutes": 3.38, "average_steps_per_second": 1.973, "loss": 0.0751, "grad_norm": 1.3530364036560059, "learning_rate": 4.755322602706185e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 1.718213058419244, "step": 500, "elapsed_minutes": 4.15, "average_steps_per_second": 2.009, "loss": 0.0769, "grad_norm": 0.9518284201622009, "learning_rate": 5.9471327788230234e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=2.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 2.0, "step": 582, "elapsed_minutes": 4.98, "average_steps_per_second": 1.948, "eval_loss": 0.10141614824533463, "eval_precision": 0.6333870101986044, "eval_recall": 0.73888541014402, "eval_f1": 0.6820809248554913, "eval_accuracy": 0.9665878383050519, "eval_runtime": 12.9326, "eval_samples_per_second": 187.433, "eval_steps_per_second": 11.753}
VALIDATION_TIME fold=3 seed=123 seconds=12.93
CHECKPOINT_TIME fold=3 seed=123 seconds=0.73
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 2.0618556701030926, "step": 600, "elapsed_minutes": 5.12, "average_steps_per_second": 1.951, "loss": 0.0722, "grad_norm": 1.403264045715332, "learning_rate": 6.913823255006682e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 2.4054982817869415, "step": 700, "elapsed_minutes": 5.86, "average_steps_per_second": 1.989, "loss": 0.0457, "grad_norm": 0.692871630191803, "learning_rate": 6.781399902104811e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 2.7491408934707904, "step": 800, "elapsed_minutes": 6.66, "average_steps_per_second": 2.002, "loss": 0.0532, "grad_norm": 0.6115938425064087, "learning_rate": 6.648976549202939e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=3.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 3.0, "step": 873, "elapsed_minutes": 7.45, "average_steps_per_second": 1.953, "eval_loss": 0.11015363782644272, "eval_precision": 0.7064439140811456, "eval_recall": 0.741390106449593, "eval_f1": 0.723495264283532, "eval_accuracy": 0.9690633254504972, "eval_runtime": 12.9123, "eval_samples_per_second": 187.727, "eval_steps_per_second": 11.772}
VALIDATION_TIME fold=3 seed=123 seconds=12.91
CHECKPOINT_TIME fold=3 seed=123 seconds=0.75
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 3.0927835051546393, "step": 900, "elapsed_minutes": 7.66, "average_steps_per_second": 1.959, "loss": 0.0425, "grad_norm": 0.5291299819946289, "learning_rate": 6.516553196301069e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 3.436426116838488, "step": 1000, "elapsed_minutes": 8.45, "average_steps_per_second": 1.972, "loss": 0.0285, "grad_norm": 0.7831053137779236, "learning_rate": 6.384129843399197e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 3.7800687285223367, "step": 1100, "elapsed_minutes": 9.23, "average_steps_per_second": 1.987, "loss": 0.029, "grad_norm": 1.3591023683547974, "learning_rate": 6.251706490497327e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=4.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 4.0, "step": 1164, "elapsed_minutes": 9.93, "average_steps_per_second": 1.955, "eval_loss": 0.13486404716968536, "eval_precision": 0.7481389578163772, "eval_recall": 0.7551659361302442, "eval_f1": 0.7516360236833904, "eval_accuracy": 0.9705292563857888, "eval_runtime": 13.0009, "eval_samples_per_second": 186.449, "eval_steps_per_second": 11.692}
VALIDATION_TIME fold=3 seed=123 seconds=13.00
CHECKPOINT_TIME fold=3 seed=123 seconds=0.74
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 4.123711340206185, "step": 1200, "elapsed_minutes": 10.21, "average_steps_per_second": 1.96, "loss": 0.026, "grad_norm": 0.5357614755630493, "learning_rate": 6.119283137595456e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 4.4673539518900345, "step": 1300, "elapsed_minutes": 10.99, "average_steps_per_second": 1.972, "loss": 0.0157, "grad_norm": 0.7316164374351501, "learning_rate": 5.986859784693585e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 4.810996563573883, "step": 1400, "elapsed_minutes": 11.77, "average_steps_per_second": 1.983, "loss": 0.0191, "grad_norm": 0.5184276700019836, "learning_rate": 5.8544364317917137e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=5.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 5.0, "step": 1455, "elapsed_minutes": 12.4, "average_steps_per_second": 1.955, "eval_loss": 0.1199420914053917, "eval_precision": 0.7031161473087819, "eval_recall": 0.7770820288040076, "eval_f1": 0.738251041046996, "eval_accuracy": 0.9693122571187542, "eval_runtime": 12.985, "eval_samples_per_second": 186.677, "eval_steps_per_second": 11.706}
VALIDATION_TIME fold=3 seed=123 seconds=12.99
CHECKPOINT_TIME fold=3 seed=123 seconds=0.71
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 5.154639175257732, "step": 1500, "elapsed_minutes": 12.78, "average_steps_per_second": 1.957, "loss": 0.0148, "grad_norm": 0.9330664277076721, "learning_rate": 5.7220130788898427e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 5.498281786941581, "step": 1600, "elapsed_minutes": 13.52, "average_steps_per_second": 1.973, "loss": 0.0109, "grad_norm": 0.4157769978046417, "learning_rate": 5.589589725987972e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 5.841924398625429, "step": 1700, "elapsed_minutes": 14.32, "average_steps_per_second": 1.978, "loss": 0.0133, "grad_norm": 0.3812254071235657, "learning_rate": 5.457166373086101e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=6.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 6.0, "step": 1746, "elapsed_minutes": 14.88, "average_steps_per_second": 1.956, "eval_loss": 0.14314985275268555, "eval_precision": 0.6863611264494754, "eval_recall": 0.778334376956794, "eval_f1": 0.7294600938967136, "eval_accuracy": 0.968316530445726, "eval_runtime": 12.7294, "eval_samples_per_second": 190.425, "eval_steps_per_second": 11.941}
VALIDATION_TIME fold=3 seed=123 seconds=12.73
CHECKPOINT_TIME fold=3 seed=123 seconds=0.79
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 6.185567010309279, "step": 1800, "elapsed_minutes": 15.32, "average_steps_per_second": 1.958, "loss": 0.0086, "grad_norm": 0.012914595194160938, "learning_rate": 5.32474302018423e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 6.529209621993127, "step": 1900, "elapsed_minutes": 16.07, "average_steps_per_second": 1.971, "loss": 0.0087, "grad_norm": 0.814295768737793, "learning_rate": 5.192319667282359e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 6.872852233676976, "step": 2000, "elapsed_minutes": 16.86, "average_steps_per_second": 1.978, "loss": 0.0084, "grad_norm": 0.1316109001636505, "learning_rate": 5.059896314380488e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=7.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 7.0, "step": 2037, "elapsed_minutes": 17.34, "average_steps_per_second": 1.958, "eval_loss": 0.14933575689792633, "eval_precision": 0.7150997150997151, "eval_recall": 0.7858484658735129, "eval_f1": 0.7488066825775656, "eval_accuracy": 0.9704186200887857, "eval_runtime": 12.7066, "eval_samples_per_second": 190.767, "eval_steps_per_second": 11.962}
VALIDATION_TIME fold=3 seed=123 seconds=12.71
CHECKPOINT_TIME fold=3 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 7.216494845360825, "step": 2100, "elapsed_minutes": 17.83, "average_steps_per_second": 1.963, "loss": 0.0067, "grad_norm": 0.19904030859470367, "learning_rate": 4.927472961478617e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 7.560137457044673, "step": 2200, "elapsed_minutes": 18.63, "average_steps_per_second": 1.968, "loss": 0.0072, "grad_norm": 0.5078030228614807, "learning_rate": 4.795049608576746e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 7.903780068728523, "step": 2300, "elapsed_minutes": 19.37, "average_steps_per_second": 1.979, "loss": 0.0076, "grad_norm": 0.08391159027814865, "learning_rate": 4.662626255674876e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=8.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 8.0, "step": 2328, "elapsed_minutes": 19.82, "average_steps_per_second": 1.958, "eval_loss": 0.16305318474769592, "eval_precision": 0.7107674684994273, "eval_recall": 0.7770820288040076, "eval_f1": 0.7424469039784625, "eval_accuracy": 0.9700175635121493, "eval_runtime": 12.8335, "eval_samples_per_second": 188.88, "eval_steps_per_second": 11.844}
VALIDATION_TIME fold=3 seed=123 seconds=12.84
CHECKPOINT_TIME fold=3 seed=123 seconds=0.71
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 8.24742268041237, "step": 2400, "elapsed_minutes": 20.39, "average_steps_per_second": 1.962, "loss": 0.005, "grad_norm": 0.632905900478363, "learning_rate": 4.530202902773005e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 8.59106529209622, "step": 2500, "elapsed_minutes": 21.17, "average_steps_per_second": 1.969, "loss": 0.0042, "grad_norm": 0.17059114575386047, "learning_rate": 4.397779549871133e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 8.934707903780069, "step": 2600, "elapsed_minutes": 21.94, "average_steps_per_second": 1.975, "loss": 0.0036, "grad_norm": 0.03883281350135803, "learning_rate": 4.265356196969263e-05}
EPOCH_TRAIN_END fold=3 seed=123 epoch=9.00
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 9.0, "step": 2619, "elapsed_minutes": 22.3, "average_steps_per_second": 1.958, "eval_loss": 0.16887083649635315, "eval_precision": 0.6987681970884658, "eval_recall": 0.7814652473387602, "eval_f1": 0.7378066804611292, "eval_accuracy": 0.9700452225864, "eval_runtime": 12.7198, "eval_samples_per_second": 190.569, "eval_steps_per_second": 11.95}
VALIDATION_TIME fold=3 seed=123 seconds=12.72
CHECKPOINT_TIME fold=3 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 9.0, "step": 2619, "elapsed_minutes": 22.31, "average_steps_per_second": 1.956, "train_runtime": 1338.6231, "train_samples_per_second": 138.784, "train_steps_per_second": 4.348, "total_flos": 4243105745570304.0, "train_loss": 0.04826790460788279}

TRAIN_PROGRESS {"fold": 3, "seed": 123, "epoch": 9.0, "step": 2619, "elapsed_minutes": 22.52, "average_steps_per_second": 1.938, "eval_loss": 0.13486404716968536, "eval_precision": 0.7481389578163772, "eval_recall": 0.7551659361302442, "eval_f1": 0.7516360236833904, "eval_accuracy": 0.9705292563857888, "eval_runtime": 12.7799, "eval_samples_per_second": 189.672, "eval_steps_per_second": 11.894}
VALIDATION_TIME fold=3 seed=123 seconds=26.35
    fold=3 seed=123 | best_f1=0.7516 | eval_f1=0.7516 | 22.5 min

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  Seed 4242...
TRAIN_START fold=3 seed=4242 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 0.3436426116838488, "step": 100, "elapsed_minutes": 0.79, "average_steps_per_second": 2.119, "loss": 0.4706, "grad_norm": 1.030848503112793, "learning_rate": 1.17989207435567e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 0.6872852233676976, "step": 200, "elapsed_minutes": 1.57, "average_steps_per_second": 2.118, "loss": 0.1158, "grad_norm": 1.0826343297958374, "learning_rate": 2.3717022504725083e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=1.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 1.0, "step": 291, "elapsed_minutes": 2.46, "average_steps_per_second": 1.972, "eval_loss": 0.09658046066761017, "eval_precision": 0.6520947176684881, "eval_recall": 0.6725109580463369, "eval_f1": 0.6621454993834772, "eval_accuracy": 0.9657857251517792, "eval_runtime": 12.9594, "eval_samples_per_second": 187.046, "eval_steps_per_second": 11.729}
VALIDATION_TIME fold=3 seed=4242 seconds=12.97
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 1.0309278350515463, "step": 300, "elapsed_minutes": 2.53, "average_steps_per_second": 1.976, "loss": 0.0995, "grad_norm": 0.9347650408744812, "learning_rate": 3.563512426589347e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 1.3745704467353952, "step": 400, "elapsed_minutes": 3.28, "average_steps_per_second": 2.033, "loss": 0.0773, "grad_norm": 0.987438976764679, "learning_rate": 4.755322602706185e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 1.718213058419244, "step": 500, "elapsed_minutes": 4.07, "average_steps_per_second": 2.049, "loss": 0.0768, "grad_norm": 0.6673002243041992, "learning_rate": 5.9471327788230234e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=2.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 2.0, "step": 582, "elapsed_minutes": 4.96, "average_steps_per_second": 1.956, "eval_loss": 0.09623368084430695, "eval_precision": 0.6101882613510521, "eval_recall": 0.6900438321853475, "eval_f1": 0.6476638260358507, "eval_accuracy": 0.9652187141296381, "eval_runtime": 12.6911, "eval_samples_per_second": 191.0, "eval_steps_per_second": 11.977}
VALIDATION_TIME fold=3 seed=4242 seconds=12.69
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 2.0618556701030926, "step": 600, "elapsed_minutes": 5.1, "average_steps_per_second": 1.96, "loss": 0.0743, "grad_norm": 0.48116105794906616, "learning_rate": 6.913823255006682e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 2.4054982817869415, "step": 700, "elapsed_minutes": 5.85, "average_steps_per_second": 1.995, "loss": 0.0492, "grad_norm": 0.9244323968887329, "learning_rate": 6.781399902104811e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 2.7491408934707904, "step": 800, "elapsed_minutes": 6.65, "average_steps_per_second": 2.005, "loss": 0.05, "grad_norm": 0.9151610136032104, "learning_rate": 6.648976549202939e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=3.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 3.0, "step": 873, "elapsed_minutes": 7.46, "average_steps_per_second": 1.952, "eval_loss": 0.10837100446224213, "eval_precision": 0.716636197440585, "eval_recall": 0.736380713838447, "eval_f1": 0.7263743051266214, "eval_accuracy": 0.9695335297127605, "eval_runtime": 12.8112, "eval_samples_per_second": 189.209, "eval_steps_per_second": 11.865}
VALIDATION_TIME fold=3 seed=4242 seconds=12.81
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.79
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 3.0927835051546393, "step": 900, "elapsed_minutes": 7.67, "average_steps_per_second": 1.955, "loss": 0.0421, "grad_norm": 0.9537520408630371, "learning_rate": 6.516553196301069e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 3.436426116838488, "step": 1000, "elapsed_minutes": 8.47, "average_steps_per_second": 1.967, "loss": 0.0301, "grad_norm": 1.6194745302200317, "learning_rate": 6.384129843399197e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 3.7800687285223367, "step": 1100, "elapsed_minutes": 9.28, "average_steps_per_second": 1.977, "loss": 0.03, "grad_norm": 0.9081982970237732, "learning_rate": 6.251706490497327e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=4.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 4.0, "step": 1164, "elapsed_minutes": 9.98, "average_steps_per_second": 1.944, "eval_loss": 0.12123684585094452, "eval_precision": 0.648975302154493, "eval_recall": 0.7733249843456481, "eval_f1": 0.7057142857142857, "eval_accuracy": 0.9662420998769171, "eval_runtime": 12.746, "eval_samples_per_second": 190.177, "eval_steps_per_second": 11.925}
VALIDATION_TIME fold=3 seed=4242 seconds=12.75
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 4.123711340206185, "step": 1200, "elapsed_minutes": 10.3, "average_steps_per_second": 1.942, "loss": 0.024, "grad_norm": 0.23554158210754395, "learning_rate": 6.119283137595456e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 4.4673539518900345, "step": 1300, "elapsed_minutes": 11.07, "average_steps_per_second": 1.958, "loss": 0.0152, "grad_norm": 0.7466483116149902, "learning_rate": 5.986859784693585e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 4.810996563573883, "step": 1400, "elapsed_minutes": 11.86, "average_steps_per_second": 1.968, "loss": 0.0185, "grad_norm": 0.7795018553733826, "learning_rate": 5.8544364317917137e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=5.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 5.0, "step": 1455, "elapsed_minutes": 12.48, "average_steps_per_second": 1.944, "eval_loss": 0.1363748162984848, "eval_precision": 0.6789444749862562, "eval_recall": 0.7733249843456481, "eval_f1": 0.7230679156908666, "eval_accuracy": 0.9684824848912307, "eval_runtime": 12.7372, "eval_samples_per_second": 190.309, "eval_steps_per_second": 11.934}
VALIDATION_TIME fold=3 seed=4242 seconds=12.74
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.70
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 5.154639175257732, "step": 1500, "elapsed_minutes": 12.81, "average_steps_per_second": 1.951, "loss": 0.0158, "grad_norm": 0.7573631405830383, "learning_rate": 5.7220130788898427e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 5.498281786941581, "step": 1600, "elapsed_minutes": 13.6, "average_steps_per_second": 1.96, "loss": 0.0127, "grad_norm": 0.36077630519866943, "learning_rate": 5.589589725987972e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 5.841924398625429, "step": 1700, "elapsed_minutes": 14.38, "average_steps_per_second": 1.971, "loss": 0.0121, "grad_norm": 0.21161103248596191, "learning_rate": 5.457166373086101e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=6.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 6.0, "step": 1746, "elapsed_minutes": 14.94, "average_steps_per_second": 1.947, "eval_loss": 0.13485267758369446, "eval_precision": 0.723826714801444, "eval_recall": 0.7532874139010645, "eval_f1": 0.7382632709420067, "eval_accuracy": 0.9694505524900081, "eval_runtime": 12.8272, "eval_samples_per_second": 188.973, "eval_steps_per_second": 11.85}
VALIDATION_TIME fold=3 seed=4242 seconds=12.83
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.73
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 6.185567010309279, "step": 1800, "elapsed_minutes": 15.36, "average_steps_per_second": 1.953, "loss": 0.0095, "grad_norm": 0.4300585389137268, "learning_rate": 5.32474302018423e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 6.529209621993127, "step": 1900, "elapsed_minutes": 16.13, "average_steps_per_second": 1.963, "loss": 0.0092, "grad_norm": 1.2507925033569336, "learning_rate": 5.192319667282359e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 6.872852233676976, "step": 2000, "elapsed_minutes": 16.93, "average_steps_per_second": 1.969, "loss": 0.0084, "grad_norm": 1.7681217193603516, "learning_rate": 5.059896314380488e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=7.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 7.0, "step": 2037, "elapsed_minutes": 17.43, "average_steps_per_second": 1.948, "eval_loss": 0.1513901799917221, "eval_precision": 0.7406716417910447, "eval_recall": 0.7457733249843457, "eval_f1": 0.7432137285491419, "eval_accuracy": 0.9701281998091524, "eval_runtime": 12.7574, "eval_samples_per_second": 190.007, "eval_steps_per_second": 11.915}
VALIDATION_TIME fold=3 seed=4242 seconds=12.76
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 7.216494845360825, "step": 2100, "elapsed_minutes": 17.92, "average_steps_per_second": 1.953, "loss": 0.0061, "grad_norm": 3.10840106010437, "learning_rate": 4.927472961478617e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 7.560137457044673, "step": 2200, "elapsed_minutes": 18.73, "average_steps_per_second": 1.958, "loss": 0.0047, "grad_norm": 0.4947972297668457, "learning_rate": 4.795049608576746e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 7.903780068728523, "step": 2300, "elapsed_minutes": 19.49, "average_steps_per_second": 1.966, "loss": 0.008, "grad_norm": 0.31272029876708984, "learning_rate": 4.662626255674876e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=8.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 8.0, "step": 2328, "elapsed_minutes": 19.91, "average_steps_per_second": 1.948, "eval_loss": 0.1674923598766327, "eval_precision": 0.7155272305909618, "eval_recall": 0.7733249843456481, "eval_f1": 0.7433042431537767, "eval_accuracy": 0.9693952343415065, "eval_runtime": 12.807, "eval_samples_per_second": 189.272, "eval_steps_per_second": 11.869}
VALIDATION_TIME fold=3 seed=4242 seconds=12.81
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.70
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 8.24742268041237, "step": 2400, "elapsed_minutes": 20.49, "average_steps_per_second": 1.952, "loss": 0.005, "grad_norm": 6.043325901031494, "learning_rate": 4.530202902773005e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 8.59106529209622, "step": 2500, "elapsed_minutes": 21.27, "average_steps_per_second": 1.959, "loss": 0.0042, "grad_norm": 0.006043415982276201, "learning_rate": 4.397779549871133e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 8.934707903780069, "step": 2600, "elapsed_minutes": 22.06, "average_steps_per_second": 1.965, "loss": 0.0038, "grad_norm": 0.003934565465897322, "learning_rate": 4.265356196969263e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=9.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 9.0, "step": 2619, "elapsed_minutes": 22.4, "average_steps_per_second": 1.949, "eval_loss": 0.17715297639369965, "eval_precision": 0.7305882352941176, "eval_recall": 0.7777082028804008, "eval_f1": 0.7534121929026387, "eval_accuracy": 0.9707643585169204, "eval_runtime": 12.7839, "eval_samples_per_second": 189.614, "eval_steps_per_second": 11.89}
VALIDATION_TIME fold=3 seed=4242 seconds=12.79
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 9.278350515463918, "step": 2700, "elapsed_minutes": 23.01, "average_steps_per_second": 1.956, "loss": 0.0044, "grad_norm": 0.2051057666540146, "learning_rate": 4.132932844067392e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 9.621993127147766, "step": 2800, "elapsed_minutes": 23.74, "average_steps_per_second": 1.965, "loss": 0.0047, "grad_norm": 2.0109894275665283, "learning_rate": 4.00050949116552e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 9.965635738831615, "step": 2900, "elapsed_minutes": 24.58, "average_steps_per_second": 1.967, "loss": 0.0036, "grad_norm": 0.21335630118846893, "learning_rate": 3.86808613826365e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=10.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 10.0, "step": 2910, "elapsed_minutes": 24.86, "average_steps_per_second": 1.951, "eval_loss": 0.18476520478725433, "eval_precision": 0.7444444444444445, "eval_recall": 0.7551659361302442, "eval_f1": 0.7497668635374573, "eval_accuracy": 0.9699345862893969, "eval_runtime": 12.799, "eval_samples_per_second": 189.39, "eval_steps_per_second": 11.876}
VALIDATION_TIME fold=3 seed=4242 seconds=12.80
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 10.309278350515465, "step": 3000, "elapsed_minutes": 25.58, "average_steps_per_second": 1.954, "loss": 0.0025, "grad_norm": 0.011841151863336563, "learning_rate": 3.735662785361779e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 10.652920962199312, "step": 3100, "elapsed_minutes": 26.33, "average_steps_per_second": 1.962, "loss": 0.0031, "grad_norm": 0.14642098546028137, "learning_rate": 3.6032394324599086e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 10.996563573883162, "step": 3200, "elapsed_minutes": 27.12, "average_steps_per_second": 1.966, "loss": 0.0023, "grad_norm": 0.4866301417350769, "learning_rate": 3.470816079558037e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=11.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 11.0, "step": 3201, "elapsed_minutes": 27.34, "average_steps_per_second": 1.951, "eval_loss": 0.1959109902381897, "eval_precision": 0.7339393939393939, "eval_recall": 0.7582968065122104, "eval_f1": 0.74591931013243, "eval_accuracy": 0.9693122571187542, "eval_runtime": 12.8955, "eval_samples_per_second": 187.972, "eval_steps_per_second": 11.787}
VALIDATION_TIME fold=3 seed=4242 seconds=12.90
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 11.34020618556701, "step": 3300, "elapsed_minutes": 28.13, "average_steps_per_second": 1.955, "loss": 0.0021, "grad_norm": 0.5343355536460876, "learning_rate": 3.338392726656166e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 11.683848797250858, "step": 3400, "elapsed_minutes": 28.9, "average_steps_per_second": 1.961, "loss": 0.0023, "grad_norm": 0.03544367477297783, "learning_rate": 3.2059693737542956e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=12.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 12.0, "step": 3492, "elapsed_minutes": 29.83, "average_steps_per_second": 1.951, "eval_loss": 0.1776067316532135, "eval_precision": 0.7465214761040533, "eval_recall": 0.7726988102692548, "eval_f1": 0.7593846153846153, "eval_accuracy": 0.971594130744444, "eval_runtime": 12.7649, "eval_samples_per_second": 189.896, "eval_steps_per_second": 11.908}
VALIDATION_TIME fold=3 seed=4242 seconds=12.77
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 12.027491408934708, "step": 3500, "elapsed_minutes": 29.9, "average_steps_per_second": 1.951, "loss": 0.0017, "grad_norm": 0.007659809198230505, "learning_rate": 3.0735460208524246e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 12.371134020618557, "step": 3600, "elapsed_minutes": 30.66, "average_steps_per_second": 1.957, "loss": 0.0017, "grad_norm": 0.7740052342414856, "learning_rate": 2.9411226679505533e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 12.714776632302405, "step": 3700, "elapsed_minutes": 31.41, "average_steps_per_second": 1.963, "loss": 0.0013, "grad_norm": 0.07728003710508347, "learning_rate": 2.8086993150486826e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=13.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 13.0, "step": 3783, "elapsed_minutes": 32.31, "average_steps_per_second": 1.952, "eval_loss": 0.20287619531154633, "eval_precision": 0.760178117048346, "eval_recall": 0.7482780212899186, "eval_f1": 0.7541811296939098, "eval_accuracy": 0.9712622218534346, "eval_runtime": 12.8042, "eval_samples_per_second": 189.313, "eval_steps_per_second": 11.871}
VALIDATION_TIME fold=3 seed=4242 seconds=12.81
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 13.058419243986254, "step": 3800, "elapsed_minutes": 32.43, "average_steps_per_second": 1.953, "loss": 0.0016, "grad_norm": 0.018848881125450134, "learning_rate": 2.6762759621468116e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 13.402061855670103, "step": 3900, "elapsed_minutes": 33.19, "average_steps_per_second": 1.959, "loss": 0.0006, "grad_norm": 0.8375760912895203, "learning_rate": 2.5438526092449406e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 13.745704467353953, "step": 4000, "elapsed_minutes": 33.98, "average_steps_per_second": 1.962, "loss": 0.0008, "grad_norm": 0.04033469036221504, "learning_rate": 2.4114292563430696e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=14.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 14.0, "step": 4074, "elapsed_minutes": 34.78, "average_steps_per_second": 1.952, "eval_loss": 0.20831914246082306, "eval_precision": 0.7544615384615385, "eval_recall": 0.7676894176581089, "eval_f1": 0.7610180012414649, "eval_accuracy": 0.9709303129624252, "eval_runtime": 12.8053, "eval_samples_per_second": 189.296, "eval_steps_per_second": 11.87}
VALIDATION_TIME fold=3 seed=4242 seconds=12.81
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 14.0893470790378, "step": 4100, "elapsed_minutes": 35.0, "average_steps_per_second": 1.953, "loss": 0.0009, "grad_norm": 0.6275327205657959, "learning_rate": 2.279005903441199e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 14.43298969072165, "step": 4200, "elapsed_minutes": 35.76, "average_steps_per_second": 1.957, "loss": 0.0009, "grad_norm": 0.015533733181655407, "learning_rate": 2.146582550539328e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 14.776632302405499, "step": 4300, "elapsed_minutes": 36.54, "average_steps_per_second": 1.961, "loss": 0.0005, "grad_norm": 0.001955557381734252, "learning_rate": 2.014159197637457e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=15.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 15.0, "step": 4365, "elapsed_minutes": 37.24, "average_steps_per_second": 1.953, "eval_loss": 0.2152397185564041, "eval_precision": 0.748451053283767, "eval_recall": 0.7564182842830307, "eval_f1": 0.7524135783245094, "eval_accuracy": 0.9705845745342904, "eval_runtime": 12.808, "eval_samples_per_second": 189.256, "eval_steps_per_second": 11.868}
VALIDATION_TIME fold=3 seed=4242 seconds=12.81
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 15.120274914089347, "step": 4400, "elapsed_minutes": 37.53, "average_steps_per_second": 1.954, "loss": 0.0004, "grad_norm": 0.0017978152027353644, "learning_rate": 1.881735844735586e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 15.463917525773196, "step": 4500, "elapsed_minutes": 38.27, "average_steps_per_second": 1.96, "loss": 0.0006, "grad_norm": 0.0011094713117927313, "learning_rate": 1.749312491833715e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 15.807560137457045, "step": 4600, "elapsed_minutes": 39.06, "average_steps_per_second": 1.963, "loss": 0.0009, "grad_norm": 0.0039296564646065235, "learning_rate": 1.6168891389318442e-05}
EPOCH_TRAIN_END fold=3 seed=4242 epoch=16.00
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 16.0, "step": 4656, "elapsed_minutes": 39.72, "average_steps_per_second": 1.954, "eval_loss": 0.22923757135868073, "eval_precision": 0.7481796116504854, "eval_recall": 0.7720726361928616, "eval_f1": 0.7599383667180277, "eval_accuracy": 0.9703218133289079, "eval_runtime": 12.8079, "eval_samples_per_second": 189.258, "eval_steps_per_second": 11.868}
VALIDATION_TIME fold=3 seed=4242 seconds=12.81
CHECKPOINT_TIME fold=3 seed=4242 seconds=0.70
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 16.151202749140893, "step": 4700, "elapsed_minutes": 40.08, "average_steps_per_second": 1.955, "loss": 0.0005, "grad_norm": 0.016687709838151932, "learning_rate": 1.4844657860299732e-05}
TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 16.49484536082474, "step": 4800, "elapsed_minutes": 40.88, "average_steps_per_second": 1.957, "loss": 0.0006, "grad_norm": 0.0427875816822052, "learning_rate": 1.3520424331281022e-05}

TRAIN_PROGRESS {"fold": 3, "seed": 4242, "epoch": 20.0, "step": 5820, "elapsed_minutes": 49.89, "average_steps_per_second": 1.944, "eval_loss": 0.22379930317401886, "eval_precision": 0.7524271844660194, "eval_recall": 0.7764558547276142, "eval_f1": 0.7642526964560863, "eval_accuracy": 0.9709026538881743, "eval_runtime": 12.8586, "eval_samples_per_second": 188.511, "eval_steps_per_second": 11.821}
VALIDATION_TIME fold=3 seed=4242 seconds=26.56
    fold=3 seed=4242 | best_f1=0.7643 | eval_f1=0.7643 | 49.9 min

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 4/5 | train=600 docs / 9400 seqs | val=150 docs / 2313 seqs
  Seed 123...
TRAIN_START fold=4 seed=123 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 0.3401360544217687, "step": 100, "elapsed_minutes": 0.77, "average_steps_per_second": 2.154, "loss": 0.4592, "grad_norm": 1.4072588682174683, "learning_rate": 1.1678523593112244e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 0.6802721088435374, "step": 200, "elapsed_minutes": 1.55, "average_steps_per_second": 2.152, "loss": 0.1198, "grad_norm": 1.052220344543457, "learning_rate": 2.3475012071003398e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=1.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 1.0, "step": 294, "elapsed_minutes": 2.46, "average_steps_per_second": 1.996, "eval_loss": 0.08891808241605759, "eval_precision": 0.656128674431503, "eval_recall": 0.7426239799121155, "eval_f1": 0.6967020023557126, "eval_accuracy": 0.9680429710813304, "eval_runtime": 12.738, "eval_samples_per_second": 181.583, "eval_steps_per_second": 11.383}
VALIDATION_TIME fold=4 seed=123 seconds=12.74
CHECKPOINT_TIME fold=4 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 1.0204081632653061, "step": 300, "elapsed_minutes": 2.52, "average_steps_per_second": 1.986, "loss": 0.1045, "grad_norm": 0.8354362845420837, "learning_rate": 3.527150054889455e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 1.3605442176870748, "step": 400, "elapsed_minutes": 3.28, "average_steps_per_second": 2.035, "loss": 0.0834, "grad_norm": 2.9987409114837646, "learning_rate": 4.706798902678571e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 1.7006802721088436, "step": 500, "elapsed_minutes": 4.05, "average_steps_per_second": 2.059, "loss": 0.0754, "grad_norm": 1.8270736932754517, "learning_rate": 5.886447750467687e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=2.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 2.0, "step": 588, "elapsed_minutes": 4.92, "average_steps_per_second": 1.991, "eval_loss": 0.09067057073116302, "eval_precision": 0.696875, "eval_recall": 0.6999372253609542, "eval_f1": 0.6984027560288131, "eval_accuracy": 0.9697656122836525, "eval_runtime": 13.4521, "eval_samples_per_second": 171.944, "eval_steps_per_second": 10.779}
VALIDATION_TIME fold=4 seed=123 seconds=13.45
CHECKPOINT_TIME fold=4 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 2.0408163265306123, "step": 600, "elapsed_minutes": 5.03, "average_steps_per_second": 1.99, "loss": 0.0816, "grad_norm": 0.9799578189849854, "learning_rate": 6.921917294638133e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 2.380952380952381, "step": 700, "elapsed_minutes": 5.78, "average_steps_per_second": 2.018, "loss": 0.0475, "grad_norm": 0.6930328607559204, "learning_rate": 6.790845200439342e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 2.7210884353741496, "step": 800, "elapsed_minutes": 6.54, "average_steps_per_second": 2.038, "loss": 0.0554, "grad_norm": 0.6015167236328125, "learning_rate": 6.659773106240552e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=3.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 3.0, "step": 882, "elapsed_minutes": 7.39, "average_steps_per_second": 1.989, "eval_loss": 0.10887033492326736, "eval_precision": 0.757498404594767, "eval_recall": 0.7451349654739485, "eval_f1": 0.75126582278481, "eval_accuracy": 0.9719629971244099, "eval_runtime": 12.665, "eval_samples_per_second": 182.629, "eval_steps_per_second": 11.449}
VALIDATION_TIME fold=4 seed=123 seconds=12.67
CHECKPOINT_TIME fold=4 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 3.061224489795918, "step": 900, "elapsed_minutes": 7.55, "average_steps_per_second": 1.987, "loss": 0.0444, "grad_norm": 0.7423602938652039, "learning_rate": 6.52870101204176e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 3.4013605442176873, "step": 1000, "elapsed_minutes": 8.31, "average_steps_per_second": 2.005, "loss": 0.0279, "grad_norm": 0.355763703584671, "learning_rate": 6.39762891784297e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 3.741496598639456, "step": 1100, "elapsed_minutes": 9.06, "average_steps_per_second": 2.024, "loss": 0.0319, "grad_norm": 1.9559799432754517, "learning_rate": 6.26655682364418e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=4.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 4.0, "step": 1176, "elapsed_minutes": 9.85, "average_steps_per_second": 1.99, "eval_loss": 0.11578631401062012, "eval_precision": 0.7392638036809815, "eval_recall": 0.7564344005021971, "eval_f1": 0.7477505429723859, "eval_accuracy": 0.9710270739514948, "eval_runtime": 12.664, "eval_samples_per_second": 182.644, "eval_steps_per_second": 11.45}
VALIDATION_TIME fold=4 seed=123 seconds=12.67
CHECKPOINT_TIME fold=4 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 4.081632653061225, "step": 1200, "elapsed_minutes": 10.04, "average_steps_per_second": 1.992, "loss": 0.0286, "grad_norm": 0.3558206558227539, "learning_rate": 6.135484729445389e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 4.421768707482993, "step": 1300, "elapsed_minutes": 10.8, "average_steps_per_second": 2.006, "loss": 0.0187, "grad_norm": 0.43709513545036316, "learning_rate": 6.004412635246598e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 4.761904761904762, "step": 1400, "elapsed_minutes": 11.56, "average_steps_per_second": 2.018, "loss": 0.0172, "grad_norm": 0.5492061972618103, "learning_rate": 5.873340541047807e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=5.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 5.0, "step": 1470, "elapsed_minutes": 12.31, "average_steps_per_second": 1.99, "eval_loss": 0.11424646526575089, "eval_precision": 0.7059477487493052, "eval_recall": 0.7972379158819837, "eval_f1": 0.7488207547169812, "eval_accuracy": 0.9694807661005914, "eval_runtime": 12.7325, "eval_samples_per_second": 181.661, "eval_steps_per_second": 11.388}
VALIDATION_TIME fold=4 seed=123 seconds=12.73
CHECKPOINT_TIME fold=4 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 5.1020408163265305, "step": 1500, "elapsed_minutes": 12.57, "average_steps_per_second": 1.99, "loss": 0.0169, "grad_norm": 0.08947557210922241, "learning_rate": 5.742268446849017e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 5.442176870748299, "step": 1600, "elapsed_minutes": 13.3, "average_steps_per_second": 2.006, "loss": 0.0104, "grad_norm": 0.11698150634765625, "learning_rate": 5.611196352650226e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 5.782312925170068, "step": 1700, "elapsed_minutes": 14.03, "average_steps_per_second": 2.019, "loss": 0.0106, "grad_norm": 0.4589565694332123, "learning_rate": 5.480124258451435e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=6.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 6.0, "step": 1764, "elapsed_minutes": 14.76, "average_steps_per_second": 1.992, "eval_loss": 0.14148028194904327, "eval_precision": 0.7322053675612602, "eval_recall": 0.7878217200251099, "eval_f1": 0.7589960689446629, "eval_accuracy": 0.9717866637729912, "eval_runtime": 13.221, "eval_samples_per_second": 174.949, "eval_steps_per_second": 10.967}
VALIDATION_TIME fold=4 seed=123 seconds=13.22
CHECKPOINT_TIME fold=4 seed=123 seconds=0.72
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 6.122448979591836, "step": 1800, "elapsed_minutes": 15.06, "average_steps_per_second": 1.992, "loss": 0.0107, "grad_norm": 0.929110050201416, "learning_rate": 5.3490521642526454e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 6.462585034013605, "step": 1900, "elapsed_minutes": 15.8, "average_steps_per_second": 2.004, "loss": 0.0078, "grad_norm": 0.23099437355995178, "learning_rate": 5.217980070053855e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 6.802721088435375, "step": 2000, "elapsed_minutes": 16.56, "average_steps_per_second": 2.013, "loss": 0.0087, "grad_norm": 0.3287977874279022, "learning_rate": 5.086907975855064e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=7.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 7.0, "step": 2058, "elapsed_minutes": 17.22, "average_steps_per_second": 1.992, "eval_loss": 0.1871918886899948, "eval_precision": 0.6801310043668122, "eval_recall": 0.7821720025109855, "eval_f1": 0.7275912408759123, "eval_accuracy": 0.9642314578698931, "eval_runtime": 12.8459, "eval_samples_per_second": 180.057, "eval_steps_per_second": 11.288}
VALIDATION_TIME fold=4 seed=123 seconds=12.85
CHECKPOINT_TIME fold=4 seed=123 seconds=0.66
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 7.142857142857143, "step": 2100, "elapsed_minutes": 17.54, "average_steps_per_second": 1.996, "loss": 0.0104, "grad_norm": 0.2668541669845581, "learning_rate": 4.9558358816562734e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 7.482993197278912, "step": 2200, "elapsed_minutes": 18.29, "average_steps_per_second": 2.005, "loss": 0.0073, "grad_norm": 0.1577550321817398, "learning_rate": 4.824763787457483e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 7.8231292517006805, "step": 2300, "elapsed_minutes": 19.07, "average_steps_per_second": 2.01, "loss": 0.0066, "grad_norm": 0.828745424747467, "learning_rate": 4.693691693258692e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=8.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 8.0, "step": 2352, "elapsed_minutes": 19.67, "average_steps_per_second": 1.993, "eval_loss": 0.16192534565925598, "eval_precision": 0.7131474103585658, "eval_recall": 0.7865662272441933, "eval_f1": 0.7480597014925374, "eval_accuracy": 0.9688839455265585, "eval_runtime": 12.7112, "eval_samples_per_second": 181.966, "eval_steps_per_second": 11.407}
VALIDATION_TIME fold=4 seed=123 seconds=12.71
CHECKPOINT_TIME fold=4 seed=123 seconds=0.71
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 8.16326530612245, "step": 2400, "elapsed_minutes": 20.03, "average_steps_per_second": 1.997, "loss": 0.0057, "grad_norm": 0.10733628273010254, "learning_rate": 4.5626195990599014e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 8.503401360544217, "step": 2500, "elapsed_minutes": 20.79, "average_steps_per_second": 2.004, "loss": 0.007, "grad_norm": 0.5636844635009766, "learning_rate": 4.43154750486111e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 8.843537414965986, "step": 2600, "elapsed_minutes": 21.56, "average_steps_per_second": 2.01, "loss": 0.0049, "grad_norm": 0.9111226797103882, "learning_rate": 4.30047541066232e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=9.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 9.0, "step": 2646, "elapsed_minutes": 22.12, "average_steps_per_second": 1.994, "eval_loss": 0.16091814637184143, "eval_precision": 0.7519902020820576, "eval_recall": 0.770872567482737, "eval_f1": 0.7613143211407317, "eval_accuracy": 0.970945689327763, "eval_runtime": 12.6861, "eval_samples_per_second": 182.325, "eval_steps_per_second": 11.43}
VALIDATION_TIME fold=4 seed=123 seconds=12.69
CHECKPOINT_TIME fold=4 seed=123 seconds=0.71
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 9.183673469387756, "step": 2700, "elapsed_minutes": 22.54, "average_steps_per_second": 1.997, "loss": 0.0039, "grad_norm": 0.46924471855163574, "learning_rate": 4.1694033164635295e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 9.523809523809524, "step": 2800, "elapsed_minutes": 23.3, "average_steps_per_second": 2.003, "loss": 0.0034, "grad_norm": 0.6356519460678101, "learning_rate": 4.0383312222647384e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 9.863945578231293, "step": 2900, "elapsed_minutes": 24.07, "average_steps_per_second": 2.008, "loss": 0.0039, "grad_norm": 0.24601642787456512, "learning_rate": 3.9072591280659486e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=10.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 10.0, "step": 2940, "elapsed_minutes": 24.58, "average_steps_per_second": 1.993, "eval_loss": 0.14724674820899963, "eval_precision": 0.7297297297297297, "eval_recall": 0.7966101694915254, "eval_f1": 0.7617046818727491, "eval_accuracy": 0.9728717920894145, "eval_runtime": 12.8877, "eval_samples_per_second": 179.474, "eval_steps_per_second": 11.251}
VALIDATION_TIME fold=4 seed=123 seconds=12.89
CHECKPOINT_TIME fold=4 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 10.204081632653061, "step": 3000, "elapsed_minutes": 25.04, "average_steps_per_second": 1.997, "loss": 0.003, "grad_norm": 0.08904246985912323, "learning_rate": 3.776187033867158e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 10.54421768707483, "step": 3100, "elapsed_minutes": 25.82, "average_steps_per_second": 2.001, "loss": 0.0023, "grad_norm": 0.006424062419682741, "learning_rate": 3.645114939668367e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 10.884353741496598, "step": 3200, "elapsed_minutes": 26.6, "average_steps_per_second": 2.005, "loss": 0.0039, "grad_norm": 0.036249954253435135, "learning_rate": 3.5140428454695766e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=11.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 11.0, "step": 3234, "elapsed_minutes": 27.05, "average_steps_per_second": 1.993, "eval_loss": 0.14966218173503876, "eval_precision": 0.7560975609756098, "eval_recall": 0.778405524168236, "eval_f1": 0.7670893906588309, "eval_accuracy": 0.9719901253323205, "eval_runtime": 12.8539, "eval_samples_per_second": 179.946, "eval_steps_per_second": 11.281}
VALIDATION_TIME fold=4 seed=123 seconds=12.86
CHECKPOINT_TIME fold=4 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 11.224489795918368, "step": 3300, "elapsed_minutes": 27.57, "average_steps_per_second": 1.995, "loss": 0.0032, "grad_norm": 0.006875176914036274, "learning_rate": 3.3829707512707855e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 11.564625850340136, "step": 3400, "elapsed_minutes": 28.33, "average_steps_per_second": 2.0, "loss": 0.0023, "grad_norm": 0.1639530062675476, "learning_rate": 3.251898657071995e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 11.904761904761905, "step": 3500, "elapsed_minutes": 29.08, "average_steps_per_second": 2.006, "loss": 0.0024, "grad_norm": 0.053221408277750015, "learning_rate": 3.120826562873205e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=12.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 12.0, "step": 3528, "elapsed_minutes": 29.49, "average_steps_per_second": 1.994, "eval_loss": 0.17045408487319946, "eval_precision": 0.741822429906542, "eval_recall": 0.7972379158819837, "eval_f1": 0.7685325264750378, "eval_accuracy": 0.9708643047040313, "eval_runtime": 13.0977, "eval_samples_per_second": 176.596, "eval_steps_per_second": 11.071}
VALIDATION_TIME fold=4 seed=123 seconds=13.10
CHECKPOINT_TIME fold=4 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 12.244897959183673, "step": 3600, "elapsed_minutes": 30.07, "average_steps_per_second": 1.995, "loss": 0.0027, "grad_norm": 0.004048136528581381, "learning_rate": 2.989754468674414e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 12.585034013605442, "step": 3700, "elapsed_minutes": 30.8, "average_steps_per_second": 2.002, "loss": 0.0018, "grad_norm": 0.11965645104646683, "learning_rate": 2.8586823744756235e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 12.92517006802721, "step": 3800, "elapsed_minutes": 31.58, "average_steps_per_second": 2.006, "loss": 0.0016, "grad_norm": 0.9798330068588257, "learning_rate": 2.7276102802768327e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=13.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 13.0, "step": 3822, "elapsed_minutes": 31.95, "average_steps_per_second": 1.994, "eval_loss": 0.1689416617155075, "eval_precision": 0.7487980769230769, "eval_recall": 0.7821720025109855, "eval_f1": 0.7651212772490021, "eval_accuracy": 0.9717730996690359, "eval_runtime": 13.1952, "eval_samples_per_second": 175.291, "eval_steps_per_second": 10.989}
VALIDATION_TIME fold=4 seed=123 seconds=13.20
CHECKPOINT_TIME fold=4 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 13.26530612244898, "step": 3900, "elapsed_minutes": 32.58, "average_steps_per_second": 1.995, "loss": 0.0012, "grad_norm": 0.029422881081700325, "learning_rate": 2.5965381860780423e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 13.60544217687075, "step": 4000, "elapsed_minutes": 33.33, "average_steps_per_second": 2.0, "loss": 0.0016, "grad_norm": 0.015695665031671524, "learning_rate": 2.4654660918792515e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 13.945578231292517, "step": 4100, "elapsed_minutes": 34.11, "average_steps_per_second": 2.003, "loss": 0.0012, "grad_norm": 0.14705543220043182, "learning_rate": 2.3343939976804607e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=14.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 14.0, "step": 4116, "elapsed_minutes": 34.42, "average_steps_per_second": 1.993, "eval_loss": 0.1864151656627655, "eval_precision": 0.788896061975468, "eval_recall": 0.7671060891399875, "eval_f1": 0.7778485041374921, "eval_accuracy": 0.9736178178069557, "eval_runtime": 12.8927, "eval_samples_per_second": 179.403, "eval_steps_per_second": 11.247}
VALIDATION_TIME fold=4 seed=123 seconds=12.89
CHECKPOINT_TIME fold=4 seed=123 seconds=0.76
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 14.285714285714286, "step": 4200, "elapsed_minutes": 35.08, "average_steps_per_second": 1.995, "loss": 0.0012, "grad_norm": 0.05668191239237785, "learning_rate": 2.2033219034816703e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 14.625850340136054, "step": 4300, "elapsed_minutes": 35.81, "average_steps_per_second": 2.001, "loss": 0.0013, "grad_norm": 0.006228506099432707, "learning_rate": 2.07224980928288e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 14.965986394557824, "step": 4400, "elapsed_minutes": 36.57, "average_steps_per_second": 2.005, "loss": 0.001, "grad_norm": 0.17317956686019897, "learning_rate": 1.941177715084089e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=15.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 15.0, "step": 4410, "elapsed_minutes": 36.86, "average_steps_per_second": 1.994, "eval_loss": 0.17843125760555267, "eval_precision": 0.770625, "eval_recall": 0.7740112994350282, "eval_f1": 0.7723144378327592, "eval_accuracy": 0.973495740871358, "eval_runtime": 12.8091, "eval_samples_per_second": 180.575, "eval_steps_per_second": 11.32}
VALIDATION_TIME fold=4 seed=123 seconds=12.81
CHECKPOINT_TIME fold=4 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 15.306122448979592, "step": 4500, "elapsed_minutes": 37.57, "average_steps_per_second": 1.997, "loss": 0.001, "grad_norm": 0.004149776417762041, "learning_rate": 1.8101056208852983e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 15.646258503401361, "step": 4600, "elapsed_minutes": 38.32, "average_steps_per_second": 2.001, "loss": 0.0008, "grad_norm": 0.0014466618886217475, "learning_rate": 1.679033526686508e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 15.986394557823129, "step": 4700, "elapsed_minutes": 39.08, "average_steps_per_second": 2.005, "loss": 0.001, "grad_norm": 0.0023530931212008, "learning_rate": 1.5479614324877174e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=16.00
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 16.0, "step": 4704, "elapsed_minutes": 39.31, "average_steps_per_second": 1.994, "eval_loss": 0.18304501473903656, "eval_precision": 0.7679012345679013, "eval_recall": 0.7809165097300691, "eval_f1": 0.7743541861188921, "eval_accuracy": 0.9731566382724757, "eval_runtime": 12.6434, "eval_samples_per_second": 182.941, "eval_steps_per_second": 11.468}
VALIDATION_TIME fold=4 seed=123 seconds=12.64
CHECKPOINT_TIME fold=4 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 16.3265306122449, "step": 4800, "elapsed_minutes": 40.07, "average_steps_per_second": 1.996, "loss": 0.0005, "grad_norm": 0.013565844856202602, "learning_rate": 1.4168893382889265e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 16.666666666666668, "step": 4900, "elapsed_minutes": 40.82, "average_steps_per_second": 2.001, "loss": 0.0005, "grad_norm": 0.04979569464921951, "learning_rate": 1.285817244090136e-05}
EPOCH_TRAIN_END fold=4 seed=123 epoch=17.00

TRAIN_PROGRESS {"fold": 4, "seed": 123, "epoch": 20.0, "step": 5880, "elapsed_minutes": 49.36, "average_steps_per_second": 1.986, "eval_loss": 0.19443835318088531, "eval_precision": 0.7769562538508934, "eval_recall": 0.7915881983678594, "eval_f1": 0.7842039800995025, "eval_accuracy": 0.9729938690250122, "eval_runtime": 12.5383, "eval_samples_per_second": 184.474, "eval_steps_per_second": 11.565}
VALIDATION_TIME fold=4 seed=123 seconds=26.74
    fold=4 seed=123 | best_f1=0.7842 | eval_f1=0.7842 | 49.4 min

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  Seed 4242...
TRAIN_START fold=4 seed=4242 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 0.3401360544217687, "step": 100, "elapsed_minutes": 0.73, "average_steps_per_second": 2.278, "loss": 0.4733, "grad_norm": 0.6241455674171448, "learning_rate": 1.1678523593112244e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 0.6802721088435374, "step": 200, "elapsed_minutes": 1.49, "average_steps_per_second": 2.237, "loss": 0.1169, "grad_norm": 1.873335599899292, "learning_rate": 2.3475012071003398e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=1.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 1.0, "step": 294, "elapsed_minutes": 2.45, "average_steps_per_second": 1.999, "eval_loss": 0.08833856135606766, "eval_precision": 0.6223265519040166, "eval_recall": 0.7489014438166981, "eval_f1": 0.6797720797720798, "eval_accuracy": 0.9685312788237209, "eval_runtime": 12.6192, "eval_samples_per_second": 183.292, "eval_steps_per_second": 11.49}
VALIDATION_TIME fold=4 seed=4242 seconds=12.63
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 1.0204081632653061, "step": 300, "elapsed_minutes": 2.51, "average_steps_per_second": 1.996, "loss": 0.103, "grad_norm": 0.9235478043556213, "learning_rate": 3.527150054889455e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 1.3605442176870748, "step": 400, "elapsed_minutes": 3.25, "average_steps_per_second": 2.053, "loss": 0.0836, "grad_norm": 2.927171230316162, "learning_rate": 4.706798902678571e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 1.7006802721088436, "step": 500, "elapsed_minutes": 4.01, "average_steps_per_second": 2.076, "loss": 0.0779, "grad_norm": 0.6945055723190308, "learning_rate": 5.886447750467687e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=2.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 2.0, "step": 588, "elapsed_minutes": 4.88, "average_steps_per_second": 2.006, "eval_loss": 0.08714541792869568, "eval_precision": 0.6800754242614707, "eval_recall": 0.6792215944758317, "eval_f1": 0.6796482412060301, "eval_accuracy": 0.9680836633931963, "eval_runtime": 13.3243, "eval_samples_per_second": 173.592, "eval_steps_per_second": 10.882}
VALIDATION_TIME fold=4 seed=4242 seconds=13.33
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.66
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 2.0408163265306123, "step": 600, "elapsed_minutes": 4.98, "average_steps_per_second": 2.009, "loss": 0.0762, "grad_norm": 0.8360171914100647, "learning_rate": 6.921917294638133e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 2.380952380952381, "step": 700, "elapsed_minutes": 5.76, "average_steps_per_second": 2.027, "loss": 0.0496, "grad_norm": 0.9676384329795837, "learning_rate": 6.790845200439342e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 2.7210884353741496, "step": 800, "elapsed_minutes": 6.52, "average_steps_per_second": 2.046, "loss": 0.0462, "grad_norm": 0.4491792917251587, "learning_rate": 6.659773106240552e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=3.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 3.0, "step": 882, "elapsed_minutes": 7.31, "average_steps_per_second": 2.012, "eval_loss": 0.08866502344608307, "eval_precision": 0.7212713936430318, "eval_recall": 0.7407407407407407, "eval_f1": 0.7308764323319912, "eval_accuracy": 0.97104063805545, "eval_runtime": 12.593, "eval_samples_per_second": 183.673, "eval_steps_per_second": 11.514}
VALIDATION_TIME fold=4 seed=4242 seconds=12.59
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.71
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 3.061224489795918, "step": 900, "elapsed_minutes": 7.45, "average_steps_per_second": 2.014, "loss": 0.0517, "grad_norm": 1.796804428100586, "learning_rate": 6.52870101204176e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 3.4013605442176873, "step": 1000, "elapsed_minutes": 8.17, "average_steps_per_second": 2.04, "loss": 0.0243, "grad_norm": 0.8427708745002747, "learning_rate": 6.39762891784297e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 3.741496598639456, "step": 1100, "elapsed_minutes": 8.97, "average_steps_per_second": 2.043, "loss": 0.0298, "grad_norm": 0.4922880232334137, "learning_rate": 6.26655682364418e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=4.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 4.0, "step": 1176, "elapsed_minutes": 9.75, "average_steps_per_second": 2.011, "eval_loss": 0.11587320268154144, "eval_precision": 0.7120689655172414, "eval_recall": 0.7777777777777778, "eval_f1": 0.7434743474347435, "eval_accuracy": 0.9713526124464218, "eval_runtime": 12.5957, "eval_samples_per_second": 183.634, "eval_steps_per_second": 11.512}
VALIDATION_TIME fold=4 seed=4242 seconds=12.60
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 4.081632653061225, "step": 1200, "elapsed_minutes": 9.93, "average_steps_per_second": 2.014, "loss": 0.0225, "grad_norm": 1.2070292234420776, "learning_rate": 6.135484729445389e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 4.421768707482993, "step": 1300, "elapsed_minutes": 10.68, "average_steps_per_second": 2.028, "loss": 0.0172, "grad_norm": 0.09780815988779068, "learning_rate": 6.004412635246598e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 4.761904761904762, "step": 1400, "elapsed_minutes": 11.43, "average_steps_per_second": 2.041, "loss": 0.0174, "grad_norm": 0.18142260611057281, "learning_rate": 5.873340541047807e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=5.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 5.0, "step": 1470, "elapsed_minutes": 12.17, "average_steps_per_second": 2.013, "eval_loss": 0.1439182311296463, "eval_precision": 0.7648922686945501, "eval_recall": 0.7576898932831136, "eval_f1": 0.761274046042258, "eval_accuracy": 0.9725869459063534, "eval_runtime": 12.661, "eval_samples_per_second": 182.688, "eval_steps_per_second": 11.453}
VALIDATION_TIME fold=4 seed=4242 seconds=12.66
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 5.1020408163265305, "step": 1500, "elapsed_minutes": 12.41, "average_steps_per_second": 2.014, "loss": 0.0155, "grad_norm": 0.541633129119873, "learning_rate": 5.742268446849017e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 5.442176870748299, "step": 1600, "elapsed_minutes": 13.2, "average_steps_per_second": 2.02, "loss": 0.0112, "grad_norm": 0.37081360816955566, "learning_rate": 5.611196352650226e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 5.782312925170068, "step": 1700, "elapsed_minutes": 13.94, "average_steps_per_second": 2.033, "loss": 0.0117, "grad_norm": 0.35335472226142883, "learning_rate": 5.480124258451435e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=6.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 6.0, "step": 1764, "elapsed_minutes": 14.59, "average_steps_per_second": 2.014, "eval_loss": 0.12615196406841278, "eval_precision": 0.724198250728863, "eval_recall": 0.7796610169491526, "eval_f1": 0.7509068923821041, "eval_accuracy": 0.9707693559763442, "eval_runtime": 12.5548, "eval_samples_per_second": 184.232, "eval_steps_per_second": 11.549}
VALIDATION_TIME fold=4 seed=4242 seconds=12.56
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.65
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 6.122448979591836, "step": 1800, "elapsed_minutes": 14.87, "average_steps_per_second": 2.018, "loss": 0.0124, "grad_norm": 0.2708747684955597, "learning_rate": 5.3490521642526454e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 6.462585034013605, "step": 1900, "elapsed_minutes": 15.61, "average_steps_per_second": 2.029, "loss": 0.0095, "grad_norm": 0.3609977960586548, "learning_rate": 5.217980070053855e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 6.802721088435375, "step": 2000, "elapsed_minutes": 16.4, "average_steps_per_second": 2.032, "loss": 0.0076, "grad_norm": 0.1880633383989334, "learning_rate": 5.086907975855064e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=7.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 7.0, "step": 2058, "elapsed_minutes": 17.01, "average_steps_per_second": 2.016, "eval_loss": 0.15002122521400452, "eval_precision": 0.7641921397379913, "eval_recall": 0.7689893283113622, "eval_f1": 0.7665832290362955, "eval_accuracy": 0.9728310997775487, "eval_runtime": 12.7235, "eval_samples_per_second": 181.79, "eval_steps_per_second": 11.396}
VALIDATION_TIME fold=4 seed=4242 seconds=12.72
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.71
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 7.142857142857143, "step": 2100, "elapsed_minutes": 17.34, "average_steps_per_second": 2.018, "loss": 0.0053, "grad_norm": 0.24167212843894958, "learning_rate": 4.9558358816562734e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 7.482993197278912, "step": 2200, "elapsed_minutes": 18.08, "average_steps_per_second": 2.029, "loss": 0.0052, "grad_norm": 0.10042602568864822, "learning_rate": 4.824763787457483e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 7.8231292517006805, "step": 2300, "elapsed_minutes": 18.82, "average_steps_per_second": 2.036, "loss": 0.0044, "grad_norm": 0.8420093059539795, "learning_rate": 4.693691693258692e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=8.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 8.0, "step": 2352, "elapsed_minutes": 19.43, "average_steps_per_second": 2.017, "eval_loss": 0.1522955596446991, "eval_precision": 0.769182782283219, "eval_recall": 0.7740112994350282, "eval_f1": 0.7715894868585732, "eval_accuracy": 0.9735364331832239, "eval_runtime": 12.5919, "eval_samples_per_second": 183.69, "eval_steps_per_second": 11.515}
VALIDATION_TIME fold=4 seed=4242 seconds=12.59
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 8.16326530612245, "step": 2400, "elapsed_minutes": 19.81, "average_steps_per_second": 2.02, "loss": 0.0056, "grad_norm": 0.19322456419467926, "learning_rate": 4.5626195990599014e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 8.503401360544217, "step": 2500, "elapsed_minutes": 20.56, "average_steps_per_second": 2.027, "loss": 0.0036, "grad_norm": 0.011440422385931015, "learning_rate": 4.43154750486111e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 8.843537414965986, "step": 2600, "elapsed_minutes": 21.3, "average_steps_per_second": 2.035, "loss": 0.0046, "grad_norm": 0.6682760119438171, "learning_rate": 4.30047541066232e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=9.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 9.0, "step": 2646, "elapsed_minutes": 21.87, "average_steps_per_second": 2.017, "eval_loss": 0.1616283804178238, "eval_precision": 0.7356188262638002, "eval_recall": 0.7947269303201506, "eval_f1": 0.7640313820156911, "eval_accuracy": 0.9726412023221745, "eval_runtime": 12.8231, "eval_samples_per_second": 180.378, "eval_steps_per_second": 11.308}
VALIDATION_TIME fold=4 seed=4242 seconds=12.82
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 9.183673469387756, "step": 2700, "elapsed_minutes": 22.3, "average_steps_per_second": 2.018, "loss": 0.0054, "grad_norm": 0.167502298951149, "learning_rate": 4.1694033164635295e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 9.523809523809524, "step": 2800, "elapsed_minutes": 23.06, "average_steps_per_second": 2.023, "loss": 0.0042, "grad_norm": 0.1414175182580948, "learning_rate": 4.0383312222647384e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 9.863945578231293, "step": 2900, "elapsed_minutes": 23.8, "average_steps_per_second": 2.031, "loss": 0.0035, "grad_norm": 3.6071200370788574, "learning_rate": 3.9072591280659486e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=10.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 10.0, "step": 2940, "elapsed_minutes": 24.31, "average_steps_per_second": 2.016, "eval_loss": 0.15139734745025635, "eval_precision": 0.7748724489795918, "eval_recall": 0.7627118644067796, "eval_f1": 0.7687440683328061, "eval_accuracy": 0.9742960230047203, "eval_runtime": 13.161, "eval_samples_per_second": 175.746, "eval_steps_per_second": 11.017}
VALIDATION_TIME fold=4 seed=4242 seconds=13.16
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.73
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 10.204081632653061, "step": 3000, "elapsed_minutes": 24.79, "average_steps_per_second": 2.017, "loss": 0.0038, "grad_norm": 0.21697621047496796, "learning_rate": 3.776187033867158e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 10.54421768707483, "step": 3100, "elapsed_minutes": 25.54, "average_steps_per_second": 2.023, "loss": 0.0033, "grad_norm": 0.08470583707094193, "learning_rate": 3.645114939668367e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 10.884353741496598, "step": 3200, "elapsed_minutes": 26.28, "average_steps_per_second": 2.029, "loss": 0.0022, "grad_norm": 0.0053442963398993015, "learning_rate": 3.5140428454695766e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=11.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 11.0, "step": 3234, "elapsed_minutes": 26.74, "average_steps_per_second": 2.016, "eval_loss": 0.1748465895652771, "eval_precision": 0.7681426814268143, "eval_recall": 0.7840552416823603, "eval_f1": 0.7760173967070518, "eval_accuracy": 0.9744316640442733, "eval_runtime": 12.7086, "eval_samples_per_second": 182.003, "eval_steps_per_second": 11.41}
VALIDATION_TIME fold=4 seed=4242 seconds=12.71
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.71
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 11.224489795918368, "step": 3300, "elapsed_minutes": 27.25, "average_steps_per_second": 2.018, "loss": 0.0011, "grad_norm": 0.0032078044023364782, "learning_rate": 3.3829707512707855e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 11.564625850340136, "step": 3400, "elapsed_minutes": 27.99, "average_steps_per_second": 2.025, "loss": 0.0021, "grad_norm": 0.0023364173248410225, "learning_rate": 3.251898657071995e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 11.904761904761905, "step": 3500, "elapsed_minutes": 28.78, "average_steps_per_second": 2.027, "loss": 0.0018, "grad_norm": 0.0029336188454180956, "learning_rate": 3.120826562873205e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=12.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 12.0, "step": 3528, "elapsed_minutes": 29.18, "average_steps_per_second": 2.015, "eval_loss": 0.17218901216983795, "eval_precision": 0.7532149418248623, "eval_recall": 0.7721280602636534, "eval_f1": 0.7625542467451952, "eval_accuracy": 0.9718816125006782, "eval_runtime": 12.6643, "eval_samples_per_second": 182.639, "eval_steps_per_second": 11.449}
VALIDATION_TIME fold=4 seed=4242 seconds=12.67
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.65
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 12.244897959183673, "step": 3600, "elapsed_minutes": 29.69, "average_steps_per_second": 2.021, "loss": 0.0031, "grad_norm": 0.0038514290936291218, "learning_rate": 2.989754468674414e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 12.585034013605442, "step": 3700, "elapsed_minutes": 30.44, "average_steps_per_second": 2.026, "loss": 0.0014, "grad_norm": 0.09351229667663574, "learning_rate": 2.8586823744756235e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 12.92517006802721, "step": 3800, "elapsed_minutes": 31.23, "average_steps_per_second": 2.028, "loss": 0.0016, "grad_norm": 0.024472033604979515, "learning_rate": 2.7276102802768327e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=13.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 13.0, "step": 3822, "elapsed_minutes": 31.6, "average_steps_per_second": 2.016, "eval_loss": 0.17013145983219147, "eval_precision": 0.7482014388489209, "eval_recall": 0.783427495291902, "eval_f1": 0.7654093836246549, "eval_accuracy": 0.9734143562476263, "eval_runtime": 13.0065, "eval_samples_per_second": 177.834, "eval_steps_per_second": 11.148}
VALIDATION_TIME fold=4 seed=4242 seconds=13.01
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 13.26530612244898, "step": 3900, "elapsed_minutes": 32.18, "average_steps_per_second": 2.02, "loss": 0.0015, "grad_norm": 0.004781158175319433, "learning_rate": 2.5965381860780423e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 13.60544217687075, "step": 4000, "elapsed_minutes": 32.95, "average_steps_per_second": 2.023, "loss": 0.0019, "grad_norm": 0.003301025368273258, "learning_rate": 2.4654660918792515e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 13.945578231292517, "step": 4100, "elapsed_minutes": 33.7, "average_steps_per_second": 2.028, "loss": 0.0012, "grad_norm": 0.007591636385768652, "learning_rate": 2.3343939976804607e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=14.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 14.0, "step": 4116, "elapsed_minutes": 34.04, "average_steps_per_second": 2.015, "eval_loss": 0.18369531631469727, "eval_precision": 0.7521008403361344, "eval_recall": 0.7865662272441933, "eval_f1": 0.7689475299171525, "eval_accuracy": 0.9734143562476263, "eval_runtime": 12.7492, "eval_samples_per_second": 181.423, "eval_steps_per_second": 11.373}
VALIDATION_TIME fold=4 seed=4242 seconds=12.75
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 14.285714285714286, "step": 4200, "elapsed_minutes": 34.72, "average_steps_per_second": 2.016, "loss": 0.0004, "grad_norm": 0.12097476422786713, "learning_rate": 2.2033219034816703e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 14.625850340136054, "step": 4300, "elapsed_minutes": 35.47, "average_steps_per_second": 2.021, "loss": 0.0004, "grad_norm": 0.3524763584136963, "learning_rate": 2.07224980928288e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 14.965986394557824, "step": 4400, "elapsed_minutes": 36.22, "average_steps_per_second": 2.024, "loss": 0.0007, "grad_norm": 0.008126523345708847, "learning_rate": 1.941177715084089e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=15.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 15.0, "step": 4410, "elapsed_minutes": 36.5, "average_steps_per_second": 2.013, "eval_loss": 0.20047830045223236, "eval_precision": 0.7566924449732302, "eval_recall": 0.7984934086629002, "eval_f1": 0.7770311545510079, "eval_accuracy": 0.9722749715153817, "eval_runtime": 12.6975, "eval_samples_per_second": 182.162, "eval_steps_per_second": 11.42}
VALIDATION_TIME fold=4 seed=4242 seconds=12.70
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.71
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 15.306122448979592, "step": 4500, "elapsed_minutes": 37.22, "average_steps_per_second": 2.015, "loss": 0.0007, "grad_norm": 0.011194898746907711, "learning_rate": 1.8101056208852983e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 15.646258503401361, "step": 4600, "elapsed_minutes": 37.96, "average_steps_per_second": 2.02, "loss": 0.0008, "grad_norm": 0.158061683177948, "learning_rate": 1.679033526686508e-05}
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 15.986394557823129, "step": 4700, "elapsed_minutes": 38.69, "average_steps_per_second": 2.025, "loss": 0.0014, "grad_norm": 0.0011010525049641728, "learning_rate": 1.5479614324877174e-05}
EPOCH_TRAIN_END fold=4 seed=4242 epoch=16.00
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 16.0, "step": 4704, "elapsed_minutes": 38.94, "average_steps_per_second": 2.013, "eval_loss": 0.1889752298593521, "eval_precision": 0.75737507525587, "eval_recall": 0.7897049591964846, "eval_f1": 0.77320221266134, "eval_accuracy": 0.973170202376431, "eval_runtime": 12.7896, "eval_samples_per_second": 180.85, "eval_steps_per_second": 11.337}
VALIDATION_TIME fold=4 seed=4242 seconds=12.79
CHECKPOINT_TIME fold=4 seed=4242 seconds=0.65
TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 16.3265306122449, "step": 4800, "elapsed_minutes": 39.67, "average_steps_per_second": 2.017, "loss": 0.0006, "grad_norm": 0.014522487297654152, "learning_rate": 1.4168893382889265e-05}

TRAIN_PROGRESS {"fold": 4, "seed": 4242, "epoch": 20.0, "step": 5880, "elapsed_minutes": 48.93, "average_steps_per_second": 2.003, "eval_loss": 0.19451501965522766, "eval_precision": 0.7720815318097591, "eval_recall": 0.7846829880728186, "eval_f1": 0.7783312577833126, "eval_accuracy": 0.9745673050838262, "eval_runtime": 12.5319, "eval_samples_per_second": 184.569, "eval_steps_per_second": 11.57}
VALIDATION_TIME fold=4 seed=4242 seconds=26.05
    fold=4 seed=4242 | best_f1=0.7783 | eval_f1=0.7783 | 48.9 min

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 5/5 | train=600 docs / 9398 seqs | val=150 docs / 2315 seqs
  Seed 123...
TRAIN_START fold=5 seed=123 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 0.3401360544217687, "step": 100, "elapsed_minutes": 0.75, "average_steps_per_second": 2.219, "loss": 0.4637, "grad_norm": 1.0902844667434692, "learning_rate": 1.1678523593112244e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 0.6802721088435374, "step": 200, "elapsed_minutes": 1.52, "average_steps_per_second": 2.188, "loss": 0.1157, "grad_norm": 0.8637807369232178, "learning_rate": 2.3475012071003398e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=1.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 1.0, "step": 294, "elapsed_minutes": 2.45, "average_steps_per_second": 1.998, "eval_loss": 0.09150911867618561, "eval_precision": 0.6447761194029851, "eval_recall": 0.7114624505928854, "eval_f1": 0.6764797995615409, "eval_accuracy": 0.9673933457576677, "eval_runtime": 12.7093, "eval_samples_per_second": 182.15, "eval_steps_per_second": 11.409}
VALIDATION_TIME fold=5 seed=123 seconds=12.72
CHECKPOINT_TIME fold=5 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 1.0204081632653061, "step": 300, "elapsed_minutes": 2.5, "average_steps_per_second": 1.997, "loss": 0.0912, "grad_norm": 1.0229740142822266, "learning_rate": 3.527150054889455e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 1.3605442176870748, "step": 400, "elapsed_minutes": 3.25, "average_steps_per_second": 2.049, "loss": 0.0793, "grad_norm": 0.3804134726524353, "learning_rate": 4.706798902678571e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 1.7006802721088436, "step": 500, "elapsed_minutes": 4.0, "average_steps_per_second": 2.084, "loss": 0.0779, "grad_norm": 1.324148178100586, "learning_rate": 5.886447750467687e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=2.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 2.0, "step": 588, "elapsed_minutes": 4.9, "average_steps_per_second": 1.999, "eval_loss": 0.08615801483392715, "eval_precision": 0.6527220630372493, "eval_recall": 0.7503293807641633, "eval_f1": 0.69813055470426, "eval_accuracy": 0.9689969517040119, "eval_runtime": 13.3452, "eval_samples_per_second": 173.47, "eval_steps_per_second": 10.865}
VALIDATION_TIME fold=5 seed=123 seconds=13.35
CHECKPOINT_TIME fold=5 seed=123 seconds=0.70
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 2.0408163265306123, "step": 600, "elapsed_minutes": 5.0, "average_steps_per_second": 1.998, "loss": 0.0798, "grad_norm": 0.8685294985771179, "learning_rate": 6.921917294638133e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 2.380952380952381, "step": 700, "elapsed_minutes": 5.77, "average_steps_per_second": 2.022, "loss": 0.0479, "grad_norm": 2.1981446743011475, "learning_rate": 6.790845200439342e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 2.7210884353741496, "step": 800, "elapsed_minutes": 6.51, "average_steps_per_second": 2.049, "loss": 0.0531, "grad_norm": 1.7466094493865967, "learning_rate": 6.659773106240552e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=3.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 3.0, "step": 882, "elapsed_minutes": 7.34, "average_steps_per_second": 2.003, "eval_loss": 0.1053134873509407, "eval_precision": 0.7346637102734663, "eval_recall": 0.6548089591567853, "eval_f1": 0.6924416579588992, "eval_accuracy": 0.9674800271601728, "eval_runtime": 12.6015, "eval_samples_per_second": 183.709, "eval_steps_per_second": 11.507}
VALIDATION_TIME fold=5 seed=123 seconds=12.60
CHECKPOINT_TIME fold=5 seed=123 seconds=0.64
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 3.061224489795918, "step": 900, "elapsed_minutes": 7.48, "average_steps_per_second": 2.006, "loss": 0.0452, "grad_norm": 1.1434284448623657, "learning_rate": 6.52870101204176e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 3.4013605442176873, "step": 1000, "elapsed_minutes": 8.24, "average_steps_per_second": 2.023, "loss": 0.0308, "grad_norm": 0.5555550456047058, "learning_rate": 6.39762891784297e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 3.741496598639456, "step": 1100, "elapsed_minutes": 8.98, "average_steps_per_second": 2.042, "loss": 0.0295, "grad_norm": 2.778698444366455, "learning_rate": 6.26655682364418e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=4.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 4.0, "step": 1176, "elapsed_minutes": 9.78, "average_steps_per_second": 2.003, "eval_loss": 0.09246168285608292, "eval_precision": 0.7123977344241661, "eval_recall": 0.7457180500658761, "eval_f1": 0.7286771805600257, "eval_accuracy": 0.9719007786879325, "eval_runtime": 12.7327, "eval_samples_per_second": 181.815, "eval_steps_per_second": 11.388}
VALIDATION_TIME fold=5 seed=123 seconds=12.73
CHECKPOINT_TIME fold=5 seed=123 seconds=0.73
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 4.081632653061225, "step": 1200, "elapsed_minutes": 9.98, "average_steps_per_second": 2.005, "loss": 0.026, "grad_norm": 0.4957837760448456, "learning_rate": 6.135484729445389e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 4.421768707482993, "step": 1300, "elapsed_minutes": 10.74, "average_steps_per_second": 2.017, "loss": 0.0144, "grad_norm": 1.1116589307785034, "learning_rate": 6.004412635246598e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 4.761904761904762, "step": 1400, "elapsed_minutes": 11.5, "average_steps_per_second": 2.029, "loss": 0.0169, "grad_norm": 1.1143088340759277, "learning_rate": 5.873340541047807e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=5.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 5.0, "step": 1470, "elapsed_minutes": 12.23, "average_steps_per_second": 2.003, "eval_loss": 0.11443372070789337, "eval_precision": 0.7044776119402985, "eval_recall": 0.7773386034255599, "eval_f1": 0.7391168180394614, "eval_accuracy": 0.970990623961629, "eval_runtime": 12.543, "eval_samples_per_second": 184.566, "eval_steps_per_second": 11.56}
VALIDATION_TIME fold=5 seed=123 seconds=12.54
CHECKPOINT_TIME fold=5 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 5.1020408163265305, "step": 1500, "elapsed_minutes": 12.46, "average_steps_per_second": 2.006, "loss": 0.0177, "grad_norm": 0.09885568171739578, "learning_rate": 5.742268446849017e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 5.442176870748299, "step": 1600, "elapsed_minutes": 13.22, "average_steps_per_second": 2.017, "loss": 0.008, "grad_norm": 0.14402532577514648, "learning_rate": 5.611196352650226e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 5.782312925170068, "step": 1700, "elapsed_minutes": 13.97, "average_steps_per_second": 2.028, "loss": 0.0114, "grad_norm": 0.13714192807674408, "learning_rate": 5.480124258451435e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=6.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 6.0, "step": 1764, "elapsed_minutes": 14.69, "average_steps_per_second": 2.002, "eval_loss": 0.15076328814029694, "eval_precision": 0.7410540013012362, "eval_recall": 0.7503293807641633, "eval_f1": 0.7456628477905074, "eval_accuracy": 0.9722475042979529, "eval_runtime": 12.9901, "eval_samples_per_second": 178.213, "eval_steps_per_second": 11.162}
VALIDATION_TIME fold=5 seed=123 seconds=12.99
CHECKPOINT_TIME fold=5 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 6.122448979591836, "step": 1800, "elapsed_minutes": 14.97, "average_steps_per_second": 2.003, "loss": 0.0086, "grad_norm": 0.05994558706879616, "learning_rate": 5.3490521642526454e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 6.462585034013605, "step": 1900, "elapsed_minutes": 15.72, "average_steps_per_second": 2.014, "loss": 0.0074, "grad_norm": 2.3754169940948486, "learning_rate": 5.217980070053855e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 6.802721088435375, "step": 2000, "elapsed_minutes": 16.51, "average_steps_per_second": 2.019, "loss": 0.0092, "grad_norm": 0.028427068144083023, "learning_rate": 5.086907975855064e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=7.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 7.0, "step": 2058, "elapsed_minutes": 17.15, "average_steps_per_second": 2.0, "eval_loss": 0.14879976212978363, "eval_precision": 0.7144585601935874, "eval_recall": 0.7779973649538867, "eval_f1": 0.7448754336171555, "eval_accuracy": 0.9715107123766595, "eval_runtime": 12.5435, "eval_samples_per_second": 184.558, "eval_steps_per_second": 11.56}
VALIDATION_TIME fold=5 seed=123 seconds=12.55
CHECKPOINT_TIME fold=5 seed=123 seconds=0.66
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 7.142857142857143, "step": 2100, "elapsed_minutes": 17.45, "average_steps_per_second": 2.006, "loss": 0.0053, "grad_norm": 0.09720107167959213, "learning_rate": 4.9558358816562734e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 7.482993197278912, "step": 2200, "elapsed_minutes": 18.23, "average_steps_per_second": 2.012, "loss": 0.0048, "grad_norm": 0.2901759743690491, "learning_rate": 4.824763787457483e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 7.8231292517006805, "step": 2300, "elapsed_minutes": 19.03, "average_steps_per_second": 2.014, "loss": 0.005, "grad_norm": 0.3470107614994049, "learning_rate": 4.693691693258692e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=8.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 8.0, "step": 2352, "elapsed_minutes": 19.63, "average_steps_per_second": 1.997, "eval_loss": 0.13846802711486816, "eval_precision": 0.6986382474837182, "eval_recall": 0.7773386034255599, "eval_f1": 0.7358902400997817, "eval_accuracy": 0.9709039425591239, "eval_runtime": 12.5849, "eval_samples_per_second": 183.95, "eval_steps_per_second": 11.522}
VALIDATION_TIME fold=5 seed=123 seconds=12.59
CHECKPOINT_TIME fold=5 seed=123 seconds=0.67
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 8.16326530612245, "step": 2400, "elapsed_minutes": 20.01, "average_steps_per_second": 1.999, "loss": 0.0069, "grad_norm": 0.36870047450065613, "learning_rate": 4.5626195990599014e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 8.503401360544217, "step": 2500, "elapsed_minutes": 20.72, "average_steps_per_second": 2.011, "loss": 0.0044, "grad_norm": 0.40053048729896545, "learning_rate": 4.43154750486111e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 8.843537414965986, "step": 2600, "elapsed_minutes": 21.54, "average_steps_per_second": 2.012, "loss": 0.0039, "grad_norm": 2.1317362785339355, "learning_rate": 4.30047541066232e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=9.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 9.0, "step": 2646, "elapsed_minutes": 22.08, "average_steps_per_second": 1.998, "eval_loss": 0.16123753786087036, "eval_precision": 0.7384815055158988, "eval_recall": 0.7496706192358367, "eval_f1": 0.7440339980385746, "eval_accuracy": 0.9713517964720669, "eval_runtime": 12.697, "eval_samples_per_second": 182.326, "eval_steps_per_second": 11.42}
VALIDATION_TIME fold=5 seed=123 seconds=12.70
CHECKPOINT_TIME fold=5 seed=123 seconds=0.71
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 9.183673469387756, "step": 2700, "elapsed_minutes": 22.51, "average_steps_per_second": 1.999, "loss": 0.0051, "grad_norm": 0.21527183055877686, "learning_rate": 4.1694033164635295e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 9.523809523809524, "step": 2800, "elapsed_minutes": 23.28, "average_steps_per_second": 2.005, "loss": 0.0034, "grad_norm": 0.11992430686950684, "learning_rate": 4.0383312222647384e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 9.863945578231293, "step": 2900, "elapsed_minutes": 24.03, "average_steps_per_second": 2.011, "loss": 0.0025, "grad_norm": 2.114626884460449, "learning_rate": 3.9072591280659486e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=10.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 10.0, "step": 2940, "elapsed_minutes": 24.54, "average_steps_per_second": 1.997, "eval_loss": 0.16573461890220642, "eval_precision": 0.7175480769230769, "eval_recall": 0.7865612648221344, "eval_f1": 0.7504714016341922, "eval_accuracy": 0.9711639867666392, "eval_runtime": 12.5245, "eval_samples_per_second": 184.837, "eval_steps_per_second": 11.577}
VALIDATION_TIME fold=5 seed=123 seconds=12.53
CHECKPOINT_TIME fold=5 seed=123 seconds=0.72
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 10.204081632653061, "step": 3000, "elapsed_minutes": 25.02, "average_steps_per_second": 1.998, "loss": 0.0032, "grad_norm": 0.008556166663765907, "learning_rate": 3.776187033867158e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 10.54421768707483, "step": 3100, "elapsed_minutes": 25.79, "average_steps_per_second": 2.003, "loss": 0.0021, "grad_norm": 0.08202414214611053, "learning_rate": 3.645114939668367e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 10.884353741496598, "step": 3200, "elapsed_minutes": 26.55, "average_steps_per_second": 2.009, "loss": 0.0032, "grad_norm": 0.034565702080726624, "learning_rate": 3.5140428454695766e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=11.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 11.0, "step": 3234, "elapsed_minutes": 27.0, "average_steps_per_second": 1.996, "eval_loss": 0.18374615907669067, "eval_precision": 0.7335009428032684, "eval_recall": 0.7687747035573123, "eval_f1": 0.7507237053715021, "eval_accuracy": 0.9699937878328204, "eval_runtime": 12.6513, "eval_samples_per_second": 182.985, "eval_steps_per_second": 11.461}
VALIDATION_TIME fold=5 seed=123 seconds=12.65
CHECKPOINT_TIME fold=5 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 11.224489795918368, "step": 3300, "elapsed_minutes": 27.53, "average_steps_per_second": 1.998, "loss": 0.0022, "grad_norm": 0.14941638708114624, "learning_rate": 3.3829707512707855e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 11.564625850340136, "step": 3400, "elapsed_minutes": 28.29, "average_steps_per_second": 2.003, "loss": 0.0023, "grad_norm": 0.3754015266895294, "learning_rate": 3.251898657071995e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 11.904761904761905, "step": 3500, "elapsed_minutes": 29.05, "average_steps_per_second": 2.008, "loss": 0.0021, "grad_norm": 0.04584279656410217, "learning_rate": 3.120826562873205e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=12.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 12.0, "step": 3528, "elapsed_minutes": 29.47, "average_steps_per_second": 1.995, "eval_loss": 0.17759935557842255, "eval_precision": 0.746031746031746, "eval_recall": 0.7740447957839263, "eval_f1": 0.7597801487229227, "eval_accuracy": 0.9722619511983704, "eval_runtime": 12.9803, "eval_samples_per_second": 178.347, "eval_steps_per_second": 11.171}
VALIDATION_TIME fold=5 seed=123 seconds=12.98
CHECKPOINT_TIME fold=5 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 12.244897959183673, "step": 3600, "elapsed_minutes": 30.03, "average_steps_per_second": 1.998, "loss": 0.0014, "grad_norm": 0.0615634024143219, "learning_rate": 2.989754468674414e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 12.585034013605442, "step": 3700, "elapsed_minutes": 30.77, "average_steps_per_second": 2.004, "loss": 0.0021, "grad_norm": 0.7033767104148865, "learning_rate": 2.8586823744756235e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 12.92517006802721, "step": 3800, "elapsed_minutes": 31.54, "average_steps_per_second": 2.008, "loss": 0.0017, "grad_norm": 0.008334054611623287, "learning_rate": 2.7276102802768327e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=13.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 13.0, "step": 3822, "elapsed_minutes": 31.93, "average_steps_per_second": 1.995, "eval_loss": 0.18872809410095215, "eval_precision": 0.7456647398843931, "eval_recall": 0.7648221343873518, "eval_f1": 0.7551219512195121, "eval_accuracy": 0.9715829468787471, "eval_runtime": 13.1991, "eval_samples_per_second": 175.391, "eval_steps_per_second": 10.986}
VALIDATION_TIME fold=5 seed=123 seconds=13.20
CHECKPOINT_TIME fold=5 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 13.26530612244898, "step": 3900, "elapsed_minutes": 32.54, "average_steps_per_second": 1.997, "loss": 0.0016, "grad_norm": 0.012893944047391415, "learning_rate": 2.5965381860780423e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 13.60544217687075, "step": 4000, "elapsed_minutes": 33.3, "average_steps_per_second": 2.002, "loss": 0.0019, "grad_norm": 0.22952593863010406, "learning_rate": 2.4654660918792515e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 13.945578231292517, "step": 4100, "elapsed_minutes": 34.07, "average_steps_per_second": 2.006, "loss": 0.0012, "grad_norm": 0.0020636175759136677, "learning_rate": 2.3343939976804607e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=14.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 14.0, "step": 4116, "elapsed_minutes": 34.4, "average_steps_per_second": 1.994, "eval_loss": 0.19696621596813202, "eval_precision": 0.7445442875481386, "eval_recall": 0.764163372859025, "eval_f1": 0.7542262678803641, "eval_accuracy": 0.9702393851399183, "eval_runtime": 12.6104, "eval_samples_per_second": 183.579, "eval_steps_per_second": 11.498}
VALIDATION_TIME fold=5 seed=123 seconds=12.61
CHECKPOINT_TIME fold=5 seed=123 seconds=0.69
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 14.285714285714286, "step": 4200, "elapsed_minutes": 35.06, "average_steps_per_second": 1.997, "loss": 0.0011, "grad_norm": 0.003255992429330945, "learning_rate": 2.2033219034816703e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 14.625850340136054, "step": 4300, "elapsed_minutes": 35.83, "average_steps_per_second": 2.0, "loss": 0.0009, "grad_norm": 0.05095444992184639, "learning_rate": 2.07224980928288e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 14.965986394557824, "step": 4400, "elapsed_minutes": 36.58, "average_steps_per_second": 2.005, "loss": 0.0009, "grad_norm": 0.05826712027192116, "learning_rate": 1.941177715084089e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=15.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 15.0, "step": 4410, "elapsed_minutes": 36.86, "average_steps_per_second": 1.994, "eval_loss": 0.1897653192281723, "eval_precision": 0.7262124002455494, "eval_recall": 0.7793148880105402, "eval_f1": 0.751827136955831, "eval_accuracy": 0.9706872390528613, "eval_runtime": 12.5422, "eval_samples_per_second": 184.577, "eval_steps_per_second": 11.561}
VALIDATION_TIME fold=5 seed=123 seconds=12.54
CHECKPOINT_TIME fold=5 seed=123 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 15.306122448979592, "step": 4500, "elapsed_minutes": 37.59, "average_steps_per_second": 1.995, "loss": 0.0006, "grad_norm": 0.0238303542137146, "learning_rate": 1.8101056208852983e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 15.646258503401361, "step": 4600, "elapsed_minutes": 38.34, "average_steps_per_second": 1.999, "loss": 0.0011, "grad_norm": 0.015073506161570549, "learning_rate": 1.679033526686508e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 15.986394557823129, "step": 4700, "elapsed_minutes": 39.11, "average_steps_per_second": 2.003, "loss": 0.0006, "grad_norm": 0.06066429242491722, "learning_rate": 1.5479614324877174e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=16.00
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 16.0, "step": 4704, "elapsed_minutes": 39.35, "average_steps_per_second": 1.993, "eval_loss": 0.20702120661735535, "eval_precision": 0.7493654822335025, "eval_recall": 0.7779973649538867, "eval_f1": 0.7634130575307047, "eval_accuracy": 0.9709761770612115, "eval_runtime": 12.5976, "eval_samples_per_second": 183.765, "eval_steps_per_second": 11.51}
VALIDATION_TIME fold=5 seed=123 seconds=12.60
CHECKPOINT_TIME fold=5 seed=123 seconds=0.73
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 16.3265306122449, "step": 4800, "elapsed_minutes": 40.1, "average_steps_per_second": 1.995, "loss": 0.0006, "grad_norm": 0.013274776749312878, "learning_rate": 1.4168893382889265e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 16.666666666666668, "step": 4900, "elapsed_minutes": 40.85, "average_steps_per_second": 1.999, "loss": 0.0007, "grad_norm": 0.009368923492729664, "learning_rate": 1.285817244090136e-05}
EPOCH_TRAIN_END fold=5 seed=123 epoch=17.00

TRAIN_PROGRESS {"fold": 5, "seed": 123, "epoch": 20.0, "step": 5880, "elapsed_minutes": 49.41, "average_steps_per_second": 1.983, "eval_loss": 0.20702120661735535, "eval_precision": 0.7493654822335025, "eval_recall": 0.7779973649538867, "eval_f1": 0.7634130575307047, "eval_accuracy": 0.9709761770612115, "eval_runtime": 12.562, "eval_samples_per_second": 184.286, "eval_steps_per_second": 11.543}
VALIDATION_TIME fold=5 seed=123 seconds=26.17
    fold=5 seed=123 | best_f1=0.7634 | eval_f1=0.7634 | 49.4 min

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at lcampillos/roberta-es-clinical-trials-ner and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([3]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  Seed 4242...
TRAIN_START fold=5 seed=4242 GPUs=2 effective_batch=32

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 0.3401360544217687, "step": 100, "elapsed_minutes": 0.77, "average_steps_per_second": 2.154, "loss": 0.4708, "grad_norm": 1.5513705015182495, "learning_rate": 1.1678523593112244e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 0.6802721088435374, "step": 200, "elapsed_minutes": 1.54, "average_steps_per_second": 2.166, "loss": 0.1154, "grad_norm": 1.2336220741271973, "learning_rate": 2.3475012071003398e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=1.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 1.0, "step": 294, "elapsed_minutes": 2.45, "average_steps_per_second": 2.0, "eval_loss": 0.09521998465061188, "eval_precision": 0.6394176931690929, "eval_recall": 0.7523056653491436, "eval_f1": 0.6912832929782082, "eval_accuracy": 0.9660786778196738, "eval_runtime": 12.6733, "eval_samples_per_second": 182.668, "eval_steps_per_second": 11.441}
VALIDATION_TIME fold=5 seed=4242 seconds=12.68
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 1.0204081632653061, "step": 300, "elapsed_minutes": 2.5, "average_steps_per_second": 1.999, "loss": 0.1013, "grad_norm": 0.626774251461029, "learning_rate": 3.527150054889455e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 1.3605442176870748, "step": 400, "elapsed_minutes": 3.28, "average_steps_per_second": 2.031, "loss": 0.0736, "grad_norm": 1.812557339668274, "learning_rate": 4.706798902678571e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 1.7006802721088436, "step": 500, "elapsed_minutes": 4.03, "average_steps_per_second": 2.066, "loss": 0.0851, "grad_norm": 0.8456857800483704, "learning_rate": 5.886447750467687e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=2.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 2.0, "step": 588, "elapsed_minutes": 4.91, "average_steps_per_second": 1.996, "eval_loss": 0.10735554248094559, "eval_precision": 0.704358812381554, "eval_recall": 0.7345191040843215, "eval_f1": 0.7191228635923896, "eval_accuracy": 0.9693581242144498, "eval_runtime": 13.2633, "eval_samples_per_second": 174.541, "eval_steps_per_second": 10.932}
VALIDATION_TIME fold=5 seed=4242 seconds=13.26
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 2.0408163265306123, "step": 600, "elapsed_minutes": 5.02, "average_steps_per_second": 1.993, "loss": 0.0745, "grad_norm": 1.453861951828003, "learning_rate": 6.921917294638133e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 2.380952380952381, "step": 700, "elapsed_minutes": 5.79, "average_steps_per_second": 2.017, "loss": 0.0486, "grad_norm": 0.5700666904449463, "learning_rate": 6.790845200439342e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 2.7210884353741496, "step": 800, "elapsed_minutes": 6.57, "average_steps_per_second": 2.03, "loss": 0.0514, "grad_norm": 3.3384392261505127, "learning_rate": 6.659773106240552e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=3.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 3.0, "step": 882, "elapsed_minutes": 7.38, "average_steps_per_second": 1.993, "eval_loss": 0.0907486155629158, "eval_precision": 0.6773028296207104, "eval_recall": 0.741106719367589, "eval_f1": 0.7077697389116075, "eval_accuracy": 0.9668443635418021, "eval_runtime": 12.5323, "eval_samples_per_second": 184.723, "eval_steps_per_second": 11.57}
VALIDATION_TIME fold=5 seed=4242 seconds=12.53
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.67
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 3.061224489795918, "step": 900, "elapsed_minutes": 7.53, "average_steps_per_second": 1.992, "loss": 0.0498, "grad_norm": 1.0189330577850342, "learning_rate": 6.52870101204176e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 3.4013605442176873, "step": 1000, "elapsed_minutes": 8.31, "average_steps_per_second": 2.006, "loss": 0.0278, "grad_norm": 2.888721227645874, "learning_rate": 6.39762891784297e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 3.741496598639456, "step": 1100, "elapsed_minutes": 9.05, "average_steps_per_second": 2.026, "loss": 0.0301, "grad_norm": 1.0132927894592285, "learning_rate": 6.26655682364418e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=4.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 4.0, "step": 1176, "elapsed_minutes": 9.84, "average_steps_per_second": 1.992, "eval_loss": 0.09742722660303116, "eval_precision": 0.6910714285714286, "eval_recall": 0.7648221343873518, "eval_f1": 0.726078799249531, "eval_accuracy": 0.9669310449443071, "eval_runtime": 12.6013, "eval_samples_per_second": 183.712, "eval_steps_per_second": 11.507}
VALIDATION_TIME fold=5 seed=4242 seconds=12.60
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.73
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 4.081632653061225, "step": 1200, "elapsed_minutes": 10.03, "average_steps_per_second": 1.995, "loss": 0.0269, "grad_norm": 0.4009622037410736, "learning_rate": 6.135484729445389e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 4.421768707482993, "step": 1300, "elapsed_minutes": 10.79, "average_steps_per_second": 2.008, "loss": 0.0169, "grad_norm": 0.6285245418548584, "learning_rate": 6.004412635246598e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 4.761904761904762, "step": 1400, "elapsed_minutes": 11.57, "average_steps_per_second": 2.017, "loss": 0.0183, "grad_norm": 0.8526321649551392, "learning_rate": 5.873340541047807e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=5.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 5.0, "step": 1470, "elapsed_minutes": 12.3, "average_steps_per_second": 1.991, "eval_loss": 0.12531186640262604, "eval_precision": 0.7177615571776156, "eval_recall": 0.7773386034255599, "eval_f1": 0.7463630613535737, "eval_accuracy": 0.9701671506378307, "eval_runtime": 12.5814, "eval_samples_per_second": 184.002, "eval_steps_per_second": 11.525}
VALIDATION_TIME fold=5 seed=4242 seconds=12.58
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 5.1020408163265305, "step": 1500, "elapsed_minutes": 12.56, "average_steps_per_second": 1.991, "loss": 0.0172, "grad_norm": 1.0231112241744995, "learning_rate": 5.742268446849017e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 5.442176870748299, "step": 1600, "elapsed_minutes": 13.33, "average_steps_per_second": 2.001, "loss": 0.0133, "grad_norm": 0.621070146560669, "learning_rate": 5.611196352650226e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 5.782312925170068, "step": 1700, "elapsed_minutes": 14.08, "average_steps_per_second": 2.012, "loss": 0.011, "grad_norm": 0.5768536925315857, "learning_rate": 5.480124258451435e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=6.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 6.0, "step": 1764, "elapsed_minutes": 14.77, "average_steps_per_second": 1.991, "eval_loss": 0.12591570615768433, "eval_precision": 0.7306955966815571, "eval_recall": 0.7542819499341239, "eval_f1": 0.7423014586709888, "eval_accuracy": 0.9701093630361606, "eval_runtime": 12.8839, "eval_samples_per_second": 179.681, "eval_steps_per_second": 11.254}
VALIDATION_TIME fold=5 seed=4242 seconds=12.89
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.64
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 6.122448979591836, "step": 1800, "elapsed_minutes": 15.04, "average_steps_per_second": 1.994, "loss": 0.0105, "grad_norm": 0.47332146763801575, "learning_rate": 5.3490521642526454e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 6.462585034013605, "step": 1900, "elapsed_minutes": 15.83, "average_steps_per_second": 2.001, "loss": 0.0078, "grad_norm": 0.45932742953300476, "learning_rate": 5.217980070053855e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 6.802721088435375, "step": 2000, "elapsed_minutes": 16.57, "average_steps_per_second": 2.012, "loss": 0.0081, "grad_norm": 0.8120326399803162, "learning_rate": 5.086907975855064e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=7.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 7.0, "step": 2058, "elapsed_minutes": 17.22, "average_steps_per_second": 1.992, "eval_loss": 0.14305321872234344, "eval_precision": 0.7001194743130227, "eval_recall": 0.7720685111989459, "eval_f1": 0.7343358395989975, "eval_accuracy": 0.9692569959115271, "eval_runtime": 12.5744, "eval_samples_per_second": 184.105, "eval_steps_per_second": 11.531}
VALIDATION_TIME fold=5 seed=4242 seconds=12.58
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 7.142857142857143, "step": 2100, "elapsed_minutes": 17.53, "average_steps_per_second": 1.996, "loss": 0.0081, "grad_norm": 0.2507493793964386, "learning_rate": 4.9558358816562734e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 7.482993197278912, "step": 2200, "elapsed_minutes": 18.33, "average_steps_per_second": 2.0, "loss": 0.0047, "grad_norm": 0.4322739243507385, "learning_rate": 4.824763787457483e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 7.8231292517006805, "step": 2300, "elapsed_minutes": 19.1, "average_steps_per_second": 2.007, "loss": 0.0066, "grad_norm": 3.983363628387451, "learning_rate": 4.693691693258692e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=8.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 8.0, "step": 2352, "elapsed_minutes": 19.69, "average_steps_per_second": 1.991, "eval_loss": 0.14857400953769684, "eval_precision": 0.6867052023121387, "eval_recall": 0.782608695652174, "eval_f1": 0.731527093596059, "eval_accuracy": 0.9678267527701931, "eval_runtime": 12.6264, "eval_samples_per_second": 183.345, "eval_steps_per_second": 11.484}
VALIDATION_TIME fold=5 seed=4242 seconds=12.63
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 8.16326530612245, "step": 2400, "elapsed_minutes": 20.04, "average_steps_per_second": 1.996, "loss": 0.0049, "grad_norm": 0.7299790978431702, "learning_rate": 4.5626195990599014e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 8.503401360544217, "step": 2500, "elapsed_minutes": 20.8, "average_steps_per_second": 2.003, "loss": 0.004, "grad_norm": 0.039244234561920166, "learning_rate": 4.43154750486111e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 8.843537414965986, "step": 2600, "elapsed_minutes": 21.59, "average_steps_per_second": 2.007, "loss": 0.0035, "grad_norm": 0.29896873235702515, "learning_rate": 4.30047541066232e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=9.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 9.0, "step": 2646, "elapsed_minutes": 22.14, "average_steps_per_second": 1.992, "eval_loss": 0.16554827988147736, "eval_precision": 0.7259938837920489, "eval_recall": 0.7819499341238472, "eval_f1": 0.7529337139232478, "eval_accuracy": 0.9694014649157023, "eval_runtime": 12.539, "eval_samples_per_second": 184.624, "eval_steps_per_second": 11.564}
VALIDATION_TIME fold=5 seed=4242 seconds=12.54
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 9.183673469387756, "step": 2700, "elapsed_minutes": 22.58, "average_steps_per_second": 1.993, "loss": 0.0032, "grad_norm": 0.006817005109041929, "learning_rate": 4.1694033164635295e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 9.523809523809524, "step": 2800, "elapsed_minutes": 23.33, "average_steps_per_second": 2.001, "loss": 0.0021, "grad_norm": 1.4083404541015625, "learning_rate": 4.0383312222647384e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 9.863945578231293, "step": 2900, "elapsed_minutes": 24.09, "average_steps_per_second": 2.006, "loss": 0.0039, "grad_norm": 0.23048603534698486, "learning_rate": 3.9072591280659486e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=10.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 10.0, "step": 2940, "elapsed_minutes": 24.59, "average_steps_per_second": 1.992, "eval_loss": 0.17261071503162384, "eval_precision": 0.7321760694358338, "eval_recall": 0.7779973649538867, "eval_f1": 0.7543915681890768, "eval_accuracy": 0.9697770843265577, "eval_runtime": 12.5595, "eval_samples_per_second": 184.323, "eval_steps_per_second": 11.545}
VALIDATION_TIME fold=5 seed=4242 seconds=12.56
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 10.204081632653061, "step": 3000, "elapsed_minutes": 25.05, "average_steps_per_second": 1.996, "loss": 0.0023, "grad_norm": 0.5614280700683594, "learning_rate": 3.776187033867158e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 10.54421768707483, "step": 3100, "elapsed_minutes": 25.82, "average_steps_per_second": 2.001, "loss": 0.0031, "grad_norm": 0.4744375944137573, "learning_rate": 3.645114939668367e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 10.884353741496598, "step": 3200, "elapsed_minutes": 26.57, "average_steps_per_second": 2.007, "loss": 0.0023, "grad_norm": 0.13169924914836884, "learning_rate": 3.5140428454695766e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=11.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 11.0, "step": 3234, "elapsed_minutes": 27.02, "average_steps_per_second": 1.995, "eval_loss": 0.17145884037017822, "eval_precision": 0.7288971041281578, "eval_recall": 0.7793148880105402, "eval_f1": 0.7532632919452403, "eval_accuracy": 0.9706872390528613, "eval_runtime": 12.6859, "eval_samples_per_second": 182.486, "eval_steps_per_second": 11.43}
VALIDATION_TIME fold=5 seed=4242 seconds=12.69
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.65
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 11.224489795918368, "step": 3300, "elapsed_minutes": 27.53, "average_steps_per_second": 1.998, "loss": 0.0022, "grad_norm": 1.7179349660873413, "learning_rate": 3.3829707512707855e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 11.564625850340136, "step": 3400, "elapsed_minutes": 28.31, "average_steps_per_second": 2.001, "loss": 0.0037, "grad_norm": 0.37010958790779114, "learning_rate": 3.251898657071995e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 11.904761904761905, "step": 3500, "elapsed_minutes": 29.05, "average_steps_per_second": 2.008, "loss": 0.0022, "grad_norm": 0.2054768204689026, "learning_rate": 3.120826562873205e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=12.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 12.0, "step": 3528, "elapsed_minutes": 29.48, "average_steps_per_second": 1.995, "eval_loss": 0.18367360532283783, "eval_precision": 0.7177950868783702, "eval_recall": 0.7891963109354414, "eval_f1": 0.7518042045811109, "eval_accuracy": 0.9699071064303154, "eval_runtime": 12.8952, "eval_samples_per_second": 179.524, "eval_steps_per_second": 11.244}
VALIDATION_TIME fold=5 seed=4242 seconds=12.90
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.68
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 12.244897959183673, "step": 3600, "elapsed_minutes": 30.04, "average_steps_per_second": 1.998, "loss": 0.0023, "grad_norm": 0.022324196994304657, "learning_rate": 2.989754468674414e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 12.585034013605442, "step": 3700, "elapsed_minutes": 30.78, "average_steps_per_second": 2.003, "loss": 0.0018, "grad_norm": 0.20129802823066711, "learning_rate": 2.8586823744756235e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 12.92517006802721, "step": 3800, "elapsed_minutes": 31.56, "average_steps_per_second": 2.007, "loss": 0.0014, "grad_norm": 0.09539183229207993, "learning_rate": 2.7276102802768327e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=13.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 13.0, "step": 3822, "elapsed_minutes": 31.94, "average_steps_per_second": 1.994, "eval_loss": 0.18975171446800232, "eval_precision": 0.7263349514563107, "eval_recall": 0.7885375494071146, "eval_f1": 0.7561591914087176, "eval_accuracy": 0.9705283231482685, "eval_runtime": 13.0049, "eval_samples_per_second": 178.01, "eval_steps_per_second": 11.15}
VALIDATION_TIME fold=5 seed=4242 seconds=13.01
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.70
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 13.26530612244898, "step": 3900, "elapsed_minutes": 32.53, "average_steps_per_second": 1.998, "loss": 0.0012, "grad_norm": 1.0165903568267822, "learning_rate": 2.5965381860780423e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 13.60544217687075, "step": 4000, "elapsed_minutes": 33.3, "average_steps_per_second": 2.002, "loss": 0.0019, "grad_norm": 0.006366389337927103, "learning_rate": 2.4654660918792515e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 13.945578231292517, "step": 4100, "elapsed_minutes": 34.04, "average_steps_per_second": 2.007, "loss": 0.0011, "grad_norm": 1.9252934455871582, "learning_rate": 2.3343939976804607e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=14.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 14.0, "step": 4116, "elapsed_minutes": 34.38, "average_steps_per_second": 1.995, "eval_loss": 0.20188218355178833, "eval_precision": 0.7126710291493159, "eval_recall": 0.7891963109354414, "eval_f1": 0.7489840575179744, "eval_accuracy": 0.9692569959115271, "eval_runtime": 12.5146, "eval_samples_per_second": 184.984, "eval_steps_per_second": 11.586}
VALIDATION_TIME fold=5 seed=4242 seconds=12.52
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.65
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 14.285714285714286, "step": 4200, "elapsed_minutes": 35.07, "average_steps_per_second": 1.996, "loss": 0.0012, "grad_norm": 0.0027876098174601793, "learning_rate": 2.2033219034816703e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 14.625850340136054, "step": 4300, "elapsed_minutes": 35.82, "average_steps_per_second": 2.001, "loss": 0.0013, "grad_norm": 0.0012418987462297082, "learning_rate": 2.07224980928288e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 14.965986394557824, "step": 4400, "elapsed_minutes": 36.56, "average_steps_per_second": 2.006, "loss": 0.0006, "grad_norm": 1.2400766611099243, "learning_rate": 1.941177715084089e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=15.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 15.0, "step": 4410, "elapsed_minutes": 36.85, "average_steps_per_second": 1.995, "eval_loss": 0.21486616134643555, "eval_precision": 0.73579013116802, "eval_recall": 0.7760210803689065, "eval_f1": 0.7553703109971145, "eval_accuracy": 0.9704560886461809, "eval_runtime": 12.5336, "eval_samples_per_second": 184.703, "eval_steps_per_second": 11.569}
VALIDATION_TIME fold=5 seed=4242 seconds=12.54
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.69
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 15.306122448979592, "step": 4500, "elapsed_minutes": 37.57, "average_steps_per_second": 1.996, "loss": 0.0009, "grad_norm": 0.011262067593634129, "learning_rate": 1.8101056208852983e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 15.646258503401361, "step": 4600, "elapsed_minutes": 38.35, "average_steps_per_second": 1.999, "loss": 0.0008, "grad_norm": 0.02007419988512993, "learning_rate": 1.679033526686508e-05}
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 15.986394557823129, "step": 4700, "elapsed_minutes": 39.07, "average_steps_per_second": 2.005, "loss": 0.0009, "grad_norm": 0.001678817206993699, "learning_rate": 1.5479614324877174e-05}
EPOCH_TRAIN_END fold=5 seed=4242 epoch=16.00
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 16.0, "step": 4704, "elapsed_minutes": 39.31, "average_steps_per_second": 1.994, "eval_loss": 0.2054324746131897, "eval_precision": 0.7430555555555556, "eval_recall": 0.7753623188405797, "eval_f1": 0.7588652482269502, "eval_accuracy": 0.9708172611566188, "eval_runtime": 12.5951, "eval_samples_per_second": 183.802, "eval_steps_per_second": 11.512}
VALIDATION_TIME fold=5 seed=4242 seconds=12.60
CHECKPOINT_TIME fold=5 seed=4242 seconds=0.72
TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 16.3265306122449, "step": 4800, "elapsed_minutes": 40.07, "average_steps_per_second": 1.996, "loss": 0.0008, "grad_norm": 0.09883926808834076, "learning_rate": 1.4168893382889265e-05}

TRAIN_PROGRESS {"fold": 5, "seed": 4242, "epoch": 20.0, "step": 5880, "elapsed_minutes": 49.35, "average_steps_per_second": 1.986, "eval_loss": 0.22537723183631897, "eval_precision": 0.7454772301933874, "eval_recall": 0.7872200263504612, "eval_f1": 0.7657801986542774, "eval_accuracy": 0.9713951371733195, "eval_runtime": 12.5577, "eval_samples_per_second": 184.349, "eval_steps_per_second": 11.547}
VALIDATION_TIME fold=5 seed=4242 seconds=25.95
    fold=5 seed=4242 | best_f1=0.7658 | eval_f1=0.7658 | 49.4 min

Ensemble models: 10
 fold  seed  eval_f1  best_eval_f1  elapsed_min
    4   123 0.784204      0.784204    49.369440
    4  4242 0.778331      0.778331    48.938749
    1  4242 0.774704      0.774704    49.721082
    1   123 0.771883      0.771883    42.315370
    2   123 0.770846      0.770846    41.673074
    5  4242 0.765780      0.765780    49.366597
    3  4242 0.764253      0.764253    49.898335
    5   123 0.763413      0.763413    49.423240
    2  4242 0.759632      0.759632    24.713676
    3   123 0.751636      0.751636    22.536451

### 3.4. Ensemble summary

Aggregation of validation metrics across folds and seeds, and saving of the ensemble state.

In [10]:
cols = ["eval_precision", "eval_recall", "eval_f1", "eval_accuracy", "eval_loss"]
agg = df_ensemble_results[cols].agg(["mean", "std", "min", "max"]).T.reset_index().rename(columns={"index": "metric"})
print(agg.to_string(index=False))

summary = {c: {"mean": float(df_ensemble_results[c].mean()), "std": float(df_ensemble_results[c].std(ddof=0))} for c in cols}
summary["ensemble_size"] = len(ensemble_models)
with open(f"{RESULTS_DIR}/validation_ensemble_summary.json", "w", encoding="utf-8") as f:
    json.dump(summary, f, ensure_ascii=False, indent=2)

        metric     mean      std      min      max
eval_precision 0.758439 0.014338 0.738814 0.781630
   eval_recall 0.778982 0.012295 0.755166 0.791588
       eval_f1 0.768468 0.009505 0.751636 0.784204
 eval_accuracy 0.971978 0.001760 0.969986 0.974739
     eval_loss 0.184933 0.034554 0.120669 0.225377

## 4. Inference

### 4.1. Sentence-based inference function

Segment each document using spaCy, apply the NER pipeline to each sentence and adjust offsets to the full text.

In [11]:
def sentence_based_ner(texto, pipeline_ner, nlp_spacy):
    """Run sentence-based NER and map offsets to the full document."""
    doc = nlp_spacy(texto)
    all_entities = []

    for sent in doc.sents:
        sent_text = sent.text
        sent_offset = sent.start_char

        entities = pipeline_ner(sent_text)

        for entity in entities:
            entity["start"] += sent_offset
            entity["end"] += sent_offset
            all_entities.append(entity)

    return all_entities

### 4.2. Ensemble execution

Read the test texts, run inference with each ensemble model and aggregate entities by majority voting.

In [12]:
ruta_txts = DATA_PATHS["text_files_test_dir"]
ruta_gs   = DATA_PATHS["gs_mentions_tsv"]

texts_by_filename = {
    f.replace(".txt", ""): open(os.path.join(ruta_txts, f), encoding="utf-8").read()
    for f in sorted(os.listdir(ruta_txts)) if f.endswith(".txt")
}

if not texts_by_filename:
    raise RuntimeError(f"No .txt files were found in {ruta_txts}")
if not ensemble_models:
    raise RuntimeError("The ensemble contains no models.")

vote_threshold = max(1, int(np.ceil(ENSEMBLE_VOTING_RATIO * len(ensemble_models))))
pred_file = f"{RESULTS_DIR}/predictions_ensemble_k{K_FOLDS}_s{len(SEEDS)}.tsv"
aggregated = defaultdict(int)
model_times = []
end_to_end_start = t0 = time.time()

print(f"Test documents: {len(texts_by_filename)} | Models: {len(ensemble_models)} | Required votes: {vote_threshold}")

for model_info in ensemble_models:
    fold, seed, model_dir = model_info["fold"], model_info["seed"], model_info["model_dir"]
    t_model = time.time()

    modelo_inf    = AutoModelForTokenClassification.from_pretrained(model_dir)
    tokenizer_inf = AutoTokenizer.from_pretrained(model_dir)
    nlp_ner = pipeline("ner", model=modelo_inf, tokenizer=tokenizer_inf, aggregation_strategy="simple")

    for filename, texto in texts_by_filename.items():
        for ent in sentence_based_ner(texto, nlp_ner, nlp_spacy):
            if ent["entity_group"] == "ENFERMEDAD":
                aggregated[(filename, int(ent["start"]), int(ent["end"]))] += 1

    elapsed = time.time() - t_model
    model_times.append(elapsed)
    print(f"  fold={fold} seed={seed}: {elapsed:.1f}s")

    del nlp_ner, tokenizer_inf, modelo_inf
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# Voting consensus
mark_counter = defaultdict(int)
final_rows = []
for (filename, off0, off1), votes in sorted(aggregated.items()):
    if votes < vote_threshold:
        continue
    mark_counter[filename] += 1
    final_rows.append({
        "filename": filename,
        "mark": f"T{mark_counter[filename]}",
        "label": "ENFERMEDAD",
        "off0": off0, "off1": off1,
        "span": texts_by_filename[filename][off0:off1],
    })

df_pred = pd.DataFrame(final_rows, columns=["filename", "mark", "label", "off0", "off1", "span"])
df_pred.to_csv(pred_file, sep="\t", index=False)

total_s = time.time() - t0
stats = {
    "archivos_procesados": len(texts_by_filename),
    "modelos_ensamblados": len(ensemble_models),
    "voting_ratio": ENSEMBLE_VOTING_RATIO,
    "votos_requeridos": vote_threshold,
    "entidades_candidatas": len(aggregated),
    "entidades_detectadas": len(df_pred),
    "inference_total_seconds": total_s,
    "inference_avg_file_seconds": total_s / len(texts_by_filename),
    "inference_avg_model_seconds": float(np.mean(model_times)),
}
with open(f"{RESULTS_DIR}/inference_stats_ensemble.json", "w", encoding="utf-8") as f:
    json.dump(stats, f, ensure_ascii=False, indent=2)

print(f"Detected entities: {len(df_pred)} | Total time: {total_s:.1f}s | Predictions: {pred_file}")

Test documents: 250 | Models: 10 | Required votes: 5

Device set to use cuda:0
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

  fold=1 seed=123: 172.6s

Device set to use cuda:0

  fold=1 seed=4242: 167.9s

Device set to use cuda:0

  fold=2 seed=123: 168.7s

Device set to use cuda:0

  fold=2 seed=4242: 170.4s

Device set to use cuda:0

  fold=3 seed=123: 169.7s

Device set to use cuda:0

  fold=3 seed=4242: 169.5s

Device set to use cuda:0

  fold=4 seed=123: 171.2s

Device set to use cuda:0

  fold=4 seed=4242: 168.7s

Device set to use cuda:0

  fold=5 seed=123: 170.9s

Device set to use cuda:0

  fold=5 seed=4242: 172.7s
Detected entities: 7747 | Total time: 1707.7s | Predictions: results_roberta-es-clinical-trials-ner_kfold_multiseed/predictions_ensemble_k5_s2.tsv

## 5. Evaluation

### 5.1. Strict offset-based evaluation

Compare predictions against the gold standard using exact label and character-offset matches across all 250 documents.

In [13]:
def prf(tp, fp, fn):
    p = tp / (tp + fp) if (tp + fp) else 0.0
    r = tp / (tp + fn) if (tp + fn) else 0.0
    f = 2 * p * r / (p + r) if (p + r) else 0.0
    return p, r, f

df_gs   = pd.read_csv(ruta_gs,   sep="\t")
df_pred = pd.read_csv(pred_file, sep="\t")

set_gs   = set(zip(df_gs["filename"],   df_gs["label"],   df_gs["off0"],   df_gs["off1"]))
set_pred = set(zip(df_pred["filename"], df_pred["label"], df_pred["off0"], df_pred["off1"]))

tp, fp, fn = len(set_gs & set_pred), len(set_pred - set_gs), len(set_gs - set_pred)
precision, recall, fscore = prf(tp, fp, fn)
end_to_end_seconds = time.time() - end_to_end_start

strict_report = {
    "base_model": BASE_MODEL, "k_folds": K_FOLDS, "seeds": SEEDS,
    "ensemble_size": len(ensemble_models), "voting_ratio": ENSEMBLE_VOTING_RATIO,
    "tp": tp, "fp": fp, "fn": fn,
    "precision": precision, "recall": recall, "fscore": fscore,
    "end_to_end_seconds": end_to_end_seconds,
    "predictions_file": pred_file,
}
with open(f"{RESULTS_DIR}/strict_evaluation_ensemble.json", "w", encoding="utf-8") as f:
    json.dump(strict_report, f, ensure_ascii=False, indent=2)

print(f"Precision: {precision:.4f} | Recall: {recall:.4f} | F1: {fscore:.4f}")
print(f"TP={tp} FP={fp} FN={fn} | End-to-end: {end_to_end_seconds:.1f}s")

Precision: 0.7671 | Recall: 0.7538 | F1: 0.7604
TP=5943 FP=1804 FN=1941 | End-to-end: 1708.1s

### 5.2. Overlap evaluation (IoU)

Calculate precision, recall and F1 at different overlap thresholds between predicted and gold spans.

In [14]:
EVAL_SUMMARY_JSON = f"{RESULTS_DIR}/overlap_eval_summary.json"
processed_files   = sorted(texts_by_filename)
df_gs_filt        = df_gs

thresholds = [0.0, 0.5, 0.8]
results    = {t: {"tp": 0, "fp": 0, "fn": 0} for t in thresholds}

for filename in processed_files:
    gs_ints   = list(zip(df_gs_filt[df_gs_filt["filename"] == filename]["off0"],
                         df_gs_filt[df_gs_filt["filename"] == filename]["off1"]))
    pred_ints = list(zip(df_pred[df_pred["filename"] == filename]["off0"],
                         df_pred[df_pred["filename"] == filename]["off1"]))

    iou_matrix = sorted(
        [(max(0, min(p1,g1) - max(p0,g0)) / (max(p1,g1) - min(p0,g0)), pi, gi)
         for pi,(p0,p1) in enumerate(pred_ints)
         for gi,(g0,g1) in enumerate(gs_ints)
         if max(p1,g1) - min(p0,g0) > 0 and min(p1,g1) - max(p0,g0) > 0],
        reverse=True,
    )

    for t in thresholds:
        matched_p, matched_g = set(), set()
        for iou, pi, gi in iou_matrix:
            if iou >= t and pi not in matched_p and gi not in matched_g:
                matched_p.add(pi); matched_g.add(gi)
        tp = len(matched_p)
        results[t]["tp"] += tp
        results[t]["fp"] += len(pred_ints) - tp
        results[t]["fn"] += len(gs_ints)   - tp

report = {"Estricta": {**dict(zip(["tp","fp","fn"],[strict_report["tp"],strict_report["fp"],strict_report["fn"]])),
                       "precision": strict_report["precision"], "recall": strict_report["recall"], "fscore": strict_report["fscore"]}}
print(f"Strict: P={strict_report['precision']:.4f} R={strict_report['recall']:.4f} F1={strict_report['fscore']:.4f}\n")

for t in thresholds:
    tp, fp, fn = results[t]["tp"], results[t]["fp"], results[t]["fn"]
    p, r, f1 = prf(tp, fp, fn)
    report[f"IoU >= {t}"] = {"tp": tp, "fp": fp, "fn": fn, "precision": round(p,4), "recall": round(r,4), "fscore": round(f1,4)}
    print(f"IoU >= {t}: P={p:.4f} R={r:.4f} F1={f1:.4f} | TP={tp} FP={fp} FN={fn}")

with open(EVAL_SUMMARY_JSON, "w", encoding="utf-8") as f:
    json.dump(report, f, ensure_ascii=False, indent=2)

Strict: P=0.7671 R=0.7538 F1=0.7604

IoU >= 0.0: P=0.8776 R=0.8624 F1=0.8699 | TP=6799 FP=948 FN=1085
IoU >= 0.5: P=0.8339 R=0.8194 F1=0.8266 | TP=6460 FP=1287 FN=1424
IoU >= 0.8: P=0.7782 R=0.7647 F1=0.7714 | TP=6029 FP=1718 FN=1855